import assert from "node:assert/strict"
import { readFile } from "node:fs/promises"
import { describe, it } from "node:test"

describe("Anatomy admin browser table UI", () => {
  it("exposes top and bottom horizontal scroll tracks with resizable columns", async () => {
    const pageSource = await readFile(new URL("../app/admin/anatomy/page.tsx", import.meta.url), "utf8")
    const scrollSource = await readFile(new URL("../app/admin/anatomy/synced-horizontal-scroll.tsx", import.meta.url), "utf8")

    assert.match(pageSource, /<SyncedHorizontalScroll/)
    assert.match(scrollSource, /data-anatomy-table-scroll="top"/)
    assert.match(scrollSource, /data-anatomy-table-scroll="bottom"/)
    assert.match(pageSource, /data-anatomy-resizable-column/)
  })

  it("keeps anatomy query controls and table headers sticky without top-loading count chips", async () => {
    const pageSource = await readFile(new URL("../app/admin/anatomy/page.tsx", import.meta.url), "utf8")
    const scrollSource = await readFile(new URL("../app/admin/anatomy/synced-horizontal-scroll.tsx", import.meta.url), "utf8")
    const stickyFrameSource = await readFile(new URL("../app/admin/anatomy/anatomy-browser-sticky-frame.tsx", import.meta.url), "utf8")
    const globalsSource = await readFile(new URL("../app/globals.css", import.meta.url), "utf8")
    const browserStart = pageSource.indexOf("function AnatomyDatabaseBrowser")
    const maintenanceStart = pageSource.indexOf("function MaintenanceView")
    const browserBody = pageSource.slice(browserStart, maintenanceStart)
    const maintenanceBody = pageSource.slice(maintenanceStart)

    assert.match(pageSource, /<AnatomyBrowserStickyFrame/)
    assert.match(stickyFrameSource, /data-anatomy-browser-toolbar/)
    assert.match(stickyFrameSource, /data-compact/)
    assert.match(stickyFrameSource, /closest\("\.ml-app-scroll"\)/)
    assert.match(stickyFrameSource, /sticky top-0/)
    assert.match(pageSource, /data-anatomy-search-label/)
    assert.match(pageSource, /data-anatomy-compact-control/)
    assert.match(pageSource, /data-anatomy-view-tabs/)
    assert.match(globalsSource, /\[data-anatomy-browser-toolbar\]\[data-compact="true"\]/)
    assert.match(pageSource, /className="p-0 sm:p-6 lg:p-8"/)
    assert.match(pageSource, /contentClassName="gap-0 sm:gap-6"/)
    assert.match(pageSource, /data-anatomy-table-header/)
    assert.match(pageSource, /data-anatomy-table-header-cell/)
    assert.match(scrollSource, /--anatomy-browser-sticky-offset/)
    assert.doesNotMatch(browserBody, /counts\.map/)
    assert.match(maintenanceBody, /counts\.map/)
  })

  it("surfaces full citation backlog and clickable external identifier detail", async () => {
    const pageSource = await readFile(new URL("../app/admin/anatomy/page.tsx", import.meta.url), "utf8")

    assert.match(pageSource, /const ANATOMY_DETAIL_LOOKUP_TAKE = 2000/)
    assert.match(pageSource, /prisma\.anatomyCitation\.findMany\({[\s\S]*take: ANATOMY_DETAIL_LOOKUP_TAKE/)
    assert.match(pageSource, /prisma\.externalAnatomyIdentifier\.findMany\({[\s\S]*take: ANATOMY_DETAIL_LOOKUP_TAKE/)
    assert.match(pageSource, /function externalIdentifierHref/)
    assert.match(pageSource, /function citationHref/)
    assert.match(pageSource, /function CollapsedEvidenceSection/)
    assert.match(pageSource, /<CollapsedEvidenceSection title="Citations"/)
    assert.match(pageSource, /<CollapsedEvidenceSection title="External IDs"/)
    assert.match(pageSource, /target="_blank"/)
  })

  it("surfaces spatial review state in counts, quick queries, and entity details", async () => {
    const pageSource = await readFile(new URL("../app/admin/anatomy/page.tsx", import.meta.url), "utf8")

    assert.match(pageSource, /spatial-review-queue/)
    assert.match(pageSource, /Spatial models/)
    assert.match(pageSource, /Spatial maps/)
    assert.match(pageSource, /Movement visuals/)
    assert.match(pageSource, /function selectedEntitySpatialMappings/)
    assert.match(pageSource, /function selectedEntityMovementVisualizations/)
    assert.match(pageSource, /Spatial mappings/)
    assert.match(pageSource, /Movement visualizations/)
    assert.match(pageSource, /anatomySpatialEntityMap\.findMany/)
    assert.match(pageSource, /anatomyMovementVisualization\.findMany/)
  })

  it("surfaces visual media review, candidate approval, and BodyParts3D import controls", async () => {
    const pageSource = await readFile(new URL("../app/admin/anatomy/page.tsx", import.meta.url), "utf8")
    const actionsSource = await readFile(new URL("../app/admin/anatomy/actions.ts", import.meta.url), "utf8")
    const importFieldsSource = await readFile(new URL("../app/admin/anatomy/bodyparts3d-import-fields.tsx", import.meta.url), "utf8")
    const reviewHelperSource = await readFile(new URL("../lib/anatomy-media-review.ts", import.meta.url), "utf8")

    assert.match(pageSource, /function MediaReviewPanel/)
    assert.match(pageSource, /<img src=\{previewUrl\}/)
    assert.match(pageSource, /Replacement flow/)
    assert.match(pageSource, /function mediaBodyParts3dSourceUrl/)
    assert.match(pageSource, /function mediaBodyParts3dComposerUrl/)
    assert.match(pageSource, /Open BodyParts3D composer/)
    assert.match(pageSource, /Open generated image/)
    assert.match(pageSource, /Open stored image/)
    assert.match(pageSource, /Link Existing Image/)
    assert.match(pageSource, /Sort order/)
    assert.match(pageSource, /updateAnatomyMediaReviewAction/)
    assert.match(pageSource, /linkAnatomyMediaAssetAction/)
    assert.match(pageSource, /importBodyParts3dMediaAction/)
    assert.match(pageSource, /function mediaReviewRows/)
    assert.match(pageSource, /function mediaRoleKey/)
    assert.match(pageSource, /take: 500/)
    assert.match(actionsSource, /uploadAnatomyMediaToR2/)
    assert.match(actionsSource, /prisma\.\$transaction/)
    assert.match(actionsSource, /bodyParts3dSourceDescriptor/)
    assert.match(actionsSource, /function bodyParts3dImportSource/)
    assert.match(actionsSource, /function bodyParts3dRequestImportDescriptor/)
    assert.match(actionsSource, /sameBodyParts3dPartIds\(descriptor\.partIds, expectedPartIds\)/)
    assert.match(actionsSource, /descriptor\.cameraMode !== expectedCameraMode/)
    assert.match(actionsSource, /anatomyMediaViewRequest\.delete/)
    assert.match(actionsSource, /sourceKey: importSource\.sourceKey/)
    assert.match(actionsSource, /bodyparts3dImageWidth: importSource\.imageWidth/)
    assert.match(actionsSource, /width: importSource\.imageWidth/)
    assert.match(actionsSource, /bodyparts3dCameraParameters/)
    assert.match(actionsSource, /treeName/)
    assert.match(actionsSource, /reviewStatus: "APPROVED"/)
    assert.match(actionsSource, /bodyparts3dSourceUrl: sourceUrl/)
    assert.match(reviewHelperSource, /Superior View/)
    assert.match(reviewHelperSource, /Inferior View/)
    assert.match(reviewHelperSource, /Transverse View/)
    assert.match(importFieldsSource, /bodyParts3dImageUrl/)
    assert.match(importFieldsSource, /bodyParts3dComposerUrl/)
    assert.match(importFieldsSource, /safeBodyParts3dRenderableImageUrl/)
    assert.match(importFieldsSource, /copyResetTimeoutRef/)
    assert.match(importFieldsSource, /window\.clearTimeout/)
    assert.match(importFieldsSource, /View shortcuts/)
    assert.match(importFieldsSource, /Transverse is an approximation using the top orientation/)
    assert.match(importFieldsSource, /Open BodyParts3D parts composer/)
    assert.match(importFieldsSource, /Open generated image/)
    assert.match(importFieldsSource, /current preset preview/)
    assert.match(importFieldsSource, /Copy generated image URL/)
    assert.match(importFieldsSource, /Leave blank when a preset preview looks right/)
    assert.match(importFieldsSource, /Custom BodyParts3D URL/)
    assert.match(importFieldsSource, /Open BodyParts3D home/)
    assert.match(pageSource, /function MediaViewCoverageChips/)
    assert.match(pageSource, /Request better view/)
    assert.match(pageSource, /createAnatomyMediaViewRequestAction/)
    assert.match(pageSource, /Open media view requests/)
    assert.match(pageSource, /openRows\.length === 0/)
    assert.match(pageSource, /openRows\.map/)
    assert.match(actionsSource, /createAnatomyMediaViewRequestAction/)
    assert.match(actionsSource, /linkReviewStatus: "NEEDS_REVIEW"/)
  })

  it("shows complete anatomy source metadata fields in the admin source form", async () => {
    const pageSource = await readFile(new URL("../app/admin/anatomy/page.tsx", import.meta.url), "utf8")
    const actionsSource = await readFile(new URL("../app/admin/anatomy/actions.ts", import.meta.url), "utf8")

    assert.match(pageSource, /name="license_url"/)
    assert.match(pageSource, /name="usage_scope"/)
    assert.match(pageSource, /name="accessed_at"/)
    assert.match(pageSource, /name="notes"/)
    assert.match(actionsSource, /parseAnatomyAdminSourceInput/)
    assert.match(actionsSource, /licenseUrl: sourceInput\.licenseUrl/)
    assert.match(actionsSource, /usageScope: sourceInput\.usageScope/)
    assert.match(actionsSource, /accessedAt: sourceInput\.accessedAt/)
    assert.match(actionsSource, /notes: sourceInput\.notes/)
  })
})
