import assert from "node:assert/strict"
import { readFileSync, existsSync } from "node:fs"
import { describe, it } from "node:test"

const schema = readFileSync(new URL("../prisma/schema.prisma", import.meta.url), "utf8")
const actions = readFileSync(new URL("../app/calendar/actions.ts", import.meta.url), "utf8")
const bookingSettingsPage = readFileSync(new URL("../app/calendar/booking/page.tsx", import.meta.url), "utf8")
const bookingPage = readFileSync(new URL("../app/book/[practiceSlug]/page.tsx", import.meta.url), "utf8")
const publicBookingPage = readFileSync(new URL("../app/book/public-booking-page.tsx", import.meta.url), "utf8")
const bookingPicker = readFileSync(new URL("../app/book/[practiceSlug]/booking-picker.tsx", import.meta.url), "utf8")
const sequenceOptionsRoute = readFileSync(new URL("../app/api/book/[practiceSlug]/sequence-options/route.ts", import.meta.url), "utf8")
const publicBookingSequences = readFileSync(new URL("../lib/public-booking-sequences.js", import.meta.url), "utf8")

describe("calendar booking settings schema and route surface", () => {
  it("defines policy, capacity, waitlist, pressure, and service role storage", () => {
    assert.match(schema, /enum BookingApprovalMode/)
    assert.match(schema, /enum BookingCapacityPeriod/)
    assert.match(schema, /enum ServiceBookingRole/)
    assert.match(schema, /enum BookingWaitlistStatus/)
    assert.match(schema, /model BookingPolicy/)
    assert.match(schema, /model ProviderBookingPolicy/)
    assert.match(schema, /model ProviderBookingCapacityRule/)
    assert.match(schema, /model BookingGroup/)
    assert.match(schema, /model BookingWaitlistEntry/)
    assert.match(schema, /bookingRole\s+ServiceBookingRole/)
    assert.match(schema, /countsTowardMassageCapacity\s+Boolean/)
    assert.match(schema, /requestedPressureLevel\s+Int\?/)
    assert.match(schema, /publicLocationLabel\s+String\?/)
    assert.match(schema, /publicLatitude\s+Float\?/)
    assert.match(schema, /publicLongitude\s+Float\?/)
    assert.match(schema, /publicBookingStateSlug\s+String\?/)
    assert.match(schema, /publicBookingSlug\s+String\?/)
    assert.match(schema, /@@unique\(\[publicBookingStateSlug,\s*publicBookingSlug\]\)/)
    assert.match(schema, /userId\s+String\?/)
    assert.match(schema, /user\s+User\?\s+@relation/)
    assert.match(schema, /requireClientAccount\s+Boolean\s+@default\(false\)/)
  })

  it("exposes booking settings, sequence request, waitlist, and conversion actions", () => {
    assert.equal(existsSync(new URL("../app/calendar/booking/page.tsx", import.meta.url)), true)
    assert.equal(existsSync(new URL("../lib/public-booking-url.js", import.meta.url)), true)
    assert.equal(existsSync(new URL("../app/book/[practiceSlug]/[bookingSlug]/page.tsx", import.meta.url)), true)
    assert.match(actions, /export async function saveBookingPolicyAction/)
    assert.match(actions, /export async function saveProviderBookingPolicyAction/)
    assert.match(actions, /export async function saveProviderCapacityRulesAction/)
    assert.match(actions, /export async function requestBookingSequenceAction/)
    assert.match(actions, /export async function joinBookingWaitlistAction/)
    assert.match(actions, /export async function convertWaitlistEntryAction/)
    assert.equal(existsSync(new URL("../app/api/book/[practiceSlug]/sequence-options/route.ts", import.meta.url)), true)
  })

  it("organizes booking settings into tabs and exposes public booking links", () => {
    assert.match(bookingSettingsPage, /Tabs defaultValue="booking-rules"/)
    assert.match(bookingSettingsPage, /TabsTrigger value="public-page"/)
    assert.match(bookingSettingsPage, /TabsTrigger value="providers"/)
    assert.match(bookingSettingsPage, /TabsTrigger value="capacity"/)
    assert.match(bookingSettingsPage, /PublicBookingLinkCard/)
    assert.match(bookingSettingsPage, /savePublicBookingUrlAction/)
  })

  it("allows anonymous public booking while keeping account-required gates explicit", () => {
    assert.doesNotMatch(publicBookingPage, /if \(!session\?\.user\?\.id\)/)
    assert.match(publicBookingPage, /requireClientAccount/)
    assert.match(publicBookingPage, /viewerUserId/)
    assert.match(bookingPicker, /name="guestName"/)
    assert.match(bookingPicker, /name="guestEmail"/)
    assert.match(bookingPicker, /name="guestPhone"/)
    assert.match(bookingPicker, /AccountBenefitsCard/)
  })

  it("keeps public sequence loading anonymous-capable with account-aware cache keys", () => {
    assert.doesNotMatch(sequenceOptionsRoute, /return NextResponse\.json\(\{ error: "Unauthorized" \}/)
    assert.match(sequenceOptionsRoute, /viewerUserId/)
    assert.match(sequenceOptionsRoute, /account-required/)
    assert.match(publicBookingSequences, /viewerUserId/)
    assert.match(publicBookingSequences, /allowGuestBooking/)
    assert.match(publicBookingSequences, /requireClientAccount/)
    assert.match(publicBookingSequences, /accountMode/)
  })

  it("loads public booking sequence options lazily instead of precomputing every group", () => {
    assert.doesNotMatch(bookingPage, /buildSequentialBookingOptions/)
    assert.doesNotMatch(bookingPage, /function addOnCombinations/)
    assert.doesNotMatch(bookingPage, /sequenceGroups/)
    assert.match(bookingPicker, /\/api\/book\/\$\{model\.practiceSlug\}\/sequence-options/)
    assert.doesNotMatch(bookingPicker, /sequenceGroups/)
    assert.match(publicBookingSequences, /createAsyncKeyedTtlCache/)
    assert.match(actions, /MAX_PUBLIC_ADD_ONS/)
    assert.match(actions, /publicBookingSequenceOptions/)
  })
})
