import assert from "node:assert/strict"
import { describe, it } from "node:test"
import { FEATURE_KEYS } from "../lib/membership.js"
import {
  DEFAULT_CHIMER_SETTINGS,
  sanitizeChimerSettingsForEntitlements,
} from "../lib/chimer-timer.js"

describe("Chimer entitlement-aware settings", () => {
  it("resets Eldora Novatrix controls without premium background access", () => {
    const input = {
      backgroundId: "eldora-novatrix-background",
      eldoraNovatrixPaletteMode: "harmony",
      eldoraNovatrixPrimaryColor: "#AABBCC",
      eldoraNovatrixHarmony: "triad",
      eldoraNovatrixColor: "#DDEEFF",
      eldoraNovatrixSpeed: 2.4,
      eldoraNovatrixAmplitude: 0.3,
    }

    const freeSettings = sanitizeChimerSettingsForEntitlements(input, [])

    assert.equal(freeSettings.backgroundId, DEFAULT_CHIMER_SETTINGS.backgroundId)
    assert.equal(freeSettings.eldoraNovatrixPaletteMode, DEFAULT_CHIMER_SETTINGS.eldoraNovatrixPaletteMode)
    assert.equal(freeSettings.eldoraNovatrixPrimaryColor, DEFAULT_CHIMER_SETTINGS.eldoraNovatrixPrimaryColor)
    assert.equal(freeSettings.eldoraNovatrixHarmony, DEFAULT_CHIMER_SETTINGS.eldoraNovatrixHarmony)
    assert.equal(freeSettings.eldoraNovatrixColor, DEFAULT_CHIMER_SETTINGS.eldoraNovatrixColor)
    assert.equal(freeSettings.eldoraNovatrixSpeed, DEFAULT_CHIMER_SETTINGS.eldoraNovatrixSpeed)
    assert.equal(freeSettings.eldoraNovatrixAmplitude, DEFAULT_CHIMER_SETTINGS.eldoraNovatrixAmplitude)

    const premiumSettings = sanitizeChimerSettingsForEntitlements(input, [FEATURE_KEYS.premiumBackgrounds])

    assert.equal(premiumSettings.backgroundId, "eldora-novatrix-background")
    assert.equal(premiumSettings.eldoraNovatrixPaletteMode, "harmony")
    assert.equal(premiumSettings.eldoraNovatrixPrimaryColor, "#AABBCC")
    assert.equal(premiumSettings.eldoraNovatrixHarmony, "triad")
    assert.equal(premiumSettings.eldoraNovatrixColor, "#DDEEFF")
    assert.equal(premiumSettings.eldoraNovatrixSpeed, 2.4)
    assert.equal(premiumSettings.eldoraNovatrixAmplitude, 0.3)
  })

  it("resets Eldora Hacker controls without premium background access", () => {
    const input = {
      backgroundId: "eldora-hacker-background",
      eldoraHackerPaletteMode: "harmony",
      eldoraHackerPrimaryColor: "#00D4FF",
      eldoraHackerHarmony: "triad",
      eldoraHackerColor: "#22D3EE",
      eldoraHackerSpeed: 2.4,
      eldoraHackerFontSize: 22,
    }

    const freeSettings = sanitizeChimerSettingsForEntitlements(input, [])

    assert.equal(freeSettings.backgroundId, DEFAULT_CHIMER_SETTINGS.backgroundId)
    assert.equal(freeSettings.eldoraHackerPaletteMode, DEFAULT_CHIMER_SETTINGS.eldoraHackerPaletteMode)
    assert.equal(freeSettings.eldoraHackerPrimaryColor, DEFAULT_CHIMER_SETTINGS.eldoraHackerPrimaryColor)
    assert.equal(freeSettings.eldoraHackerHarmony, DEFAULT_CHIMER_SETTINGS.eldoraHackerHarmony)
    assert.equal(freeSettings.eldoraHackerColor, DEFAULT_CHIMER_SETTINGS.eldoraHackerColor)
    assert.equal(freeSettings.eldoraHackerSpeed, DEFAULT_CHIMER_SETTINGS.eldoraHackerSpeed)
    assert.equal(freeSettings.eldoraHackerFontSize, DEFAULT_CHIMER_SETTINGS.eldoraHackerFontSize)

    const premiumSettings = sanitizeChimerSettingsForEntitlements(input, [FEATURE_KEYS.premiumBackgrounds])

    assert.equal(premiumSettings.backgroundId, "eldora-hacker-background")
    assert.equal(premiumSettings.eldoraHackerPaletteMode, "harmony")
    assert.equal(premiumSettings.eldoraHackerPrimaryColor, "#00D4FF")
    assert.equal(premiumSettings.eldoraHackerHarmony, "triad")
    assert.equal(premiumSettings.eldoraHackerColor, "#22D3EE")
    assert.equal(premiumSettings.eldoraHackerSpeed, 2.4)
    assert.equal(premiumSettings.eldoraHackerFontSize, 22)
  })

  it("resets Eldora Photon Beam controls without premium background access", () => {
    const input = {
      backgroundId: "eldora-photon-beam",
      eldoraPhotonBeamPaletteMode: "harmony",
      eldoraPhotonBeamPrimaryColor: "#00D4FF",
      eldoraPhotonBeamHarmony: "triad",
      eldoraPhotonBeamColorBg: "#010203",
      eldoraPhotonBeamColorLine: "#123456",
      eldoraPhotonBeamColorSignal: "#ABCDEF",
      eldoraPhotonBeamUseColor2: true,
      eldoraPhotonBeamColorSignal2: "#FEDCBA",
      eldoraPhotonBeamUseColor3: true,
      eldoraPhotonBeamColorSignal3: "#22D3EE",
      eldoraPhotonBeamLineCount: 120,
      eldoraPhotonBeamSpreadHeight: 64,
      eldoraPhotonBeamSpreadDepth: 18,
      eldoraPhotonBeamCurveLength: 80,
      eldoraPhotonBeamStraightLength: 160,
      eldoraPhotonBeamCurvePower: 1.25,
      eldoraPhotonBeamWaveSpeed: 4.5,
      eldoraPhotonBeamWaveHeight: 0.6,
      eldoraPhotonBeamLineOpacity: 0.82,
      eldoraPhotonBeamSignalCount: 140,
      eldoraPhotonBeamSpeedGlobal: 1.4,
      eldoraPhotonBeamTrailLength: 8,
      eldoraPhotonBeamBloomStrength: 4.2,
      eldoraPhotonBeamBloomRadius: 1.1,
    }

    const freeSettings = sanitizeChimerSettingsForEntitlements(input, [])

    assert.equal(freeSettings.backgroundId, DEFAULT_CHIMER_SETTINGS.backgroundId)
    assert.equal(freeSettings.eldoraPhotonBeamPaletteMode, DEFAULT_CHIMER_SETTINGS.eldoraPhotonBeamPaletteMode)
    assert.equal(freeSettings.eldoraPhotonBeamPrimaryColor, DEFAULT_CHIMER_SETTINGS.eldoraPhotonBeamPrimaryColor)
    assert.equal(freeSettings.eldoraPhotonBeamHarmony, DEFAULT_CHIMER_SETTINGS.eldoraPhotonBeamHarmony)
    assert.equal(freeSettings.eldoraPhotonBeamColorBg, DEFAULT_CHIMER_SETTINGS.eldoraPhotonBeamColorBg)
    assert.equal(freeSettings.eldoraPhotonBeamColorLine, DEFAULT_CHIMER_SETTINGS.eldoraPhotonBeamColorLine)
    assert.equal(freeSettings.eldoraPhotonBeamColorSignal, DEFAULT_CHIMER_SETTINGS.eldoraPhotonBeamColorSignal)
    assert.equal(freeSettings.eldoraPhotonBeamUseColor2, DEFAULT_CHIMER_SETTINGS.eldoraPhotonBeamUseColor2)
    assert.equal(freeSettings.eldoraPhotonBeamColorSignal2, DEFAULT_CHIMER_SETTINGS.eldoraPhotonBeamColorSignal2)
    assert.equal(freeSettings.eldoraPhotonBeamUseColor3, DEFAULT_CHIMER_SETTINGS.eldoraPhotonBeamUseColor3)
    assert.equal(freeSettings.eldoraPhotonBeamColorSignal3, DEFAULT_CHIMER_SETTINGS.eldoraPhotonBeamColorSignal3)
    assert.equal(freeSettings.eldoraPhotonBeamLineCount, DEFAULT_CHIMER_SETTINGS.eldoraPhotonBeamLineCount)
    assert.equal(freeSettings.eldoraPhotonBeamSpreadHeight, DEFAULT_CHIMER_SETTINGS.eldoraPhotonBeamSpreadHeight)
    assert.equal(freeSettings.eldoraPhotonBeamSpreadDepth, DEFAULT_CHIMER_SETTINGS.eldoraPhotonBeamSpreadDepth)
    assert.equal(freeSettings.eldoraPhotonBeamCurveLength, DEFAULT_CHIMER_SETTINGS.eldoraPhotonBeamCurveLength)
    assert.equal(freeSettings.eldoraPhotonBeamStraightLength, DEFAULT_CHIMER_SETTINGS.eldoraPhotonBeamStraightLength)
    assert.equal(freeSettings.eldoraPhotonBeamCurvePower, DEFAULT_CHIMER_SETTINGS.eldoraPhotonBeamCurvePower)
    assert.equal(freeSettings.eldoraPhotonBeamWaveSpeed, DEFAULT_CHIMER_SETTINGS.eldoraPhotonBeamWaveSpeed)
    assert.equal(freeSettings.eldoraPhotonBeamWaveHeight, DEFAULT_CHIMER_SETTINGS.eldoraPhotonBeamWaveHeight)
    assert.equal(freeSettings.eldoraPhotonBeamLineOpacity, DEFAULT_CHIMER_SETTINGS.eldoraPhotonBeamLineOpacity)
    assert.equal(freeSettings.eldoraPhotonBeamSignalCount, DEFAULT_CHIMER_SETTINGS.eldoraPhotonBeamSignalCount)
    assert.equal(freeSettings.eldoraPhotonBeamSpeedGlobal, DEFAULT_CHIMER_SETTINGS.eldoraPhotonBeamSpeedGlobal)
    assert.equal(freeSettings.eldoraPhotonBeamTrailLength, DEFAULT_CHIMER_SETTINGS.eldoraPhotonBeamTrailLength)
    assert.equal(freeSettings.eldoraPhotonBeamBloomStrength, DEFAULT_CHIMER_SETTINGS.eldoraPhotonBeamBloomStrength)
    assert.equal(freeSettings.eldoraPhotonBeamBloomRadius, DEFAULT_CHIMER_SETTINGS.eldoraPhotonBeamBloomRadius)

    const premiumSettings = sanitizeChimerSettingsForEntitlements(input, ["premium_backgrounds"])

    assert.equal(premiumSettings.backgroundId, "eldora-photon-beam")
    assert.equal(premiumSettings.eldoraPhotonBeamPaletteMode, "harmony")
    assert.equal(premiumSettings.eldoraPhotonBeamPrimaryColor, "#00D4FF")
    assert.equal(premiumSettings.eldoraPhotonBeamHarmony, "triad")
    assert.equal(premiumSettings.eldoraPhotonBeamColorBg, "#010203")
    assert.equal(premiumSettings.eldoraPhotonBeamColorLine, "#123456")
    assert.equal(premiumSettings.eldoraPhotonBeamColorSignal, "#ABCDEF")
    assert.equal(premiumSettings.eldoraPhotonBeamUseColor2, true)
    assert.equal(premiumSettings.eldoraPhotonBeamColorSignal2, "#FEDCBA")
    assert.equal(premiumSettings.eldoraPhotonBeamUseColor3, true)
    assert.equal(premiumSettings.eldoraPhotonBeamColorSignal3, "#22D3EE")
    assert.equal(premiumSettings.eldoraPhotonBeamLineCount, 120)
    assert.equal(premiumSettings.eldoraPhotonBeamSpreadHeight, 64)
    assert.equal(premiumSettings.eldoraPhotonBeamSpreadDepth, 18)
    assert.equal(premiumSettings.eldoraPhotonBeamCurveLength, 80)
    assert.equal(premiumSettings.eldoraPhotonBeamStraightLength, 160)
    assert.equal(premiumSettings.eldoraPhotonBeamCurvePower, 1.25)
    assert.equal(premiumSettings.eldoraPhotonBeamWaveSpeed, 4.5)
    assert.equal(premiumSettings.eldoraPhotonBeamWaveHeight, 0.6)
    assert.equal(premiumSettings.eldoraPhotonBeamLineOpacity, 0.82)
    assert.equal(premiumSettings.eldoraPhotonBeamSignalCount, 140)
    assert.equal(premiumSettings.eldoraPhotonBeamSpeedGlobal, 1.4)
    assert.equal(premiumSettings.eldoraPhotonBeamTrailLength, 8)
    assert.equal(premiumSettings.eldoraPhotonBeamBloomStrength, 4.2)
    assert.equal(premiumSettings.eldoraPhotonBeamBloomRadius, 1.1)
  })

  it("strips custom colors for users without the Chimer custom colors feature", () => {
    const settings = sanitizeChimerSettingsForEntitlements({
      primaryFontColor: "#000000",
      secondaryFontColor: "#123456",
      clockModeFontColor: "#654321",
      movingBackgroundMainColor: "#ABCDEF",
      movingBackgroundOrbColor: "#FEDCBA",
      movingBackgroundEnabled: false,
      backgroundId: "aceternity-aurora",
      sparklesParticleColor: "#ABC123",
      sparklesParticleDensity: 180,
      sparklesSpeed: 6,
      gradientAnimationFirstColor: "#112233",
      gradientAnimationSpeed: 2,
      animateUiGradientPrimaryColor: "#102030",
      animateUiGradientHarmony: "split-complementary",
      animateUiGradientOpacity: 0.42,
      animateUiStarsColor: "#EAF6FF",
      animateUiStarsSpeed: 72,
      animateUiStarsDensity: 1.2,
      animateUiStarsParallax: 0.08,
      animateUiHoleStrokeColor: "#112233",
      animateUiHoleParticleColor: "#EAF6FF",
      animateUiHoleLineCount: 72,
      animateUiHoleDiscCount: 64,
      chamaacLightSpeedWarpSpeed: 3.5,
      chamaacLightSpeedWarpSpeedVersion: 2,
      chamaacLightSpeedParticleCount: 180,
      chamaacLightSpeedLightColor: "#33B2FF",
      chamaacLightSpeedIntensity: 4.5,
      chamaacLightSpeedRadius: 42,
      chamaacLightSpeedCylinderLength: 220,
      chamaacElectricMistColor: "#33B2FF",
      chamaacElectricMistSpeed: 250,
      chamaacElectricMistControlVersion: 2,
      chamaacElectricMistDetail: 2.4,
      chamaacElectricMistDistortion: 5.5,
      chamaacElectricMistBrightness: 80,
      chamaacAstralFlowPaletteMode: "harmony",
      chamaacAstralFlowPrimaryColor: "#33B2FF",
      chamaacAstralFlowHarmony: "split-complementary",
      chamaacAstralFlowColorOne: "#112233",
      chamaacAstralFlowColorTwo: "#445566",
      chamaacAstralFlowColorThree: "#778899",
      chamaacAstralFlowSpeed: 2.1,
      chamaacAstralFlowFlowMin: 4.2,
      chamaacAstralFlowFlowMax: 8.4,
      chamaacDeepSpaceNebulaPaletteMode: "harmony",
      chamaacDeepSpaceNebulaPrimaryColor: "#763B65",
      chamaacDeepSpaceNebulaHarmony: "complementary",
      chamaacDeepSpaceNebulaColorOne: "#5EFFF4",
      chamaacDeepSpaceNebulaColorTwo: "#763B65",
      chamaacDeepSpaceNebulaColorThree: "#1A0B2E",
      chamaacDeepSpaceNebulaSpeed: 3.6,
      chamaacGridBloomColor: "#E040FB",
      chamaacGridBloomSpeed: 2.4,
      chamaacGridBloomGridScale: 18,
      chamaacGridBloomRotationSpeed: 0.8,
      chamaacGridBloomFadeFalloff: 14,
      chamaacGridBloomDistortionAmount: 0.18,
      chamaacGridBloomFlowSpeedX: -0.6,
      chamaacGridBloomFlowSpeedY: 0.5,
      chamaacLiquidChromePaletteMode: "harmony",
      chamaacLiquidChromePrimaryColor: "#C0C0C0",
      chamaacLiquidChromeHarmony: "monochromatic",
      chamaacLiquidChromeColorOne: "#C0C0C0",
      chamaacLiquidChromeColorTwo: "#4A4A4A",
      chamaacLiquidChromeFlowSpeed: 1.4,
      chamaacLiquidChromeTimeScale: 0.4,
      chamaacWavesPaletteMode: "harmony",
      chamaacWavesPrimaryColor: "#071697",
      chamaacWavesHarmony: "triad",
      chamaacWavesBackgroundColor: "#000000",
      chamaacWavesColorOne: "#071697",
      chamaacWavesColorTwo: "#00D4FF",
      chamaacWavesColorThree: "#000000",
      chamaacWavesSpeedX: 0.08,
      chamaacWavesSpeedY: 0.04,
      chamaacWavesAmplitude: 48,
      chamaacSynthesisPaletteMode: "harmony",
      chamaacSynthesisPrimaryColor: "#33B2FF",
      chamaacSynthesisHarmony: "split-complementary",
      chamaacSynthesisColorOne: "#112233",
      chamaacSynthesisColorTwo: "#445566",
      chamaacSynthesisColorThree: "#778899",
      chamaacSynthesisSpeed: 1.8,
      chamaacSynthesisComplexity: 16,
      chamaacSynthesisScale: 2.4,
      chamaacSynthesisDistortion: 1.4,
      chamaacSynthesisGlowIntensity: 1.6,
      chamaacSynthesisFlowFrequency: 7.5,
      backgroundLinesDuration: 16,
      wavyBackgroundFill: "#111111",
      wavyColorOne: "#ABC123",
      wavyWaveWidth: 80,
      wavySpeed: "slow",
      wavyWaveOpacity: 0.8,
      shootingStarsStarColor: "#101010",
      shootingStarsTrailColor: "#202020",
      shootingStarsShootingStarColor: "#303030",
      shootingStarsDensity: 0.00028,
      shootingStarsTwinkle: false,
      shootingStarsTwinkleSpeed: 2,
      shootingStarsShootingSpeed: 1.8,
      shootingStarsFrequency: 1.6,
      canvasRevealDotsBackgroundColor: "#040404",
      canvasRevealDotsDotColor: "#00FFCC",
      canvasRevealDotsAccentColor: "#CC7722",
      canvasRevealDotsDotSize: 3.2,
      canvasRevealDotsDotSpacing: 14,
      canvasRevealDotsOpacity: 0.6,
      canvasRevealDotsAnimationSpeed: 0.8,
      canvasRevealDotsShowGradient: false,
      spotlightColor: "#AABBCC",
      spotlightOpacity: 1.4,
      spotlightWidth: 820,
      spotlightHeight: 1700,
      spotlightSmallWidth: 360,
      spotlightTranslateY: -520,
      spotlightDuration: 12,
      spotlightXOffset: 180,
      lampBackgroundColor: "#050505",
      lampColor: "#22D3EE",
      lampGlowOpacity: 0.9,
      lampBeamWidth: 780,
      lampGlowWidth: 720,
      lampVerticalOffset: -200,
      lampPulseSpeed: 14,
      vortexBackgroundColor: "#040404",
      vortexBaseHue: 280,
      vortexParticleCount: 620,
      vortexRangeY: 200,
      vortexBaseSpeed: 0.5,
      vortexRangeSpeed: 1.8,
      vortexBaseRadius: 1.7,
      vortexRangeRadius: 3.2,
      auroraBarsBackgroundColor: "#010203",
      auroraBarsPaletteMode: "custom",
      auroraBarsPrimaryColor: "#334455",
      auroraBarsColorOne: "#AABBCC",
      auroraBarsColorTwo: "#223344",
      auroraBarsColorThree: "#445566",
      auroraBarsColorFour: "#667788",
      auroraBarsColorFive: "#8899AA",
      auroraBarsBarCount: 64,
      auroraBarsSpeed: 1.5,
      auroraBarsBlur: 9,
      auroraBarsGap: 7,
      auroraBarsMaxHeightRatio: 0.84,
      auroraBarsMinHeightRatio: 0.2,
      pixelLiquidBackgroundColor: "#080512",
      pixelLiquidBaseColor: "#5C2CA2",
      pixelLiquidAccentColor: "#C562FF",
      pixelLiquidHighlightColor: "#F2D6FF",
      pixelLiquidPixelSize: 14,
      pixelLiquidDetail: "high",
      pixelLiquidMotionSpeed: 1.2,
      tileGridPaletteMode: "custom",
      tileGridPrimaryColor: "#112233",
      tileGridColorOne: "#AABBCC",
      tileGridColorTwo: "#223344",
      tileGridColorThree: "#445566",
      tileGridColorFour: "#667788",
      tileGridColorFive: "#8899AA",
      tileGridTileSize: 64,
      tileGridJointSize: 6,
      tileGridChangeFrequency: 2.5,
      tileGridActivePercent: 32,
      tileGridOpacity: 0.93,
      hexGridPrimaryColor: "#223344",
      hexGridHarmony: "triad",
      hexGridHexSize: 72,
      hexGridJointSize: 5,
      hexGridChangeFrequency: 3.5,
      hexGridActivePercent: 28,
      hexGridOpacity: 0.82,
    }, [])

    assert.equal(settings.primaryFontColor, DEFAULT_CHIMER_SETTINGS.primaryFontColor)
    assert.equal(settings.secondaryFontColor, DEFAULT_CHIMER_SETTINGS.secondaryFontColor)
    assert.equal(settings.clockModeFontColor, DEFAULT_CHIMER_SETTINGS.clockModeFontColor)
    assert.equal(settings.movingBackgroundMainColor, DEFAULT_CHIMER_SETTINGS.movingBackgroundMainColor)
    assert.equal(settings.movingBackgroundOrbColor, DEFAULT_CHIMER_SETTINGS.movingBackgroundOrbColor)
    assert.equal(settings.movingBackgroundEnabled, false)
    assert.equal(settings.backgroundId, DEFAULT_CHIMER_SETTINGS.backgroundId)
    assert.equal(settings.sparklesParticleColor, DEFAULT_CHIMER_SETTINGS.sparklesParticleColor)
    assert.equal(settings.sparklesParticleDensity, DEFAULT_CHIMER_SETTINGS.sparklesParticleDensity)
    assert.equal(settings.sparklesSpeed, DEFAULT_CHIMER_SETTINGS.sparklesSpeed)
    assert.equal(settings.gradientAnimationFirstColor, DEFAULT_CHIMER_SETTINGS.gradientAnimationFirstColor)
    assert.equal(settings.gradientAnimationSpeed, DEFAULT_CHIMER_SETTINGS.gradientAnimationSpeed)
    assert.equal(settings.animateUiGradientPrimaryColor, DEFAULT_CHIMER_SETTINGS.animateUiGradientPrimaryColor)
    assert.equal(settings.animateUiGradientHarmony, DEFAULT_CHIMER_SETTINGS.animateUiGradientHarmony)
    assert.equal(settings.animateUiGradientOpacity, DEFAULT_CHIMER_SETTINGS.animateUiGradientOpacity)
    assert.equal(settings.animateUiStarsColor, DEFAULT_CHIMER_SETTINGS.animateUiStarsColor)
    assert.equal(settings.animateUiStarsSpeed, DEFAULT_CHIMER_SETTINGS.animateUiStarsSpeed)
    assert.equal(settings.animateUiStarsDensity, DEFAULT_CHIMER_SETTINGS.animateUiStarsDensity)
    assert.equal(settings.animateUiStarsParallax, DEFAULT_CHIMER_SETTINGS.animateUiStarsParallax)
    assert.equal(settings.animateUiHoleStrokeColor, DEFAULT_CHIMER_SETTINGS.animateUiHoleStrokeColor)
    assert.equal(settings.animateUiHoleParticleColor, DEFAULT_CHIMER_SETTINGS.animateUiHoleParticleColor)
    assert.equal(settings.animateUiHoleLineCount, DEFAULT_CHIMER_SETTINGS.animateUiHoleLineCount)
    assert.equal(settings.animateUiHoleDiscCount, DEFAULT_CHIMER_SETTINGS.animateUiHoleDiscCount)
    assert.equal(settings.chamaacLightSpeedWarpSpeed, DEFAULT_CHIMER_SETTINGS.chamaacLightSpeedWarpSpeed)
    assert.equal(settings.chamaacLightSpeedParticleCount, DEFAULT_CHIMER_SETTINGS.chamaacLightSpeedParticleCount)
    assert.equal(settings.chamaacLightSpeedLightColor, DEFAULT_CHIMER_SETTINGS.chamaacLightSpeedLightColor)
    assert.equal(settings.chamaacLightSpeedIntensity, DEFAULT_CHIMER_SETTINGS.chamaacLightSpeedIntensity)
    assert.equal(settings.chamaacLightSpeedRadius, DEFAULT_CHIMER_SETTINGS.chamaacLightSpeedRadius)
    assert.equal(settings.chamaacLightSpeedCylinderLength, DEFAULT_CHIMER_SETTINGS.chamaacLightSpeedCylinderLength)
    assert.equal(settings.chamaacElectricMistColor, DEFAULT_CHIMER_SETTINGS.chamaacElectricMistColor)
    assert.equal(settings.chamaacElectricMistSpeed, DEFAULT_CHIMER_SETTINGS.chamaacElectricMistSpeed)
    assert.equal(settings.chamaacElectricMistControlVersion, DEFAULT_CHIMER_SETTINGS.chamaacElectricMistControlVersion)
    assert.equal(settings.chamaacElectricMistDetail, DEFAULT_CHIMER_SETTINGS.chamaacElectricMistDetail)
    assert.equal(settings.chamaacElectricMistDistortion, DEFAULT_CHIMER_SETTINGS.chamaacElectricMistDistortion)
    assert.equal(settings.chamaacElectricMistBrightness, DEFAULT_CHIMER_SETTINGS.chamaacElectricMistBrightness)
    assert.equal(settings.chamaacAstralFlowPaletteMode, DEFAULT_CHIMER_SETTINGS.chamaacAstralFlowPaletteMode)
    assert.equal(settings.chamaacAstralFlowPrimaryColor, DEFAULT_CHIMER_SETTINGS.chamaacAstralFlowPrimaryColor)
    assert.equal(settings.chamaacAstralFlowHarmony, DEFAULT_CHIMER_SETTINGS.chamaacAstralFlowHarmony)
    assert.equal(settings.chamaacAstralFlowColorOne, DEFAULT_CHIMER_SETTINGS.chamaacAstralFlowColorOne)
    assert.equal(settings.chamaacAstralFlowColorTwo, DEFAULT_CHIMER_SETTINGS.chamaacAstralFlowColorTwo)
    assert.equal(settings.chamaacAstralFlowColorThree, DEFAULT_CHIMER_SETTINGS.chamaacAstralFlowColorThree)
    assert.equal(settings.chamaacAstralFlowSpeed, DEFAULT_CHIMER_SETTINGS.chamaacAstralFlowSpeed)
    assert.equal(settings.chamaacAstralFlowFlowMin, DEFAULT_CHIMER_SETTINGS.chamaacAstralFlowFlowMin)
    assert.equal(settings.chamaacAstralFlowFlowMax, DEFAULT_CHIMER_SETTINGS.chamaacAstralFlowFlowMax)
    assert.equal(settings.chamaacDeepSpaceNebulaPaletteMode, DEFAULT_CHIMER_SETTINGS.chamaacDeepSpaceNebulaPaletteMode)
    assert.equal(settings.chamaacDeepSpaceNebulaPrimaryColor, DEFAULT_CHIMER_SETTINGS.chamaacDeepSpaceNebulaPrimaryColor)
    assert.equal(settings.chamaacDeepSpaceNebulaHarmony, DEFAULT_CHIMER_SETTINGS.chamaacDeepSpaceNebulaHarmony)
    assert.equal(settings.chamaacDeepSpaceNebulaColorOne, DEFAULT_CHIMER_SETTINGS.chamaacDeepSpaceNebulaColorOne)
    assert.equal(settings.chamaacDeepSpaceNebulaColorTwo, DEFAULT_CHIMER_SETTINGS.chamaacDeepSpaceNebulaColorTwo)
    assert.equal(settings.chamaacDeepSpaceNebulaColorThree, DEFAULT_CHIMER_SETTINGS.chamaacDeepSpaceNebulaColorThree)
    assert.equal(settings.chamaacDeepSpaceNebulaSpeed, DEFAULT_CHIMER_SETTINGS.chamaacDeepSpaceNebulaSpeed)
    assert.equal(settings.chamaacGridBloomColor, DEFAULT_CHIMER_SETTINGS.chamaacGridBloomColor)
    assert.equal(settings.chamaacGridBloomSpeed, DEFAULT_CHIMER_SETTINGS.chamaacGridBloomSpeed)
    assert.equal(settings.chamaacGridBloomGridScale, DEFAULT_CHIMER_SETTINGS.chamaacGridBloomGridScale)
    assert.equal(settings.chamaacGridBloomRotationSpeed, DEFAULT_CHIMER_SETTINGS.chamaacGridBloomRotationSpeed)
    assert.equal(settings.chamaacGridBloomFadeFalloff, DEFAULT_CHIMER_SETTINGS.chamaacGridBloomFadeFalloff)
    assert.equal(settings.chamaacGridBloomDistortionAmount, DEFAULT_CHIMER_SETTINGS.chamaacGridBloomDistortionAmount)
    assert.equal(settings.chamaacGridBloomFlowSpeedX, DEFAULT_CHIMER_SETTINGS.chamaacGridBloomFlowSpeedX)
    assert.equal(settings.chamaacGridBloomFlowSpeedY, DEFAULT_CHIMER_SETTINGS.chamaacGridBloomFlowSpeedY)
    assert.equal(settings.chamaacLiquidChromePaletteMode, DEFAULT_CHIMER_SETTINGS.chamaacLiquidChromePaletteMode)
    assert.equal(settings.chamaacLiquidChromePrimaryColor, DEFAULT_CHIMER_SETTINGS.chamaacLiquidChromePrimaryColor)
    assert.equal(settings.chamaacLiquidChromeHarmony, DEFAULT_CHIMER_SETTINGS.chamaacLiquidChromeHarmony)
    assert.equal(settings.chamaacLiquidChromeColorOne, DEFAULT_CHIMER_SETTINGS.chamaacLiquidChromeColorOne)
    assert.equal(settings.chamaacLiquidChromeColorTwo, DEFAULT_CHIMER_SETTINGS.chamaacLiquidChromeColorTwo)
    assert.equal(settings.chamaacLiquidChromeFlowSpeed, DEFAULT_CHIMER_SETTINGS.chamaacLiquidChromeFlowSpeed)
    assert.equal(settings.chamaacLiquidChromeTimeScale, DEFAULT_CHIMER_SETTINGS.chamaacLiquidChromeTimeScale)
    assert.equal(settings.chamaacWavesPaletteMode, DEFAULT_CHIMER_SETTINGS.chamaacWavesPaletteMode)
    assert.equal(settings.chamaacWavesPrimaryColor, DEFAULT_CHIMER_SETTINGS.chamaacWavesPrimaryColor)
    assert.equal(settings.chamaacWavesHarmony, DEFAULT_CHIMER_SETTINGS.chamaacWavesHarmony)
    assert.equal(settings.chamaacWavesBackgroundColor, DEFAULT_CHIMER_SETTINGS.chamaacWavesBackgroundColor)
    assert.equal(settings.chamaacWavesColorOne, DEFAULT_CHIMER_SETTINGS.chamaacWavesColorOne)
    assert.equal(settings.chamaacWavesColorTwo, DEFAULT_CHIMER_SETTINGS.chamaacWavesColorTwo)
    assert.equal(settings.chamaacWavesColorThree, DEFAULT_CHIMER_SETTINGS.chamaacWavesColorThree)
    assert.equal(settings.chamaacWavesSpeedX, DEFAULT_CHIMER_SETTINGS.chamaacWavesSpeedX)
    assert.equal(settings.chamaacWavesSpeedY, DEFAULT_CHIMER_SETTINGS.chamaacWavesSpeedY)
    assert.equal(settings.chamaacWavesAmplitude, DEFAULT_CHIMER_SETTINGS.chamaacWavesAmplitude)
    assert.equal(settings.chamaacSynthesisPaletteMode, DEFAULT_CHIMER_SETTINGS.chamaacSynthesisPaletteMode)
    assert.equal(settings.chamaacSynthesisPrimaryColor, DEFAULT_CHIMER_SETTINGS.chamaacSynthesisPrimaryColor)
    assert.equal(settings.chamaacSynthesisHarmony, DEFAULT_CHIMER_SETTINGS.chamaacSynthesisHarmony)
    assert.equal(settings.chamaacSynthesisColorOne, DEFAULT_CHIMER_SETTINGS.chamaacSynthesisColorOne)
    assert.equal(settings.chamaacSynthesisColorTwo, DEFAULT_CHIMER_SETTINGS.chamaacSynthesisColorTwo)
    assert.equal(settings.chamaacSynthesisColorThree, DEFAULT_CHIMER_SETTINGS.chamaacSynthesisColorThree)
    assert.equal(settings.chamaacSynthesisSpeed, DEFAULT_CHIMER_SETTINGS.chamaacSynthesisSpeed)
    assert.equal(settings.chamaacSynthesisComplexity, DEFAULT_CHIMER_SETTINGS.chamaacSynthesisComplexity)
    assert.equal(settings.chamaacSynthesisScale, DEFAULT_CHIMER_SETTINGS.chamaacSynthesisScale)
    assert.equal(settings.chamaacSynthesisDistortion, DEFAULT_CHIMER_SETTINGS.chamaacSynthesisDistortion)
    assert.equal(settings.chamaacSynthesisGlowIntensity, DEFAULT_CHIMER_SETTINGS.chamaacSynthesisGlowIntensity)
    assert.equal(settings.chamaacSynthesisFlowFrequency, DEFAULT_CHIMER_SETTINGS.chamaacSynthesisFlowFrequency)
    assert.equal(settings.backgroundLinesDuration, DEFAULT_CHIMER_SETTINGS.backgroundLinesDuration)
    assert.equal(settings.wavyBackgroundFill, DEFAULT_CHIMER_SETTINGS.wavyBackgroundFill)
    assert.equal(settings.wavyColorOne, DEFAULT_CHIMER_SETTINGS.wavyColorOne)
    assert.equal(settings.wavyWaveWidth, DEFAULT_CHIMER_SETTINGS.wavyWaveWidth)
    assert.equal(settings.wavySpeed, DEFAULT_CHIMER_SETTINGS.wavySpeed)
    assert.equal(settings.wavyWaveOpacity, DEFAULT_CHIMER_SETTINGS.wavyWaveOpacity)
    assert.equal(settings.shootingStarsStarColor, DEFAULT_CHIMER_SETTINGS.shootingStarsStarColor)
    assert.equal(settings.shootingStarsTrailColor, DEFAULT_CHIMER_SETTINGS.shootingStarsTrailColor)
    assert.equal(settings.shootingStarsShootingStarColor, DEFAULT_CHIMER_SETTINGS.shootingStarsShootingStarColor)
    assert.equal(settings.shootingStarsDensity, DEFAULT_CHIMER_SETTINGS.shootingStarsDensity)
    assert.equal(settings.shootingStarsTwinkle, DEFAULT_CHIMER_SETTINGS.shootingStarsTwinkle)
    assert.equal(settings.shootingStarsTwinkleSpeed, DEFAULT_CHIMER_SETTINGS.shootingStarsTwinkleSpeed)
    assert.equal(settings.shootingStarsShootingSpeed, DEFAULT_CHIMER_SETTINGS.shootingStarsShootingSpeed)
    assert.equal(settings.shootingStarsFrequency, DEFAULT_CHIMER_SETTINGS.shootingStarsFrequency)
    assert.equal(settings.canvasRevealDotsBackgroundColor, DEFAULT_CHIMER_SETTINGS.canvasRevealDotsBackgroundColor)
    assert.equal(settings.canvasRevealDotsDotColor, DEFAULT_CHIMER_SETTINGS.canvasRevealDotsDotColor)
    assert.equal(settings.canvasRevealDotsAccentColor, DEFAULT_CHIMER_SETTINGS.canvasRevealDotsAccentColor)
    assert.equal(settings.canvasRevealDotsDotSize, DEFAULT_CHIMER_SETTINGS.canvasRevealDotsDotSize)
    assert.equal(settings.canvasRevealDotsDotSpacing, DEFAULT_CHIMER_SETTINGS.canvasRevealDotsDotSpacing)
    assert.equal(settings.canvasRevealDotsOpacity, DEFAULT_CHIMER_SETTINGS.canvasRevealDotsOpacity)
    assert.equal(settings.canvasRevealDotsAnimationSpeed, DEFAULT_CHIMER_SETTINGS.canvasRevealDotsAnimationSpeed)
    assert.equal(settings.canvasRevealDotsShowGradient, DEFAULT_CHIMER_SETTINGS.canvasRevealDotsShowGradient)
    assert.equal(settings.spotlightColor, DEFAULT_CHIMER_SETTINGS.spotlightColor)
    assert.equal(settings.spotlightOpacity, DEFAULT_CHIMER_SETTINGS.spotlightOpacity)
    assert.equal(settings.spotlightWidth, DEFAULT_CHIMER_SETTINGS.spotlightWidth)
    assert.equal(settings.spotlightHeight, DEFAULT_CHIMER_SETTINGS.spotlightHeight)
    assert.equal(settings.spotlightSmallWidth, DEFAULT_CHIMER_SETTINGS.spotlightSmallWidth)
    assert.equal(settings.spotlightTranslateY, DEFAULT_CHIMER_SETTINGS.spotlightTranslateY)
    assert.equal(settings.spotlightDuration, DEFAULT_CHIMER_SETTINGS.spotlightDuration)
    assert.equal(settings.spotlightXOffset, DEFAULT_CHIMER_SETTINGS.spotlightXOffset)
    assert.equal(settings.lampBackgroundColor, DEFAULT_CHIMER_SETTINGS.lampBackgroundColor)
    assert.equal(settings.lampColor, DEFAULT_CHIMER_SETTINGS.lampColor)
    assert.equal(settings.lampGlowOpacity, DEFAULT_CHIMER_SETTINGS.lampGlowOpacity)
    assert.equal(settings.lampBeamWidth, DEFAULT_CHIMER_SETTINGS.lampBeamWidth)
    assert.equal(settings.lampGlowWidth, DEFAULT_CHIMER_SETTINGS.lampGlowWidth)
    assert.equal(settings.lampVerticalOffset, DEFAULT_CHIMER_SETTINGS.lampVerticalOffset)
    assert.equal(settings.lampPulseSpeed, DEFAULT_CHIMER_SETTINGS.lampPulseSpeed)
    assert.equal(settings.vortexBackgroundColor, DEFAULT_CHIMER_SETTINGS.vortexBackgroundColor)
    assert.equal(settings.vortexBaseHue, DEFAULT_CHIMER_SETTINGS.vortexBaseHue)
    assert.equal(settings.vortexParticleCount, DEFAULT_CHIMER_SETTINGS.vortexParticleCount)
    assert.equal(settings.vortexRangeY, DEFAULT_CHIMER_SETTINGS.vortexRangeY)
    assert.equal(settings.vortexBaseSpeed, DEFAULT_CHIMER_SETTINGS.vortexBaseSpeed)
    assert.equal(settings.vortexRangeSpeed, DEFAULT_CHIMER_SETTINGS.vortexRangeSpeed)
    assert.equal(settings.vortexBaseRadius, DEFAULT_CHIMER_SETTINGS.vortexBaseRadius)
    assert.equal(settings.vortexRangeRadius, DEFAULT_CHIMER_SETTINGS.vortexRangeRadius)
    assert.equal(settings.auroraBarsBackgroundColor, DEFAULT_CHIMER_SETTINGS.auroraBarsBackgroundColor)
    assert.equal(settings.auroraBarsPaletteMode, DEFAULT_CHIMER_SETTINGS.auroraBarsPaletteMode)
    assert.equal(settings.auroraBarsPrimaryColor, DEFAULT_CHIMER_SETTINGS.auroraBarsPrimaryColor)
    assert.equal(settings.auroraBarsColorOne, DEFAULT_CHIMER_SETTINGS.auroraBarsColorOne)
    assert.equal(settings.auroraBarsColorTwo, DEFAULT_CHIMER_SETTINGS.auroraBarsColorTwo)
    assert.equal(settings.auroraBarsColorThree, DEFAULT_CHIMER_SETTINGS.auroraBarsColorThree)
    assert.equal(settings.auroraBarsColorFour, DEFAULT_CHIMER_SETTINGS.auroraBarsColorFour)
    assert.equal(settings.auroraBarsColorFive, DEFAULT_CHIMER_SETTINGS.auroraBarsColorFive)
    assert.equal(settings.auroraBarsBarCount, DEFAULT_CHIMER_SETTINGS.auroraBarsBarCount)
    assert.equal(settings.auroraBarsSpeed, DEFAULT_CHIMER_SETTINGS.auroraBarsSpeed)
    assert.equal(settings.auroraBarsBlur, DEFAULT_CHIMER_SETTINGS.auroraBarsBlur)
    assert.equal(settings.auroraBarsGap, DEFAULT_CHIMER_SETTINGS.auroraBarsGap)
    assert.equal(settings.auroraBarsMaxHeightRatio, DEFAULT_CHIMER_SETTINGS.auroraBarsMaxHeightRatio)
    assert.equal(settings.auroraBarsMinHeightRatio, DEFAULT_CHIMER_SETTINGS.auroraBarsMinHeightRatio)
    assert.equal(settings.pixelLiquidBackgroundColor, DEFAULT_CHIMER_SETTINGS.pixelLiquidBackgroundColor)
    assert.equal(settings.pixelLiquidBaseColor, DEFAULT_CHIMER_SETTINGS.pixelLiquidBaseColor)
    assert.equal(settings.pixelLiquidAccentColor, DEFAULT_CHIMER_SETTINGS.pixelLiquidAccentColor)
    assert.equal(settings.pixelLiquidHighlightColor, DEFAULT_CHIMER_SETTINGS.pixelLiquidHighlightColor)
    assert.equal(settings.pixelLiquidPixelSize, DEFAULT_CHIMER_SETTINGS.pixelLiquidPixelSize)
    assert.equal(settings.pixelLiquidDetail, DEFAULT_CHIMER_SETTINGS.pixelLiquidDetail)
    assert.equal(settings.pixelLiquidMotionSpeed, DEFAULT_CHIMER_SETTINGS.pixelLiquidMotionSpeed)
    assert.equal(settings.tileGridPaletteMode, DEFAULT_CHIMER_SETTINGS.tileGridPaletteMode)
    assert.equal(settings.tileGridPrimaryColor, DEFAULT_CHIMER_SETTINGS.tileGridPrimaryColor)
    assert.equal(settings.tileGridColorOne, DEFAULT_CHIMER_SETTINGS.tileGridColorOne)
    assert.equal(settings.tileGridColorTwo, DEFAULT_CHIMER_SETTINGS.tileGridColorTwo)
    assert.equal(settings.tileGridColorThree, DEFAULT_CHIMER_SETTINGS.tileGridColorThree)
    assert.equal(settings.tileGridColorFour, DEFAULT_CHIMER_SETTINGS.tileGridColorFour)
    assert.equal(settings.tileGridColorFive, DEFAULT_CHIMER_SETTINGS.tileGridColorFive)
    assert.equal(settings.tileGridTileSize, DEFAULT_CHIMER_SETTINGS.tileGridTileSize)
    assert.equal(settings.tileGridJointSize, DEFAULT_CHIMER_SETTINGS.tileGridJointSize)
    assert.equal(settings.tileGridChangeFrequency, DEFAULT_CHIMER_SETTINGS.tileGridChangeFrequency)
    assert.equal(settings.tileGridActivePercent, DEFAULT_CHIMER_SETTINGS.tileGridActivePercent)
    assert.equal(settings.tileGridOpacity, DEFAULT_CHIMER_SETTINGS.tileGridOpacity)
    assert.equal(settings.hexGridPrimaryColor, DEFAULT_CHIMER_SETTINGS.hexGridPrimaryColor)
    assert.equal(settings.hexGridHarmony, DEFAULT_CHIMER_SETTINGS.hexGridHarmony)
    assert.equal(settings.hexGridHexSize, DEFAULT_CHIMER_SETTINGS.hexGridHexSize)
    assert.equal(settings.hexGridJointSize, DEFAULT_CHIMER_SETTINGS.hexGridJointSize)
    assert.equal(settings.hexGridChangeFrequency, DEFAULT_CHIMER_SETTINGS.hexGridChangeFrequency)
    assert.equal(settings.hexGridActivePercent, DEFAULT_CHIMER_SETTINGS.hexGridActivePercent)
    assert.equal(settings.hexGridOpacity, DEFAULT_CHIMER_SETTINGS.hexGridOpacity)
  })

  it("preserves premium backgrounds and custom colors for users with both features", () => {
    const settings = sanitizeChimerSettingsForEntitlements({
      primaryFontColor: "#000000",
      secondaryFontColor: "#123456",
      clockModeFontColor: "#654321",
      movingBackgroundMainColor: "#ABCDEF",
      movingBackgroundOrbColor: "#FEDCBA",
      backgroundId: "aceternity-sparkles",
      sparklesParticleColor: "#ABC123",
      sparklesParticleDensity: 180,
      sparklesSpeed: 6,
      gradientAnimationFirstColor: "#112233",
      gradientAnimationSpeed: 2,
      animateUiGradientPrimaryColor: "#102030",
      animateUiGradientHarmony: "split-complementary",
      animateUiGradientOpacity: 0.42,
      animateUiStarsColor: "#EAF6FF",
      animateUiStarsSpeed: 72,
      animateUiStarsDensity: 1.2,
      animateUiStarsParallax: 0.08,
      animateUiHoleStrokeColor: "#112233",
      animateUiHoleParticleColor: "#EAF6FF",
      animateUiHoleLineCount: 72,
      animateUiHoleDiscCount: 64,
      chamaacLightSpeedWarpSpeed: 3.5,
      chamaacLightSpeedWarpSpeedVersion: 2,
      chamaacLightSpeedParticleCount: 180,
      chamaacLightSpeedLightColor: "#33B2FF",
      chamaacLightSpeedIntensity: 4.5,
      chamaacLightSpeedRadius: 42,
      chamaacLightSpeedCylinderLength: 220,
      chamaacElectricMistColor: "#33B2FF",
      chamaacElectricMistSpeed: 250,
      chamaacElectricMistControlVersion: 2,
      chamaacElectricMistDetail: 2.4,
      chamaacElectricMistDistortion: 5.5,
      chamaacElectricMistBrightness: 80,
      chamaacAstralFlowPaletteMode: "harmony",
      chamaacAstralFlowPrimaryColor: "#33B2FF",
      chamaacAstralFlowHarmony: "split-complementary",
      chamaacAstralFlowColorOne: "#112233",
      chamaacAstralFlowColorTwo: "#445566",
      chamaacAstralFlowColorThree: "#778899",
      chamaacAstralFlowSpeed: 2.1,
      chamaacAstralFlowFlowMin: 4.2,
      chamaacAstralFlowFlowMax: 8.4,
      chamaacDeepSpaceNebulaPaletteMode: "harmony",
      chamaacDeepSpaceNebulaPrimaryColor: "#763B65",
      chamaacDeepSpaceNebulaHarmony: "complementary",
      chamaacDeepSpaceNebulaColorOne: "#5EFFF4",
      chamaacDeepSpaceNebulaColorTwo: "#763B65",
      chamaacDeepSpaceNebulaColorThree: "#1A0B2E",
      chamaacDeepSpaceNebulaSpeed: 3.6,
      chamaacGridBloomColor: "#E040FB",
      chamaacGridBloomSpeed: 2.4,
      chamaacGridBloomGridScale: 18,
      chamaacGridBloomRotationSpeed: 0.8,
      chamaacGridBloomFadeFalloff: 14,
      chamaacGridBloomDistortionAmount: 0.18,
      chamaacGridBloomFlowSpeedX: -0.6,
      chamaacGridBloomFlowSpeedY: 0.5,
      chamaacLiquidChromePaletteMode: "harmony",
      chamaacLiquidChromePrimaryColor: "#C0C0C0",
      chamaacLiquidChromeHarmony: "monochromatic",
      chamaacLiquidChromeColorOne: "#C0C0C0",
      chamaacLiquidChromeColorTwo: "#4A4A4A",
      chamaacLiquidChromeFlowSpeed: 1.4,
      chamaacLiquidChromeTimeScale: 0.4,
      chamaacWavesPaletteMode: "harmony",
      chamaacWavesPrimaryColor: "#071697",
      chamaacWavesHarmony: "triad",
      chamaacWavesBackgroundColor: "#000000",
      chamaacWavesColorOne: "#071697",
      chamaacWavesColorTwo: "#00D4FF",
      chamaacWavesColorThree: "#000000",
      chamaacWavesSpeedX: 0.08,
      chamaacWavesSpeedY: 0.04,
      chamaacWavesAmplitude: 48,
      chamaacSynthesisPaletteMode: "harmony",
      chamaacSynthesisPrimaryColor: "#33B2FF",
      chamaacSynthesisHarmony: "split-complementary",
      chamaacSynthesisColorOne: "#112233",
      chamaacSynthesisColorTwo: "#445566",
      chamaacSynthesisColorThree: "#778899",
      chamaacSynthesisSpeed: 1.8,
      chamaacSynthesisComplexity: 16,
      chamaacSynthesisScale: 2.4,
      chamaacSynthesisDistortion: 1.4,
      chamaacSynthesisGlowIntensity: 1.6,
      chamaacSynthesisFlowFrequency: 7.5,
      backgroundLinesDuration: 16,
      wavyBackgroundFill: "#111111",
      wavyColorOne: "#ABC123",
      wavyWaveWidth: 80,
      wavySpeed: "slow",
      wavyWaveOpacity: 0.8,
      shootingStarsStarColor: "#101010",
      shootingStarsTrailColor: "#202020",
      shootingStarsShootingStarColor: "#303030",
      shootingStarsDensity: 0.00028,
      shootingStarsTwinkle: false,
      shootingStarsTwinkleSpeed: 2,
      shootingStarsShootingSpeed: 1.8,
      shootingStarsFrequency: 1.6,
      canvasRevealDotsBackgroundColor: "#040404",
      canvasRevealDotsDotColor: "#00FFCC",
      canvasRevealDotsAccentColor: "#CC7722",
      canvasRevealDotsDotSize: 3.2,
      canvasRevealDotsDotSpacing: 14,
      canvasRevealDotsOpacity: 0.6,
      canvasRevealDotsAnimationSpeed: 0.8,
      canvasRevealDotsShowGradient: false,
      spotlightColor: "#AABBCC",
      spotlightOpacity: 1.4,
      spotlightWidth: 820,
      spotlightHeight: 1700,
      spotlightSmallWidth: 360,
      spotlightTranslateY: -520,
      spotlightDuration: 12,
      spotlightXOffset: 180,
      lampBackgroundColor: "#050505",
      lampColor: "#22D3EE",
      lampGlowOpacity: 0.9,
      lampBeamWidth: 780,
      lampGlowWidth: 720,
      lampVerticalOffset: -200,
      lampPulseSpeed: 14,
      vortexBackgroundColor: "#040404",
      vortexBaseHue: 280,
      vortexParticleCount: 620,
      vortexRangeY: 200,
      vortexBaseSpeed: 0.5,
      vortexRangeSpeed: 1.8,
      vortexBaseRadius: 1.7,
      vortexRangeRadius: 3.2,
      auroraBarsBackgroundColor: "#010203",
      auroraBarsPaletteMode: "custom",
      auroraBarsPrimaryColor: "#334455",
      auroraBarsColorOne: "#AABBCC",
      auroraBarsColorTwo: "#223344",
      auroraBarsColorThree: "#445566",
      auroraBarsColorFour: "#667788",
      auroraBarsColorFive: "#8899AA",
      auroraBarsBarCount: 64,
      auroraBarsSpeed: 1.5,
      auroraBarsBlur: 9,
      auroraBarsGap: 7,
      auroraBarsMaxHeightRatio: 0.84,
      auroraBarsMinHeightRatio: 0.2,
      pixelLiquidBackgroundColor: "#080512",
      pixelLiquidBaseColor: "#5C2CA2",
      pixelLiquidAccentColor: "#C562FF",
      pixelLiquidHighlightColor: "#F2D6FF",
      pixelLiquidPixelSize: 14,
      pixelLiquidDetail: "high",
      pixelLiquidMotionSpeed: 1.2,
      tileGridPaletteMode: "custom",
      tileGridPrimaryColor: "#112233",
      tileGridColorOne: "#AABBCC",
      tileGridColorTwo: "#223344",
      tileGridColorThree: "#445566",
      tileGridColorFour: "#667788",
      tileGridColorFive: "#8899AA",
      tileGridTileSize: 64,
      tileGridJointSize: 6,
      tileGridChangeFrequency: 2.5,
      tileGridActivePercent: 32,
      tileGridOpacity: 0.93,
      hexGridPrimaryColor: "#223344",
      hexGridHarmony: "triad",
      hexGridHexSize: 72,
      hexGridJointSize: 5,
      hexGridChangeFrequency: 3.5,
      hexGridActivePercent: 28,
      hexGridOpacity: 0.82,
    }, [FEATURE_KEYS.chimerCustomColors, FEATURE_KEYS.premiumBackgrounds])

    assert.equal(settings.primaryFontColor, "#000000")
    assert.equal(settings.secondaryFontColor, "#123456")
    assert.equal(settings.clockModeFontColor, "#654321")
    assert.equal(settings.movingBackgroundMainColor, "#ABCDEF")
    assert.equal(settings.movingBackgroundOrbColor, "#FEDCBA")
    assert.equal(settings.backgroundId, "aceternity-sparkles")
    assert.equal(settings.sparklesParticleColor, "#ABC123")
    assert.equal(settings.sparklesParticleDensity, 180)
    assert.equal(settings.sparklesSpeed, 6)
    assert.equal(settings.gradientAnimationFirstColor, "#112233")
    assert.equal(settings.gradientAnimationSpeed, 2)
    assert.equal(settings.animateUiGradientPrimaryColor, "#102030")
    assert.equal(settings.animateUiGradientHarmony, "split-complementary")
    assert.equal(settings.animateUiGradientOpacity, 0.42)
    assert.equal(settings.animateUiStarsColor, "#EAF6FF")
    assert.equal(settings.animateUiStarsSpeed, 72)
    assert.equal(settings.animateUiStarsDensity, 1.2)
    assert.equal(settings.animateUiStarsParallax, 0.08)
    assert.equal(settings.animateUiHoleStrokeColor, "#112233")
    assert.equal(settings.animateUiHoleParticleColor, "#EAF6FF")
    assert.equal(settings.animateUiHoleLineCount, 72)
    assert.equal(settings.animateUiHoleDiscCount, 64)
    assert.equal(settings.chamaacLightSpeedWarpSpeed, 3.5)
    assert.equal(settings.chamaacLightSpeedParticleCount, 180)
    assert.equal(settings.chamaacLightSpeedLightColor, "#33B2FF")
    assert.equal(settings.chamaacLightSpeedIntensity, 4.5)
    assert.equal(settings.chamaacLightSpeedRadius, 42)
    assert.equal(settings.chamaacLightSpeedCylinderLength, 220)
    assert.equal(settings.chamaacElectricMistColor, "#33B2FF")
    assert.equal(settings.chamaacElectricMistSpeed, 250)
    assert.equal(settings.chamaacElectricMistControlVersion, 2)
    assert.equal(settings.chamaacElectricMistDetail, 2.4)
    assert.equal(settings.chamaacElectricMistDistortion, 5.5)
    assert.equal(settings.chamaacElectricMistBrightness, 80)
    assert.equal(settings.chamaacAstralFlowPaletteMode, "harmony")
    assert.equal(settings.chamaacAstralFlowPrimaryColor, "#33B2FF")
    assert.equal(settings.chamaacAstralFlowHarmony, "split-complementary")
    assert.equal(settings.chamaacAstralFlowColorOne, "#112233")
    assert.equal(settings.chamaacAstralFlowColorTwo, "#445566")
    assert.equal(settings.chamaacAstralFlowColorThree, "#778899")
    assert.equal(settings.chamaacAstralFlowSpeed, 2.1)
    assert.equal(settings.chamaacAstralFlowFlowMin, 4.2)
    assert.equal(settings.chamaacAstralFlowFlowMax, 8.4)
    assert.equal(settings.chamaacDeepSpaceNebulaPaletteMode, "harmony")
    assert.equal(settings.chamaacDeepSpaceNebulaPrimaryColor, "#763B65")
    assert.equal(settings.chamaacDeepSpaceNebulaHarmony, "complementary")
    assert.equal(settings.chamaacDeepSpaceNebulaColorOne, "#5EFFF4")
    assert.equal(settings.chamaacDeepSpaceNebulaColorTwo, "#763B65")
    assert.equal(settings.chamaacDeepSpaceNebulaColorThree, "#1A0B2E")
    assert.equal(settings.chamaacDeepSpaceNebulaSpeed, 3.6)
    assert.equal(settings.chamaacGridBloomColor, "#E040FB")
    assert.equal(settings.chamaacGridBloomSpeed, 2.4)
    assert.equal(settings.chamaacGridBloomGridScale, 18)
    assert.equal(settings.chamaacGridBloomRotationSpeed, 0.8)
    assert.equal(settings.chamaacGridBloomFadeFalloff, 14)
    assert.equal(settings.chamaacGridBloomDistortionAmount, 0.18)
    assert.equal(settings.chamaacGridBloomFlowSpeedX, -0.6)
    assert.equal(settings.chamaacGridBloomFlowSpeedY, 0.5)
    assert.equal(settings.chamaacLiquidChromePaletteMode, "harmony")
    assert.equal(settings.chamaacLiquidChromePrimaryColor, "#C0C0C0")
    assert.equal(settings.chamaacLiquidChromeHarmony, "monochromatic")
    assert.equal(settings.chamaacLiquidChromeColorOne, "#C0C0C0")
    assert.equal(settings.chamaacLiquidChromeColorTwo, "#4A4A4A")
    assert.equal(settings.chamaacLiquidChromeFlowSpeed, 1.4)
    assert.equal(settings.chamaacLiquidChromeTimeScale, 0.4)
    assert.equal(settings.chamaacWavesPaletteMode, "harmony")
    assert.equal(settings.chamaacWavesPrimaryColor, "#071697")
    assert.equal(settings.chamaacWavesHarmony, "triad")
    assert.equal(settings.chamaacWavesBackgroundColor, "#000000")
    assert.equal(settings.chamaacWavesColorOne, "#071697")
    assert.equal(settings.chamaacWavesColorTwo, "#00D4FF")
    assert.equal(settings.chamaacWavesColorThree, "#000000")
    assert.equal(settings.chamaacWavesSpeedX, 0.08)
    assert.equal(settings.chamaacWavesSpeedY, 0.04)
    assert.equal(settings.chamaacWavesAmplitude, 48)
    assert.equal(settings.chamaacSynthesisPaletteMode, "harmony")
    assert.equal(settings.chamaacSynthesisPrimaryColor, "#33B2FF")
    assert.equal(settings.chamaacSynthesisHarmony, "split-complementary")
    assert.equal(settings.chamaacSynthesisColorOne, "#112233")
    assert.equal(settings.chamaacSynthesisColorTwo, "#445566")
    assert.equal(settings.chamaacSynthesisColorThree, "#778899")
    assert.equal(settings.chamaacSynthesisSpeed, 1.8)
    assert.equal(settings.chamaacSynthesisComplexity, 16)
    assert.equal(settings.chamaacSynthesisScale, 2.4)
    assert.equal(settings.chamaacSynthesisDistortion, 1.4)
    assert.equal(settings.chamaacSynthesisGlowIntensity, 1.6)
    assert.equal(settings.chamaacSynthesisFlowFrequency, 7.5)
    assert.equal(settings.backgroundLinesDuration, 16)
    assert.equal(settings.wavyBackgroundFill, "#111111")
    assert.equal(settings.wavyColorOne, "#ABC123")
    assert.equal(settings.wavyWaveWidth, 80)
    assert.equal(settings.wavySpeed, "slow")
    assert.equal(settings.wavyWaveOpacity, 0.8)
    assert.equal(settings.shootingStarsStarColor, "#101010")
    assert.equal(settings.shootingStarsTrailColor, "#202020")
    assert.equal(settings.shootingStarsShootingStarColor, "#303030")
    assert.equal(settings.shootingStarsDensity, 0.00028)
    assert.equal(settings.shootingStarsTwinkle, false)
    assert.equal(settings.shootingStarsTwinkleSpeed, 2)
    assert.equal(settings.shootingStarsShootingSpeed, 1.8)
    assert.equal(settings.shootingStarsFrequency, 1.6)
    assert.equal(settings.canvasRevealDotsBackgroundColor, "#040404")
    assert.equal(settings.canvasRevealDotsDotColor, "#00FFCC")
    assert.equal(settings.canvasRevealDotsAccentColor, "#CC7722")
    assert.equal(settings.canvasRevealDotsDotSize, 3.2)
    assert.equal(settings.canvasRevealDotsDotSpacing, 14)
    assert.equal(settings.canvasRevealDotsOpacity, 0.6)
    assert.equal(settings.canvasRevealDotsAnimationSpeed, 0.8)
    assert.equal(settings.canvasRevealDotsShowGradient, false)
    assert.equal(settings.spotlightColor, "#AABBCC")
    assert.equal(settings.spotlightOpacity, 1.4)
    assert.equal(settings.spotlightWidth, 820)
    assert.equal(settings.spotlightHeight, 1700)
    assert.equal(settings.spotlightSmallWidth, 360)
    assert.equal(settings.spotlightTranslateY, -520)
    assert.equal(settings.spotlightDuration, 12)
    assert.equal(settings.spotlightXOffset, 180)
    assert.equal(settings.lampBackgroundColor, "#050505")
    assert.equal(settings.lampColor, "#22D3EE")
    assert.equal(settings.lampGlowOpacity, 0.9)
    assert.equal(settings.lampBeamWidth, 780)
    assert.equal(settings.lampGlowWidth, 720)
    assert.equal(settings.lampVerticalOffset, -200)
    assert.equal(settings.lampPulseSpeed, 14)
    assert.equal(settings.vortexBackgroundColor, "#040404")
    assert.equal(settings.vortexBaseHue, 280)
    assert.equal(settings.vortexParticleCount, 620)
    assert.equal(settings.vortexRangeY, 200)
    assert.equal(settings.vortexBaseSpeed, 0.5)
    assert.equal(settings.vortexRangeSpeed, 1.8)
    assert.equal(settings.vortexBaseRadius, 1.7)
    assert.equal(settings.vortexRangeRadius, 3.2)
    assert.equal(settings.auroraBarsBackgroundColor, "#010203")
    assert.equal(settings.auroraBarsPaletteMode, "custom")
    assert.equal(settings.auroraBarsPrimaryColor, "#334455")
    assert.equal(settings.auroraBarsColorOne, "#AABBCC")
    assert.equal(settings.auroraBarsColorTwo, "#223344")
    assert.equal(settings.auroraBarsColorThree, "#445566")
    assert.equal(settings.auroraBarsColorFour, "#667788")
    assert.equal(settings.auroraBarsColorFive, "#8899AA")
    assert.equal(settings.auroraBarsBarCount, 64)
    assert.equal(settings.auroraBarsSpeed, 1.5)
    assert.equal(settings.auroraBarsBlur, 9)
    assert.equal(settings.auroraBarsGap, 7)
    assert.equal(settings.auroraBarsMaxHeightRatio, 0.84)
    assert.equal(settings.auroraBarsMinHeightRatio, 0.2)
    assert.equal(settings.pixelLiquidBackgroundColor, "#080512")
    assert.equal(settings.pixelLiquidBaseColor, "#5C2CA2")
    assert.equal(settings.pixelLiquidAccentColor, "#C562FF")
    assert.equal(settings.pixelLiquidHighlightColor, "#F2D6FF")
    assert.equal(settings.pixelLiquidPixelSize, 14)
    assert.equal(settings.pixelLiquidDetail, "high")
    assert.equal(settings.pixelLiquidMotionSpeed, 1.2)
    assert.equal(settings.tileGridPaletteMode, "custom")
    assert.equal(settings.tileGridPrimaryColor, "#112233")
    assert.equal(settings.tileGridColorOne, "#AABBCC")
    assert.equal(settings.tileGridColorTwo, "#223344")
    assert.equal(settings.tileGridColorThree, "#445566")
    assert.equal(settings.tileGridColorFour, "#667788")
    assert.equal(settings.tileGridColorFive, "#8899AA")
    assert.equal(settings.tileGridTileSize, 64)
    assert.equal(settings.tileGridJointSize, 6)
    assert.equal(settings.tileGridChangeFrequency, 2.5)
    assert.equal(settings.tileGridActivePercent, 32)
    assert.equal(settings.tileGridOpacity, 0.93)
    assert.equal(settings.hexGridPrimaryColor, "#223344")
    assert.equal(settings.hexGridHarmony, "triad")
    assert.equal(settings.hexGridHexSize, 72)
    assert.equal(settings.hexGridJointSize, 5)
    assert.equal(settings.hexGridChangeFrequency, 3.5)
    assert.equal(settings.hexGridActivePercent, 28)
    assert.equal(settings.hexGridOpacity, 0.82)
  })

  it("allows premium background controls without unlocking custom Chimer display colors", () => {
    const settings = sanitizeChimerSettingsForEntitlements({
      primaryFontColor: "#000000",
      backgroundId: "aceternity-gradient-animation",
      sparklesParticleColor: "#ABC123",
      sparklesParticleDensity: 180,
      gradientAnimationSecondColor: "#224466",
      gradientAnimationSize: 100,
      animateUiGradientPrimaryColor: "#102030",
      animateUiGradientHarmony: "split-complementary",
      animateUiGradientOpacity: 0.42,
      animateUiStarsColor: "#EAF6FF",
      animateUiStarsSpeed: 72,
      animateUiStarsDensity: 1.2,
      animateUiStarsParallax: 0.08,
      animateUiHoleStrokeColor: "#112233",
      animateUiHoleParticleColor: "#EAF6FF",
      animateUiHoleLineCount: 72,
      animateUiHoleDiscCount: 64,
      chamaacLightSpeedWarpSpeed: 3.5,
      chamaacLightSpeedWarpSpeedVersion: 2,
      chamaacLightSpeedParticleCount: 180,
      chamaacLightSpeedLightColor: "#33B2FF",
      chamaacLightSpeedIntensity: 4.5,
      chamaacLightSpeedRadius: 42,
      chamaacLightSpeedCylinderLength: 220,
      chamaacElectricMistColor: "#33B2FF",
      chamaacElectricMistSpeed: 250,
      chamaacElectricMistControlVersion: 2,
      chamaacElectricMistDetail: 2.4,
      chamaacElectricMistDistortion: 5.5,
      chamaacElectricMistBrightness: 80,
      chamaacAstralFlowPaletteMode: "harmony",
      chamaacAstralFlowPrimaryColor: "#33B2FF",
      chamaacAstralFlowHarmony: "split-complementary",
      chamaacAstralFlowColorOne: "#112233",
      chamaacAstralFlowColorTwo: "#445566",
      chamaacAstralFlowColorThree: "#778899",
      chamaacAstralFlowSpeed: 2.1,
      chamaacAstralFlowFlowMin: 4.2,
      chamaacAstralFlowFlowMax: 8.4,
      chamaacDeepSpaceNebulaPaletteMode: "harmony",
      chamaacDeepSpaceNebulaPrimaryColor: "#763B65",
      chamaacDeepSpaceNebulaHarmony: "complementary",
      chamaacDeepSpaceNebulaColorOne: "#5EFFF4",
      chamaacDeepSpaceNebulaColorTwo: "#763B65",
      chamaacDeepSpaceNebulaColorThree: "#1A0B2E",
      chamaacDeepSpaceNebulaSpeed: 3.6,
      chamaacGridBloomColor: "#E040FB",
      chamaacGridBloomSpeed: 2.4,
      chamaacGridBloomGridScale: 18,
      chamaacGridBloomRotationSpeed: 0.8,
      chamaacGridBloomFadeFalloff: 14,
      chamaacGridBloomDistortionAmount: 0.18,
      chamaacGridBloomFlowSpeedX: -0.6,
      chamaacGridBloomFlowSpeedY: 0.5,
      chamaacLiquidChromePaletteMode: "harmony",
      chamaacLiquidChromePrimaryColor: "#C0C0C0",
      chamaacLiquidChromeHarmony: "monochromatic",
      chamaacLiquidChromeColorOne: "#C0C0C0",
      chamaacLiquidChromeColorTwo: "#4A4A4A",
      chamaacLiquidChromeFlowSpeed: 1.4,
      chamaacLiquidChromeTimeScale: 0.4,
      chamaacWavesPaletteMode: "harmony",
      chamaacWavesPrimaryColor: "#071697",
      chamaacWavesHarmony: "triad",
      chamaacWavesBackgroundColor: "#000000",
      chamaacWavesColorOne: "#071697",
      chamaacWavesColorTwo: "#00D4FF",
      chamaacWavesColorThree: "#000000",
      chamaacWavesSpeedX: 0.08,
      chamaacWavesSpeedY: 0.04,
      chamaacWavesAmplitude: 48,
      chamaacSynthesisPaletteMode: "harmony",
      chamaacSynthesisPrimaryColor: "#33B2FF",
      chamaacSynthesisHarmony: "split-complementary",
      chamaacSynthesisColorOne: "#112233",
      chamaacSynthesisColorTwo: "#445566",
      chamaacSynthesisColorThree: "#778899",
      chamaacSynthesisSpeed: 1.8,
      chamaacSynthesisComplexity: 16,
      chamaacSynthesisScale: 2.4,
      chamaacSynthesisDistortion: 1.4,
      chamaacSynthesisGlowIntensity: 1.6,
      chamaacSynthesisFlowFrequency: 7.5,
      backgroundLinesDuration: 16,
      wavyBackgroundFill: "#111111",
      wavyColorTwo: "#ABC123",
      wavyBlur: 14,
      wavyWaveOpacity: 0.75,
      shootingStarsTrailColor: "#202020",
      shootingStarsDensity: 0.00024,
      shootingStarsTwinkle: false,
      shootingStarsFrequency: 1.5,
      canvasRevealDotsDotColor: "#00FFCC",
      canvasRevealDotsDotSpacing: 14,
      canvasRevealDotsShowGradient: false,
      spotlightColor: "#AABBCC",
      spotlightDuration: 12,
      spotlightXOffset: 180,
      lampColor: "#22D3EE",
      lampGlowOpacity: 0.9,
      lampPulseSpeed: 14,
      vortexBackgroundColor: "#040404",
      vortexBaseHue: 180,
      vortexParticleCount: 500,
      vortexRangeSpeed: 1.7,
      auroraBarsBackgroundColor: "#010203",
      auroraBarsPaletteMode: "custom",
      auroraBarsPrimaryColor: "#334455",
      auroraBarsColorOne: "#AABBCC",
      auroraBarsBarCount: 64,
      auroraBarsSpeed: 1.5,
      pixelLiquidBackgroundColor: "#110603",
      pixelLiquidBaseColor: "#A4360C",
      pixelLiquidAccentColor: "#FF7A1A",
      pixelLiquidHighlightColor: "#FFE2AB",
      pixelLiquidPixelSize: 11,
      pixelLiquidDetail: "low",
      pixelLiquidMotionSpeed: 0.5,
      tileGridPaletteMode: "custom",
      tileGridPrimaryColor: "#112233",
      tileGridColorOne: "#AABBCC",
      tileGridColorTwo: "#223344",
      tileGridColorThree: "#445566",
      tileGridColorFour: "#667788",
      tileGridColorFive: "#8899AA",
      tileGridTileSize: 64,
      tileGridJointSize: 6,
      tileGridChangeFrequency: 2.5,
      tileGridActivePercent: 32,
      tileGridOpacity: 0.93,
      hexGridPrimaryColor: "#223344",
      hexGridHarmony: "triad",
      hexGridHexSize: 72,
      hexGridJointSize: 5,
      hexGridChangeFrequency: 3.5,
      hexGridActivePercent: 28,
      hexGridOpacity: 0.82,
    }, [FEATURE_KEYS.premiumBackgrounds])

    assert.equal(settings.primaryFontColor, DEFAULT_CHIMER_SETTINGS.primaryFontColor)
    assert.equal(settings.backgroundId, "aceternity-gradient-animation")
    assert.equal(settings.sparklesParticleColor, "#ABC123")
    assert.equal(settings.sparklesParticleDensity, 180)
    assert.equal(settings.gradientAnimationSecondColor, "#224466")
    assert.equal(settings.gradientAnimationSize, 100)
    assert.equal(settings.animateUiGradientPrimaryColor, "#102030")
    assert.equal(settings.animateUiGradientHarmony, "split-complementary")
    assert.equal(settings.animateUiGradientOpacity, 0.42)
    assert.equal(settings.animateUiStarsColor, "#EAF6FF")
    assert.equal(settings.animateUiStarsSpeed, 72)
    assert.equal(settings.animateUiStarsDensity, 1.2)
    assert.equal(settings.animateUiStarsParallax, 0.08)
    assert.equal(settings.animateUiHoleStrokeColor, "#112233")
    assert.equal(settings.animateUiHoleParticleColor, "#EAF6FF")
    assert.equal(settings.animateUiHoleLineCount, 72)
    assert.equal(settings.animateUiHoleDiscCount, 64)
    assert.equal(settings.chamaacLightSpeedWarpSpeed, 3.5)
    assert.equal(settings.chamaacLightSpeedParticleCount, 180)
    assert.equal(settings.chamaacLightSpeedLightColor, "#33B2FF")
    assert.equal(settings.chamaacLightSpeedIntensity, 4.5)
    assert.equal(settings.chamaacLightSpeedRadius, 42)
    assert.equal(settings.chamaacLightSpeedCylinderLength, 220)
    assert.equal(settings.chamaacElectricMistColor, "#33B2FF")
    assert.equal(settings.chamaacElectricMistSpeed, 250)
    assert.equal(settings.chamaacElectricMistControlVersion, 2)
    assert.equal(settings.chamaacElectricMistDetail, 2.4)
    assert.equal(settings.chamaacElectricMistDistortion, 5.5)
    assert.equal(settings.chamaacElectricMistBrightness, 80)
    assert.equal(settings.chamaacAstralFlowPaletteMode, "harmony")
    assert.equal(settings.chamaacAstralFlowPrimaryColor, "#33B2FF")
    assert.equal(settings.chamaacAstralFlowHarmony, "split-complementary")
    assert.equal(settings.chamaacAstralFlowColorOne, "#112233")
    assert.equal(settings.chamaacAstralFlowColorTwo, "#445566")
    assert.equal(settings.chamaacAstralFlowColorThree, "#778899")
    assert.equal(settings.chamaacAstralFlowSpeed, 2.1)
    assert.equal(settings.chamaacAstralFlowFlowMin, 4.2)
    assert.equal(settings.chamaacAstralFlowFlowMax, 8.4)
    assert.equal(settings.chamaacDeepSpaceNebulaPaletteMode, "harmony")
    assert.equal(settings.chamaacDeepSpaceNebulaPrimaryColor, "#763B65")
    assert.equal(settings.chamaacDeepSpaceNebulaHarmony, "complementary")
    assert.equal(settings.chamaacDeepSpaceNebulaColorOne, "#5EFFF4")
    assert.equal(settings.chamaacDeepSpaceNebulaColorTwo, "#763B65")
    assert.equal(settings.chamaacDeepSpaceNebulaColorThree, "#1A0B2E")
    assert.equal(settings.chamaacDeepSpaceNebulaSpeed, 3.6)
    assert.equal(settings.chamaacGridBloomColor, "#E040FB")
    assert.equal(settings.chamaacGridBloomSpeed, 2.4)
    assert.equal(settings.chamaacGridBloomGridScale, 18)
    assert.equal(settings.chamaacGridBloomRotationSpeed, 0.8)
    assert.equal(settings.chamaacGridBloomFadeFalloff, 14)
    assert.equal(settings.chamaacGridBloomDistortionAmount, 0.18)
    assert.equal(settings.chamaacGridBloomFlowSpeedX, -0.6)
    assert.equal(settings.chamaacGridBloomFlowSpeedY, 0.5)
    assert.equal(settings.chamaacLiquidChromePaletteMode, "harmony")
    assert.equal(settings.chamaacLiquidChromePrimaryColor, "#C0C0C0")
    assert.equal(settings.chamaacLiquidChromeHarmony, "monochromatic")
    assert.equal(settings.chamaacLiquidChromeColorOne, "#C0C0C0")
    assert.equal(settings.chamaacLiquidChromeColorTwo, "#4A4A4A")
    assert.equal(settings.chamaacLiquidChromeFlowSpeed, 1.4)
    assert.equal(settings.chamaacLiquidChromeTimeScale, 0.4)
    assert.equal(settings.chamaacWavesPaletteMode, "harmony")
    assert.equal(settings.chamaacWavesPrimaryColor, "#071697")
    assert.equal(settings.chamaacWavesHarmony, "triad")
    assert.equal(settings.chamaacWavesBackgroundColor, "#000000")
    assert.equal(settings.chamaacWavesColorOne, "#071697")
    assert.equal(settings.chamaacWavesColorTwo, "#00D4FF")
    assert.equal(settings.chamaacWavesColorThree, "#000000")
    assert.equal(settings.chamaacWavesSpeedX, 0.08)
    assert.equal(settings.chamaacWavesSpeedY, 0.04)
    assert.equal(settings.chamaacWavesAmplitude, 48)
    assert.equal(settings.chamaacSynthesisPaletteMode, "harmony")
    assert.equal(settings.chamaacSynthesisPrimaryColor, "#33B2FF")
    assert.equal(settings.chamaacSynthesisHarmony, "split-complementary")
    assert.equal(settings.chamaacSynthesisColorOne, "#112233")
    assert.equal(settings.chamaacSynthesisColorTwo, "#445566")
    assert.equal(settings.chamaacSynthesisColorThree, "#778899")
    assert.equal(settings.chamaacSynthesisSpeed, 1.8)
    assert.equal(settings.chamaacSynthesisComplexity, 16)
    assert.equal(settings.chamaacSynthesisScale, 2.4)
    assert.equal(settings.chamaacSynthesisDistortion, 1.4)
    assert.equal(settings.chamaacSynthesisGlowIntensity, 1.6)
    assert.equal(settings.chamaacSynthesisFlowFrequency, 7.5)
    assert.equal(settings.backgroundLinesDuration, 16)
    assert.equal(settings.wavyBackgroundFill, "#111111")
    assert.equal(settings.wavyColorTwo, "#ABC123")
    assert.equal(settings.wavyBlur, 14)
    assert.equal(settings.wavyWaveOpacity, 0.75)
    assert.equal(settings.shootingStarsTrailColor, "#202020")
    assert.equal(settings.shootingStarsDensity, 0.00024)
    assert.equal(settings.shootingStarsTwinkle, false)
    assert.equal(settings.shootingStarsFrequency, 1.5)
    assert.equal(settings.canvasRevealDotsDotColor, "#00FFCC")
    assert.equal(settings.canvasRevealDotsDotSpacing, 14)
    assert.equal(settings.canvasRevealDotsShowGradient, false)
    assert.equal(settings.spotlightColor, "#AABBCC")
    assert.equal(settings.spotlightDuration, 12)
    assert.equal(settings.spotlightXOffset, 180)
    assert.equal(settings.lampColor, "#22D3EE")
    assert.equal(settings.lampGlowOpacity, 0.9)
    assert.equal(settings.lampPulseSpeed, 14)
    assert.equal(settings.vortexBackgroundColor, "#040404")
    assert.equal(settings.vortexBaseHue, 180)
    assert.equal(settings.vortexParticleCount, 500)
    assert.equal(settings.vortexRangeSpeed, 1.7)
    assert.equal(settings.auroraBarsBackgroundColor, "#010203")
    assert.equal(settings.auroraBarsPaletteMode, "custom")
    assert.equal(settings.auroraBarsPrimaryColor, "#334455")
    assert.equal(settings.auroraBarsColorOne, "#AABBCC")
    assert.equal(settings.auroraBarsBarCount, 64)
    assert.equal(settings.auroraBarsSpeed, 1.5)
    assert.equal(settings.pixelLiquidBackgroundColor, "#110603")
    assert.equal(settings.pixelLiquidBaseColor, "#A4360C")
    assert.equal(settings.pixelLiquidAccentColor, "#FF7A1A")
    assert.equal(settings.pixelLiquidHighlightColor, "#FFE2AB")
    assert.equal(settings.pixelLiquidPixelSize, 11)
    assert.equal(settings.pixelLiquidDetail, "low")
    assert.equal(settings.pixelLiquidMotionSpeed, 0.5)
    assert.equal(settings.tileGridPaletteMode, "custom")
    assert.equal(settings.tileGridPrimaryColor, "#112233")
    assert.equal(settings.tileGridColorOne, "#AABBCC")
    assert.equal(settings.tileGridColorTwo, "#223344")
    assert.equal(settings.tileGridColorThree, "#445566")
    assert.equal(settings.tileGridColorFour, "#667788")
    assert.equal(settings.tileGridColorFive, "#8899AA")
    assert.equal(settings.tileGridTileSize, 64)
    assert.equal(settings.tileGridJointSize, 6)
    assert.equal(settings.tileGridChangeFrequency, 2.5)
    assert.equal(settings.tileGridActivePercent, 32)
    assert.equal(settings.tileGridOpacity, 0.93)
    assert.equal(settings.hexGridPrimaryColor, "#223344")
    assert.equal(settings.hexGridHarmony, "triad")
    assert.equal(settings.hexGridHexSize, 72)
    assert.equal(settings.hexGridJointSize, 5)
    assert.equal(settings.hexGridChangeFrequency, 3.5)
    assert.equal(settings.hexGridActivePercent, 28)
    assert.equal(settings.hexGridOpacity, 0.82)
  })

  it("treats the existing paid Chimer color entitlement as premium background access", () => {
    const settings = sanitizeChimerSettingsForEntitlements({
      primaryFontColor: "#000000",
      movingBackgroundMainColor: "#ABCDEF",
      movingBackgroundOrbColor: "#FEDCBA",
      backgroundId: "aceternity-aurora",
    }, [FEATURE_KEYS.chimerCustomColors])

    assert.equal(settings.primaryFontColor, "#000000")
    assert.equal(settings.movingBackgroundMainColor, "#ABCDEF")
    assert.equal(settings.movingBackgroundOrbColor, "#FEDCBA")
    assert.equal(settings.backgroundId, "aceternity-aurora")
  })
})
