/* Generated by scripts/chimer-preview-generation/render-pilot.mjs. */

export type BackgroundPreviewAspect = "landscape" | "square" | "vertical"
export type BackgroundPreviewQuality = "low" | "standard" | "high"
export type BackgroundPreviewCodec = "vp9" | "h264"

export type BackgroundPreviewRendition = {
  aspect: BackgroundPreviewAspect
  quality: BackgroundPreviewQuality
  codec: BackgroundPreviewCodec
  url: string
  mimeType: string
  width: number
  height: number
  durationMs: number
  fps: number
  bytes: number
  sha256: string
}

export type BackgroundPreviewPoster = {
  url: string
  width: number
  height: number
  bytes: number
  sha256: string
}

export type BackgroundPreviewRenditionEntry = {
  backgroundId: string
  recipeRevision: string
  loopStrategy: "natural" | "crossfade"
  loopBoundaryMs: number
  renditions: readonly BackgroundPreviewRendition[]
  posters: Record<BackgroundPreviewAspect, BackgroundPreviewPoster>
}

export const backgroundPreviewRenditionManifest: Readonly<Record<string, BackgroundPreviewRenditionEntry>> = Object.freeze({})

export function resolvePreviewRenditionUrl(url: string): string {
  if (/^(?:https?:)?\/\//.test(url) || url.startsWith("/")) return url
  return `/chimer/background-preview-pilot/${url.replace(/^\/+/, "")}`
}

