/* Generated by scripts/chimer-preview-generation/published-runtime-manifest.mjs. */

import manifest from "../../data/background-preview-published-manifest.json" with { type: "json" }

export type BackgroundPreviewPublishedAspect = "landscape" | "square" | "vertical"
export type BackgroundPreviewPublishedQuality = "low" | "standard" | "high"
export type BackgroundPreviewPublishedCodec = "vp9" | "h264"

export type BackgroundPreviewPublishedRendition = {
  readonly aspect: BackgroundPreviewPublishedAspect
  readonly quality: BackgroundPreviewPublishedQuality
  readonly codec: BackgroundPreviewPublishedCodec
  readonly url: string
  readonly mimeType: string
}

export type BackgroundPreviewPublishedEntry = {
  readonly backgroundId: string
  readonly mediaKind: "animated" | "poster-only"
  readonly loopBoundaryMs: number
  readonly posters: Readonly<Record<BackgroundPreviewPublishedAspect, string>>
  readonly renditions: readonly BackgroundPreviewPublishedRendition[]
}

export type BackgroundPreviewPublishedManifest = {
  readonly schemaVersion: 1
  readonly catalogRevision: "catalog-approved-1"
  readonly entries: Readonly<Record<string, BackgroundPreviewPublishedEntry>>
}

export const backgroundPreviewPublishedManifest = manifest as unknown as BackgroundPreviewPublishedManifest
