/* Generated by scripts/chimer-preview-generation/published-runtime-manifest.mjs. */

import manifest from "../../data/background-preview-published-manifest.json" with { type: "json" }

export type BackgroundPreviewPublishedAspect = "landscape" | "square" | "vertical"
export type BackgroundPreviewPublishedQuality = "low" | "standard" | "high"
export type BackgroundPreviewPublishedCodec = "vp9" | "h264"

export type BackgroundPreviewPublishedRendition = {
  readonly aspect: BackgroundPreviewPublishedAspect
  readonly quality: BackgroundPreviewPublishedQuality
  readonly codec: BackgroundPreviewPublishedCodec
  readonly url: string
  readonly mimeType: string
}

export type BackgroundPreviewPublishedEntry = {
  readonly backgroundId: string
  readonly mediaKind: "animated" | "poster-only"
  readonly loopBoundaryMs: number
  readonly posters: Readonly<Record<BackgroundPreviewPublishedAspect, string>>
  readonly renditions: readonly BackgroundPreviewPublishedRendition[]
}

export type BackgroundPreviewPublishedManifest = {
  readonly schemaVersion: 1
  readonly catalogRevision: "catalog-approved-1"
  readonly entries: Readonly<Record<string, BackgroundPreviewPublishedEntry>>
}

/** Fails at module initialization if the generated JSON identity drifts. */
export function assertBackgroundPreviewPublishedManifestIdentity(value: unknown): void {
  if (typeof value !== "object" || value === null) {
    throw new Error(
      "Background preview published manifest must use schemaVersion 1 and catalogRevision catalog-approved-1.",
    )
  }
  const candidate = value as { schemaVersion?: unknown; catalogRevision?: unknown }
  if (candidate.schemaVersion !== 1
    || candidate.catalogRevision !== "catalog-approved-1") {
    throw new Error(
      "Background preview published manifest must use schemaVersion 1 and catalogRevision catalog-approved-1.",
    )
  }
}

assertBackgroundPreviewPublishedManifestIdentity(manifest)

export const backgroundPreviewPublishedManifest = manifest as unknown as BackgroundPreviewPublishedManifest
