ALTER TYPE "AuthMethodIntentPurpose" ADD VALUE 'ENROLL_TWO_FACTOR';
ALTER TYPE "AuthMethodIntentPurpose" ADD VALUE 'DISABLE_TWO_FACTOR';
ALTER TYPE "AuthMethodIntentPurpose" ADD VALUE 'REGENERATE_TWO_FACTOR_BACKUP_CODES';
