"use server"

import { revalidatePath } from "next/cache"
import { requireFullAdminUser } from "@/lib/admin/access"
import { deliverAdminEmailIntent } from "@/lib/admin/email-intents"
import {
  ADMIN_REASON_CODES,
  validateAdminReason,
  type AdminReasonCode,
} from "@/lib/admin/operation-contract"
import {
  resetUserTwoFactor,
  revokeUserSessions,
  sendAdminPasswordReset,
} from "@/lib/admin/security-service"
import { prisma } from "@/lib/prisma"
import { safeErrorCode } from "@/lib/safe-error-code"

export type SecurityActionState =
  | { status: "idle"; message: "" }
  | { status: "success" | "warning" | "error"; message: string }

const SESSION_REVOCATION_CONFIRMATION = "CONFIRM_SECURITY_SESSION_REVOCATION"
const PASSWORD_RESET_CONFIRMATION = "CONFIRM_ADMIN_PASSWORD_RESET"
const SESSION_REFRESH_OUTCOME = "The user will be signed out on the next successful database-backed session refresh."
const SAFE_SECURITY_ERRORS = new Set([
  "This security state changed since the operation was prepared. Refresh the account and try again.",
  "You cannot perform security remediation on your own account.",
  "Target account does not have a verified email address.",
  "The confirmation email does not match the target account.",
  "Two-factor authentication is not enabled for this account.",
  "Two-factor authentication changed since this operation was prepared. Refresh the account and try again.",
])

type ParsedCommon = {
  targetUserId: string
  reasonCode: AdminReasonCode
  internalNote: string | null
  operationId: string
}

type NotificationOutcome = {
  status: "DELIVERED" | "FAILED" | "BUSY" | "AMBIGUOUS"
  attempted: boolean
} | null

/**
 * Invalidates a target's older JWTs through the canonical version owner. The
 * submitted operation key is generated by the server render and never replaced
 * during submission; adapter Session counts remain optimistic-lock evidence.
 */
export async function revokeUserSessionsAction(
  userId: string,
  _previousState: SecurityActionState,
  formData: FormData,
): Promise<SecurityActionState> {
  const actor = await requireFullAdminUser()
  const parsed = parseCommon(userId, formData)
  if (!parsed.ok) return parsed.state
  if (formValue(formData, "confirmation") !== SESSION_REVOCATION_CONFIRMATION) {
    return { status: "error", message: "Confirm that existing sign-in tokens will be invalidated." }
  }
  const expectedAuthSessionVersion = parseSafeCount(formData, "expectedAuthSessionVersion")
  const expectedSessionCount = parseSafeCount(formData, "expectedSessionCount")
  if (expectedAuthSessionVersion === null || expectedSessionCount === null) {
    return { status: "error", message: "Refresh this account before invalidating sign-in tokens." }
  }

  let result: Awaited<ReturnType<typeof revokeUserSessions>>
  try {
    result = await revokeUserSessions({
      prismaClient: prisma,
      actorUserId: actor.id,
      targetUserId: parsed.value.targetUserId,
      expectedAuthSessionVersion,
      expectedSessionCount,
      reasonCode: parsed.value.reasonCode,
      internalNote: parsed.value.internalNote,
      idempotencyKey: parsed.value.operationId,
    })
  } catch (error) {
    logSecurityFailure("REVOKE_SESSIONS", error)
    return safeServiceError(error, "Sign-in tokens could not be invalidated. Refresh the account and try again.")
  }

  const notification = await deliverNotification(result.emailIntentId, "REVOKE_SESSIONS")
  revalidateSecuritySurfaces(userId)
  const completed = result.replayed
    ? "This sign-in token invalidation was already completed."
    : `Existing sign-in tokens were invalidated. ${SESSION_REFRESH_OUTCOME}`
  return notificationState(completed, notification, result.replayed)
}

/**
 * Creates a fresh standard password-reset request. The Task 12 service owns the
 * token and standard reset-mail delivery; this action must not pass the marker
 * through the account-change notification delivery or retry owners.
 */
export async function sendAdminPasswordResetAction(
  userId: string,
  _previousState: SecurityActionState,
  formData: FormData,
): Promise<SecurityActionState> {
  const actor = await requireFullAdminUser()
  const parsed = parseCommon(userId, formData)
  if (!parsed.ok) return parsed.state
  if (formValue(formData, "confirmation") !== PASSWORD_RESET_CONFIRMATION) {
    return { status: "error", message: "Confirm that a fresh password-reset link will be created." }
  }

  let result: Awaited<ReturnType<typeof sendAdminPasswordReset>>
  try {
    result = await sendAdminPasswordReset({
      prismaClient: prisma,
      actorUserId: actor.id,
      targetUserId: parsed.value.targetUserId,
      reasonCode: parsed.value.reasonCode,
      internalNote: parsed.value.internalNote,
      idempotencyKey: parsed.value.operationId,
    })
  } catch (error) {
    logSecurityFailure("PASSWORD_RESET", error)
    return safeServiceError(error, "The password-reset request could not be completed. Refresh the account and try again.")
  }

  revalidateSecuritySurfaces(userId)
  if (result.replayed) {
    if (result.deliveryStatus === "DELIVERED") {
      return { status: "success", message: "This password-reset request was already completed. Its email was already delivered; no new link was created or sent." }
    }
    if (result.deliveryStatus === "FAILED") {
      return { status: "warning", message: "This password-reset request was already completed and delivery is recorded as failed; no old reset link was reused. Send a new reset link from Activity." }
    }
    return { status: "warning", message: "This password-reset request was already completed. Delivery is still pending and no new link was created or sent. Check Activity before creating another request." }
  }
  if (result.deliveryStatus === "DELIVERED") {
    return { status: "success", message: "A fresh password-reset link was created and delivered." }
  }
  if (result.deliveryStatus === "FAILED" && result.deliveryAttempted) {
    return { status: "warning", message: "A fresh password-reset link was created, but email delivery failed. Send a new reset link from Activity." }
  }
  if (result.deliveryStatus === "PENDING" && result.deliveryAttempted) {
    return { status: "warning", message: "A fresh password-reset request was created and delivery was attempted, but its outcome could not be confirmed. Check Activity before creating another request." }
  }
  return { status: "warning", message: "A fresh password-reset request was created, but delivery was not attempted. Check Activity before creating another request." }
}

/** Resets enabled 2FA only after the service verifies the typed target email. */
export async function resetUserTwoFactorAction(
  userId: string,
  _previousState: SecurityActionState,
  formData: FormData,
): Promise<SecurityActionState> {
  const actor = await requireFullAdminUser()
  const parsed = parseCommon(userId, formData)
  if (!parsed.ok) return parsed.state
  const confirmationEmail = formValue(formData, "confirmationEmail")
  if (!confirmationEmail || confirmationEmail.length > 320 || /[\r\n]/.test(confirmationEmail)) {
    return { status: "error", message: "Type the target account email to confirm the two-factor reset." }
  }
  if (formValue(formData, "expectedTwoFactorEnabled") !== "true") {
    return { status: "error", message: "Refresh this account before resetting two-factor authentication." }
  }

  let result: Awaited<ReturnType<typeof resetUserTwoFactor>>
  try {
    result = await resetUserTwoFactor({
      prismaClient: prisma,
      actorUserId: actor.id,
      targetUserId: parsed.value.targetUserId,
      confirmationEmail,
      expectedTwoFactorEnabled: true,
      reasonCode: parsed.value.reasonCode,
      internalNote: parsed.value.internalNote,
      idempotencyKey: parsed.value.operationId,
    })
  } catch (error) {
    logSecurityFailure("RESET_TWO_FACTOR", error)
    return safeServiceError(error, "Two-factor authentication could not be reset. Refresh the account and try again.")
  }

  const notification = await deliverNotification(result.emailIntentId, "RESET_TWO_FACTOR")
  revalidateSecuritySurfaces(userId)
  const completed = result.replayed
    ? "This two-factor reset was already completed."
    : `Two-factor authentication was reset and existing sign-in tokens were invalidated. ${SESSION_REFRESH_OUTCOME}`
  return notificationState(completed, notification, result.replayed)
}

function parseCommon(
  boundUserId: string,
  formData: FormData,
): { ok: true; value: ParsedCommon } | { ok: false; state: SecurityActionState } {
  const targetUserId = formValue(formData, "targetUserId")
  if (!targetUserId || targetUserId !== boundUserId) {
    return { ok: false, state: { status: "error", message: "Refresh this account before performing a security action." } }
  }
  const operationId = formValue(formData, "operationId")
  if (!operationId || !isUuid(operationId)) {
    return { ok: false, state: { status: "error", message: "Refresh this account before performing a security action." } }
  }
  const reasonCode = formValue(formData, "reasonCode")
  const rawInternalNote = formValue(formData, "internalNote") ?? ""
  if (!reasonCode || !ADMIN_REASON_CODES.includes(reasonCode as AdminReasonCode) || rawInternalNote.length > 500) {
    return { ok: false, state: { status: "error", message: "Choose a valid reason and check the internal note." } }
  }
  const internalNote = rawInternalNote.trim() || null
  try {
    validateAdminReason(reasonCode, internalNote)
  } catch {
    return { ok: false, state: { status: "error", message: "Choose a valid reason and check the internal note." } }
  }
  return {
    ok: true,
    value: {
      targetUserId,
      operationId,
      reasonCode: reasonCode as AdminReasonCode,
      internalNote,
    },
  }
}

/** Initial delivery can recover only PENDING; FAILED and DELIVERED never resend here. */
async function deliverNotification(intentId: string, action: string): Promise<NotificationOutcome> {
  try {
    const delivery = await deliverAdminEmailIntent({ prismaClient: prisma, intentId })
    return { status: delivery.status, attempted: delivery.attempted }
  } catch (error) {
    logSecurityFailure(`${action}_EMAIL`, error)
    return null
  }
}

function notificationState(completed: string, delivery: NotificationOutcome, replayed: boolean): SecurityActionState {
  if (delivery?.status === "DELIVERED" && delivery.attempted) {
    return { status: "success", message: `${completed} Email notification delivered.` }
  }
  if (delivery?.status === "DELIVERED") {
    return { status: "success", message: `${completed} The email notification was already delivered; no new send was attempted.` }
  }
  if (delivery?.status === "FAILED" && delivery.attempted) {
    return { status: "warning", message: `${completed} The email notification failed. Retry it from Activity.` }
  }
  if (delivery?.status === "FAILED") {
    return { status: "warning", message: `${completed} The email notification is recorded as failed; no new send was attempted. Check Activity for the available next step.` }
  }
  return {
    status: "warning",
    message: `${completed} Email delivery could not be confirmed. ${replayed ? "Check Activity before retrying." : "Check Activity for the notification status."}`,
  }
}

function safeServiceError(error: unknown, fallback: string): SecurityActionState {
  return {
    status: "error",
    message: error instanceof Error && SAFE_SECURITY_ERRORS.has(error.message) ? error.message : fallback,
  }
}

function logSecurityFailure(action: string, error: unknown) {
  console.error("Admin security operation failed", { action, code: safeErrorCode(error) })
}

function revalidateSecuritySurfaces(userId: string) {
  revalidatePath(`/admin/users/${encodeURIComponent(userId)}`)
  revalidatePath("/admin/users")
}

function parseSafeCount(formData: FormData, name: string): number | null {
  const value = formValue(formData, name)
  if (!value || !/^(?:0|[1-9]\d*)$/.test(value)) return null
  const count = Number(value)
  return Number.isSafeInteger(count) ? count : null
}

function formValue(formData: FormData, name: string) {
  const value = formData.get(name)
  return typeof value === "string" ? value : null
}

function isUuid(value: string) {
  return /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)
}
