import type { AnatomyCitation, AnatomyConcept, AnatomyEntityTerm } from "../anatomy-foundation.ts"
import type { AnatomySeedSection } from "./sections.ts"

type TermSpec = {
  term: string
  termType: "preferred" | "formal" | "common" | "clinical" | "historical" | "eponym" | "abbreviation" | "alternate"
  sourceRef?: string
  notes?: string
}

type ConceptSpec = AnatomyConcept & {
  locator: string
  citationFactType?: "clinical_summary" | "education_summary"
  terms?: TermSpec[]
}

const PHYSIOLOGY_SOURCE = "openstax-human-biology"
const ENERGETIC_SOURCE = "massagelab-authored-energetic-anatomy"
const PHYSIOLOGY_LOCATOR = "OpenStax CNX Human Biology body-system physiology review source; MassageLab-authored summary."
const ENERGETIC_LOCATOR = "MassageLab-authored non-diagnostic energetic-anatomy taxonomy, 2026-05-24."

const CONCEPTS: ConceptSpec[] = [
  {
    id: "concept-digestive-system",
    slug: "digestive-system",
    name: "Digestive System",
    conceptType: "system_structure",
    bodySystem: "digestive",
    description: "The digestive system includes organs and tissues that receive food, break it down, absorb nutrients, and eliminate waste. In MassageLab it anchors non-diagnostic education about abdomen-region body systems.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: PHYSIOLOGY_LOCATOR,
    terms: [{ term: "gastrointestinal system", termType: "alternate" }],
  },
  {
    id: "concept-gastrointestinal-tract",
    slug: "gastrointestinal-tract",
    name: "Gastrointestinal Tract",
    conceptType: "system_structure",
    bodySystem: "digestive",
    description: "The gastrointestinal tract is the continuous digestive tube from mouth to anus. It gives a high-level structural frame for digestive-system learning without modeling diagnosis or pathology.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: PHYSIOLOGY_LOCATOR,
    terms: [{ term: "GI tract", termType: "abbreviation" }, { term: "alimentary canal", termType: "clinical" }],
  },
  {
    id: "concept-accessory-digestive-organs",
    slug: "accessory-digestive-organs",
    name: "Accessory Digestive Organs",
    conceptType: "system_structure",
    bodySystem: "digestive",
    description: "Accessory digestive organs support digestion without forming the full length of the digestive tract. This concept covers high-level anatomy such as liver, gallbladder, pancreas, and salivary glands.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: PHYSIOLOGY_LOCATOR,
    terms: [{ term: "digestive accessory organs", termType: "alternate" }],
  },
  {
    id: "concept-digestion",
    slug: "digestion",
    name: "Digestion",
    conceptType: "system_function",
    bodySystem: "digestive",
    description: "Digestion is the mechanical and chemical breakdown of food into smaller components. It is represented as a basic physiology concept for education and exam coverage, not treatment decision-making.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: PHYSIOLOGY_LOCATOR,
    terms: [{ term: "food breakdown", termType: "common" }],
  },
  {
    id: "concept-nutrient-absorption",
    slug: "nutrient-absorption",
    name: "Nutrient Absorption",
    conceptType: "system_function",
    bodySystem: "digestive",
    description: "Nutrient absorption is the movement of digested nutrients from the digestive tract into body fluids for distribution. It supports basic physiology literacy for massage education.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: PHYSIOLOGY_LOCATOR,
    terms: [{ term: "absorption", termType: "common" }],
  },
  {
    id: "concept-bowel-elimination",
    slug: "bowel-elimination",
    name: "Bowel Elimination",
    conceptType: "system_function",
    bodySystem: "digestive",
    description: "Bowel elimination is the digestive system's removal of undigested material and waste. It is included only as general A&P coverage and client-friendly education context.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: PHYSIOLOGY_LOCATOR,
    terms: [{ term: "defecation", termType: "clinical" }],
  },
  {
    id: "concept-endocrine-system",
    slug: "endocrine-system",
    name: "Endocrine System",
    conceptType: "system_structure",
    bodySystem: "endocrine",
    description: "The endocrine system includes hormone-producing glands and cells that communicate through the bloodstream. It is modeled at a high level for A&P and scope-aware education.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: PHYSIOLOGY_LOCATOR,
    terms: [{ term: "hormonal system", termType: "common" }],
  },
  {
    id: "concept-endocrine-gland",
    slug: "endocrine-gland",
    name: "Endocrine Gland",
    conceptType: "system_structure",
    bodySystem: "endocrine",
    description: "An endocrine gland releases hormones internally rather than through a duct to the body surface. This concept supports terminology for glands such as thyroid, adrenal, pituitary, and pancreas.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: PHYSIOLOGY_LOCATOR,
    terms: [{ term: "ductless gland", termType: "alternate" }],
  },
  {
    id: "concept-hormone",
    slug: "hormone",
    name: "Hormone",
    conceptType: "system_function",
    bodySystem: "endocrine",
    description: "A hormone is a chemical messenger that helps regulate activity in target tissues. MassageLab uses this as basic physiology context rather than as a basis for endocrine treatment claims.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: PHYSIOLOGY_LOCATOR,
    terms: [{ term: "chemical messenger", termType: "common" }],
  },
  {
    id: "concept-endocrine-feedback",
    slug: "endocrine-feedback",
    name: "Endocrine Feedback",
    conceptType: "system_function",
    bodySystem: "endocrine",
    description: "Endocrine feedback is the regulatory loop by which hormone levels and body conditions influence further hormone release. It supports general homeostasis education.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: PHYSIOLOGY_LOCATOR,
    terms: [{ term: "hormonal feedback", termType: "common" }, { term: "negative feedback", termType: "clinical" }],
  },
  {
    id: "concept-homeostasis",
    slug: "homeostasis",
    name: "Homeostasis",
    conceptType: "system_function",
    bodySystem: "general",
    description: "Homeostasis is the body's tendency to regulate internal conditions within working ranges. It bridges endocrine, nervous, cardiovascular, urinary, and thermoregulation concepts.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: PHYSIOLOGY_LOCATOR,
    terms: [{ term: "internal balance", termType: "common" }],
  },
  {
    id: "concept-integumentary-system",
    slug: "integumentary-system",
    name: "Integumentary System",
    conceptType: "system_structure",
    bodySystem: "integumentary",
    description: "The integumentary system includes skin and associated structures. It is central to massage education because touch, barrier function, temperature, and tissue history all meet at the skin.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: PHYSIOLOGY_LOCATOR,
    terms: [{ term: "skin system", termType: "common" }],
  },
  {
    id: "concept-epidermis",
    slug: "epidermis",
    name: "Epidermis",
    conceptType: "system_structure",
    bodySystem: "integumentary",
    description: "The epidermis is the outer epithelial layer of the skin. It provides a basic structural reference for barrier function and touch-related education.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: PHYSIOLOGY_LOCATOR,
  },
  {
    id: "concept-dermis",
    slug: "dermis",
    name: "Dermis",
    conceptType: "system_structure",
    bodySystem: "integumentary",
    description: "The dermis is the deeper connective-tissue layer of skin containing vessels, nerves, glands, and connective structures. It helps bridge skin anatomy with touch and tissue education.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: PHYSIOLOGY_LOCATOR,
  },
  {
    id: "concept-skin-barrier-function",
    slug: "skin-barrier-function",
    name: "Skin Barrier Function",
    conceptType: "system_function",
    bodySystem: "integumentary",
    description: "Skin barrier function helps protect the body from mechanical, chemical, microbial, and water-balance stressors. It is included as general education and safety context.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: PHYSIOLOGY_LOCATOR,
    terms: [{ term: "barrier protection", termType: "common" }],
  },
  {
    id: "concept-thermoregulation",
    slug: "thermoregulation",
    name: "Thermoregulation",
    conceptType: "system_function",
    bodySystem: "integumentary",
    description: "Thermoregulation is body-temperature regulation involving skin blood flow, sweating, nervous-system control, and behavior. It belongs in broad A&P education for bodywork settings.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: PHYSIOLOGY_LOCATOR,
    terms: [{ term: "temperature regulation", termType: "common" }],
  },
  {
    id: "concept-lymphatic-system",
    slug: "lymphatic-system",
    name: "Lymphatic System",
    conceptType: "system_structure",
    bodySystem: "lymphatic",
    description: "The lymphatic system includes lymph, lymphatic vessels, lymph nodes, and related immune tissues. It is modeled separately from treatment protocols or drainage claims.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: PHYSIOLOGY_LOCATOR,
    terms: [{ term: "lymph system", termType: "common" }],
  },
  {
    id: "concept-lymph",
    slug: "lymph",
    name: "Lymph",
    conceptType: "system_structure",
    bodySystem: "lymphatic",
    description: "Lymph is fluid within lymphatic vessels that participates in fluid balance and immune surveillance. It supports basic system literacy for massage education.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: PHYSIOLOGY_LOCATOR,
  },
  {
    id: "concept-lymph-node",
    slug: "lymph-node",
    name: "Lymph Node",
    conceptType: "system_structure",
    bodySystem: "lymphatic",
    description: "A lymph node is an immune-related structure along lymphatic pathways. It filters lymph and provides a context for immune-system education without implying treatment or diagnosis.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: PHYSIOLOGY_LOCATOR,
  },
  {
    id: "concept-immune-response",
    slug: "immune-response",
    name: "Immune Response",
    conceptType: "system_function",
    bodySystem: "lymphatic",
    description: "An immune response is coordinated activity that helps defend the body and manage injury or infection signals. It is included as general physiology context, not treatment instruction.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: PHYSIOLOGY_LOCATOR,
  },
  {
    id: "concept-innate-immunity",
    slug: "innate-immunity",
    name: "Innate Immunity",
    conceptType: "system_function",
    bodySystem: "lymphatic",
    description: "Innate immunity is a broad, rapid defense system present before specific exposure. It includes barriers and generalized immune responses important for A&P literacy.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: PHYSIOLOGY_LOCATOR,
  },
  {
    id: "concept-adaptive-immunity",
    slug: "adaptive-immunity",
    name: "Adaptive Immunity",
    conceptType: "system_function",
    bodySystem: "lymphatic",
    description: "Adaptive immunity is a more specific immune response shaped by exposure. It is represented as an introductory concept for exam coverage and client education boundaries.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: PHYSIOLOGY_LOCATOR,
  },
  {
    id: "concept-reproductive-system",
    slug: "reproductive-system",
    name: "Reproductive System",
    conceptType: "system_structure",
    bodySystem: "reproductive",
    description: "The reproductive system includes organs and tissues involved in gamete production, reproductive hormones, pregnancy-related anatomy, and reproduction. MassageLab keeps this at scope-aware A&P level.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: PHYSIOLOGY_LOCATOR,
  },
  {
    id: "concept-gamete",
    slug: "gamete",
    name: "Gamete",
    conceptType: "system_structure",
    bodySystem: "reproductive",
    description: "A gamete is a reproductive cell such as an egg or sperm. It is a basic structural and functional concept for reproductive-system literacy.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: PHYSIOLOGY_LOCATOR,
  },
  {
    id: "concept-reproductive-hormone-regulation",
    slug: "reproductive-hormone-regulation",
    name: "Reproductive Hormone Regulation",
    conceptType: "system_function",
    bodySystem: "reproductive",
    description: "Reproductive hormone regulation coordinates reproductive tissues and cycles through endocrine signaling. It is included as broad A&P context, not as treatment guidance.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: PHYSIOLOGY_LOCATOR,
    terms: [{ term: "sex hormone regulation", termType: "common" }],
  },
  {
    id: "concept-fertilization",
    slug: "fertilization",
    name: "Fertilization",
    conceptType: "system_function",
    bodySystem: "reproductive",
    description: "Fertilization is the union of gametes that begins embryonic development. It is included only as broad reproductive-system A&P coverage.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: PHYSIOLOGY_LOCATOR,
  },
  {
    id: "concept-sensory-system",
    slug: "sensory-system",
    name: "Sensory Functions",
    conceptType: "nervous_system_subtopic",
    bodySystem: "nervous",
    description: "Sensory functions include receptors, nerves, and brain pathways that detect internal and external stimuli. MassageLab keeps this as a nervous-system subtopic, not a separate textbook organ system.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: PHYSIOLOGY_LOCATOR,
  },
  {
    id: "concept-sensory-receptor",
    slug: "sensory-receptor",
    name: "Sensory Receptor",
    conceptType: "system_structure",
    bodySystem: "nervous",
    description: "A sensory receptor detects a type of stimulus and helps convert it into nervous-system signaling. This concept connects skin, muscles, joints, and special senses.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: PHYSIOLOGY_LOCATOR,
  },
  {
    id: "concept-somatosensation",
    slug: "somatosensation",
    name: "Somatosensation",
    conceptType: "system_function",
    bodySystem: "nervous",
    description: "Somatosensation includes body sensations such as touch, pressure, temperature, body position, and pain signaling. It supports massage-relevant education without diagnosing sensory disorders.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: PHYSIOLOGY_LOCATOR,
    terms: [{ term: "body sensation", termType: "common" }],
  },
  {
    id: "concept-special-senses",
    slug: "special-senses",
    name: "Special Senses",
    conceptType: "system_structure",
    bodySystem: "nervous",
    description: "Special senses include vision, hearing, equilibrium, smell, and taste. This first pass models them as high-level A&P concepts rather than detailed organ systems.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: PHYSIOLOGY_LOCATOR,
  },
  {
    id: "concept-vestibular-sense",
    slug: "vestibular-sense",
    name: "Vestibular Sense",
    conceptType: "system_function",
    bodySystem: "nervous",
    description: "Vestibular sense contributes to balance and spatial orientation. It is included for broad nervous-system and special-senses coverage in movement education context.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: PHYSIOLOGY_LOCATOR,
    terms: [{ term: "sense of balance", termType: "common" }],
  },
  {
    id: "concept-urinary-system",
    slug: "urinary-system",
    name: "Urinary System",
    conceptType: "system_structure",
    bodySystem: "urinary",
    description: "The urinary system includes kidneys, ureters, bladder, and urethra. It helps regulate waste removal, fluid balance, and electrolyte context in general A&P education.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: PHYSIOLOGY_LOCATOR,
    terms: [{ term: "renal system", termType: "alternate" }],
  },
  {
    id: "concept-kidney",
    slug: "kidney",
    name: "Kidney",
    conceptType: "system_structure",
    bodySystem: "urinary",
    description: "The kidney is a urinary-system organ that filters blood, supports fluid and electrolyte regulation, and contributes to waste removal. It is modeled at introductory A&P depth.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: PHYSIOLOGY_LOCATOR,
    terms: [{ term: "renal organ", termType: "clinical" }],
  },
  {
    id: "concept-nephron",
    slug: "nephron",
    name: "Nephron",
    conceptType: "system_structure",
    bodySystem: "urinary",
    description: "A nephron is a microscopic functional unit of the kidney. It gives the database a basic structural anchor for urine formation and fluid-balance education.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: PHYSIOLOGY_LOCATOR,
  },
  {
    id: "concept-urine-formation",
    slug: "urine-formation",
    name: "Urine Formation",
    conceptType: "system_function",
    bodySystem: "urinary",
    description: "Urine formation is the kidney process that filters, reabsorbs, secretes, and concentrates substances to produce urine. It is included as broad physiology coverage.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: PHYSIOLOGY_LOCATOR,
  },
  {
    id: "concept-fluid-electrolyte-balance",
    slug: "fluid-electrolyte-balance",
    name: "Fluid and Electrolyte Balance",
    conceptType: "system_function",
    bodySystem: "urinary",
    description: "Fluid and electrolyte balance is regulation of body water and dissolved ions through kidney, endocrine, cardiovascular, and nervous-system interactions. It is included as general A&P education.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: PHYSIOLOGY_LOCATOR,
    terms: [{ term: "water and salt balance", termType: "common" }],
  },
  {
    id: "concept-energetic-anatomy",
    slug: "energetic-anatomy",
    name: "Energetic Anatomy",
    conceptType: "energetic_anatomy",
    bodySystem: "energetic",
    description: "Energetic anatomy is a non-diagnostic education category used in some bodywork traditions to describe body maps such as channels, centers, fields, or flows. MassageLab keeps it separate from biomedical anatomy.",
    sourceRef: ENERGETIC_SOURCE,
    locator: ENERGETIC_LOCATOR,
    citationFactType: "education_summary",
    terms: [{ term: "energy anatomy", termType: "common" }],
  },
  {
    id: "concept-chakra-concept",
    slug: "chakra-concept",
    name: "Chakra Concept",
    conceptType: "energetic_anatomy",
    bodySystem: "energetic",
    description: "The chakra concept is an energetic-anatomy body map used in some traditions to organize attention around named centers. It is represented as cultural and educational terminology, not biomedical anatomy.",
    sourceRef: ENERGETIC_SOURCE,
    locator: ENERGETIC_LOCATOR,
    citationFactType: "education_summary",
    terms: [{ term: "chakra", termType: "common" }, { term: "energy center", termType: "common" }],
  },
  {
    id: "concept-meridian-concept",
    slug: "meridian-concept",
    name: "Meridian Concept",
    conceptType: "energetic_anatomy",
    bodySystem: "energetic",
    description: "The meridian concept is an energetic-anatomy body map used in some traditions to describe named channels or pathways. MassageLab stores it as non-diagnostic education terminology only.",
    sourceRef: ENERGETIC_SOURCE,
    locator: ENERGETIC_LOCATOR,
    citationFactType: "education_summary",
    terms: [{ term: "meridian", termType: "common" }, { term: "energy channel", termType: "common" }],
  },
  {
    id: "concept-biofield-concept",
    slug: "biofield-concept",
    name: "Biofield Concept",
    conceptType: "energetic_anatomy",
    bodySystem: "energetic",
    description: "The biofield concept is a broad energetic-anatomy term for an organizing field or space around and through the body in some bodywork traditions. It remains distinct from clinical anatomy facts.",
    sourceRef: ENERGETIC_SOURCE,
    locator: ENERGETIC_LOCATOR,
    citationFactType: "education_summary",
    terms: [{ term: "energy field", termType: "common" }],
  },
]

function termSlug(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")
}

function conceptSeedRecord(concept: ConceptSpec): AnatomyConcept {
  return {
    id: concept.id,
    slug: concept.slug,
    name: concept.name,
    conceptType: concept.conceptType,
    bodySystem: concept.bodySystem,
    description: concept.description,
    sourceRef: concept.sourceRef,
  }
}

function conceptTerms(concept: ConceptSpec): AnatomyEntityTerm[] {
  return [
    {
      id: `term-${concept.slug}-preferred`,
      anatomyEntityType: "anatomy_concept",
      anatomyEntitySlug: concept.slug,
      term: concept.name,
      termType: "preferred",
      sourceRef: concept.sourceRef,
    },
    ...(concept.terms ?? []).map((term): AnatomyEntityTerm => ({
      id: `term-${concept.slug}-${term.termType}-${termSlug(term.term)}`,
      anatomyEntityType: "anatomy_concept",
      anatomyEntitySlug: concept.slug,
      term: term.term,
      termType: term.termType,
      notes: term.notes,
      sourceRef: term.sourceRef ?? concept.sourceRef,
    })),
  ]
}

function conceptCitation(concept: ConceptSpec): AnatomyCitation {
  return {
    id: `citation-concept-${concept.slug}-${concept.citationFactType ?? "clinical_summary"}`,
    slug: `citation-concept-${concept.slug}-${concept.citationFactType ?? "clinical-summary"}`,
    entityType: "anatomy_concept",
    entitySlug: concept.slug,
    factType: concept.citationFactType ?? "clinical_summary",
    factSlug: `concept:${concept.slug}`,
    sourceRef: concept.sourceRef,
    sourceLocator: concept.locator,
    citationNote: "Reviewed reusable support for MassageLab-authored body-system concept summary. Do not copy source prose directly.",
    reviewStatus: "reviewed",
  }
}

export const BODY_SYSTEM_CONCEPTS_SECTION: AnatomySeedSection = {
  concepts: CONCEPTS.map(conceptSeedRecord),
  entityTerms: CONCEPTS.flatMap(conceptTerms),
  citations: CONCEPTS.map(conceptCitation),
}
