import type { AnatomyCitation, AnatomyConcept, AnatomyEntityTerm } from "../anatomy-foundation.ts"
import type { AnatomySeedSection } from "./sections.ts"

type TermSpec = {
  term: string
  termType: "preferred" | "formal" | "common" | "clinical" | "historical" | "eponym" | "abbreviation" | "alternate"
  sourceRef?: string
  notes?: string
}

type ConceptSpec = AnatomyConcept & {
  locator: string
  terms?: TermSpec[]
}

const PHYSIOLOGY_SOURCE = "openstax-human-biology"
const LOCATOR = "OpenStax CNX Human Biology cardiorespiratory, circulation, gas-exchange, immune, and lymphatic review source; MassageLab-authored summary."

const CONCEPTS: ConceptSpec[] = [
  {
    id: "concept-cardiovascular-system",
    slug: "cardiovascular-system",
    name: "Cardiovascular System",
    conceptType: "system_structure",
    bodySystem: "cardiovascular",
    description: "The cardiovascular system includes the heart, blood, and blood vessels that move blood through pulmonary and systemic circuits. In MassageLab it anchors non-diagnostic education about circulation and tissue supply.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "circulatory system", termType: "alternate" }],
  },
  {
    id: "concept-heart",
    slug: "heart",
    name: "Heart",
    conceptType: "system_structure",
    bodySystem: "cardiovascular",
    description: "The heart is the muscular pump that moves blood through pulmonary and systemic circulation. This concept is modeled for broad A&P literacy and red-flag awareness, not for cardiac assessment.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "cardiac pump", termType: "common" }],
  },
  {
    id: "concept-blood-vessel",
    slug: "blood-vessel",
    name: "Blood Vessel",
    conceptType: "system_structure",
    bodySystem: "cardiovascular",
    description: "A blood vessel is a tubular pathway that carries blood. Arteries, veins, and capillaries are represented separately so body-map and education tools can distinguish broad circulation roles.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "vascular pathway", termType: "common" }],
  },
  {
    id: "concept-artery",
    slug: "artery",
    name: "Artery",
    conceptType: "system_structure",
    bodySystem: "cardiovascular",
    description: "An artery is a blood vessel that carries blood away from the heart. The dataset uses artery concepts to connect named regional vessels with circulation education and tissue supply context.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
  },
  {
    id: "concept-vein",
    slug: "vein",
    name: "Vein",
    conceptType: "system_structure",
    bodySystem: "cardiovascular",
    description: "A vein is a blood vessel that returns blood toward the heart. It supports education about venous return, drainage language, and superficial versus deep vessel context.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
  },
  {
    id: "concept-capillary",
    slug: "capillary",
    name: "Capillary",
    conceptType: "system_structure",
    bodySystem: "cardiovascular",
    description: "A capillary is a very small blood vessel where exchange can occur between blood and nearby tissues. It helps explain oxygen, nutrient, waste, and fluid-exchange concepts at a basic level.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
  },
  {
    id: "concept-systemic-circulation",
    slug: "systemic-circulation",
    name: "Systemic Circulation",
    conceptType: "system_function",
    bodySystem: "cardiovascular",
    description: "Systemic circulation moves blood between the heart and most body tissues. It gives MassageLab a client-friendly frame for tissue supply without implying treatment of circulation disorders.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "body circulation", termType: "common" }],
  },
  {
    id: "concept-pulmonary-circulation",
    slug: "pulmonary-circulation",
    name: "Pulmonary Circulation",
    conceptType: "system_function",
    bodySystem: "cardiovascular",
    description: "Pulmonary circulation moves blood between the heart and lungs. It links cardiovascular and respiratory concepts for introductory education about oxygen and carbon dioxide exchange.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "lung circulation", termType: "common" }],
  },
  {
    id: "concept-cardiac-output",
    slug: "cardiac-output",
    name: "Cardiac Output",
    conceptType: "system_function",
    bodySystem: "cardiovascular",
    description: "Cardiac output is the amount of blood the heart pumps over time. It is included as a broad physiology concept for exercise, stress, and circulation education without diagnostic use.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
  },
  {
    id: "concept-blood-pressure",
    slug: "blood-pressure",
    name: "Blood Pressure",
    conceptType: "system_function",
    bodySystem: "cardiovascular",
    description: "Blood pressure is the force of blood against vessel walls. MassageLab stores it for A&P literacy and safety context, while measurement and diagnosis remain outside the anatomy seed.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "BP", termType: "abbreviation" }],
  },
  {
    id: "concept-venous-return",
    slug: "venous-return",
    name: "Venous Return",
    conceptType: "system_function",
    bodySystem: "cardiovascular",
    description: "Venous return is blood flow back toward the heart through veins. It supports cautious education about posture, movement, breathing, and muscle activity without making treatment claims.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
  },
  {
    id: "concept-respiratory-system",
    slug: "respiratory-system",
    name: "Respiratory System",
    conceptType: "system_structure",
    bodySystem: "respiratory",
    description: "The respiratory system includes airways, lungs, and gas-exchange surfaces that move air and exchange oxygen and carbon dioxide. It connects breathing mechanics with physiology education.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
  },
  {
    id: "concept-airway",
    slug: "airway",
    name: "Airway",
    conceptType: "system_structure",
    bodySystem: "respiratory",
    description: "The airway is the passage system that conducts air toward and away from the lungs. It is modeled as a high-level concept rather than a detailed respiratory-organ atlas in this pass.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "respiratory tract", termType: "alternate" }],
  },
  {
    id: "concept-lung",
    slug: "lung",
    name: "Lung",
    conceptType: "system_structure",
    bodySystem: "respiratory",
    description: "The lungs are paired respiratory organs where ventilation supports gas exchange with blood. MassageLab uses this concept for basic education, not respiratory diagnosis.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
  },
  {
    id: "concept-alveolus",
    slug: "alveolus",
    name: "Alveolus",
    conceptType: "system_structure",
    bodySystem: "respiratory",
    description: "An alveolus is a small air space in the lung where gas exchange occurs with nearby capillaries. It gives respiratory physiology a microscopic structural anchor.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "air sac", termType: "common" }],
  },
  {
    id: "concept-pleura",
    slug: "pleura",
    name: "Pleura",
    conceptType: "system_structure",
    bodySystem: "respiratory",
    description: "The pleura is the membrane system associated with the lungs and thoracic cavity. It is included as a broad structure concept for respiratory and thoracic education.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
  },
  {
    id: "concept-ventilation",
    slug: "ventilation",
    name: "Ventilation",
    conceptType: "system_function",
    bodySystem: "respiratory",
    description: "Ventilation is the movement of air into and out of the lungs. This concept links diaphragm and rib-cage mechanics to respiratory physiology in a scope-aware way.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "breathing air movement", termType: "common" }],
  },
  {
    id: "concept-gas-exchange",
    slug: "gas-exchange",
    name: "Gas Exchange",
    conceptType: "system_function",
    bodySystem: "respiratory",
    description: "Gas exchange is the movement of oxygen and carbon dioxide between air spaces, blood, and tissues. It bridges respiratory and cardiovascular education without implying clinical interpretation.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
  },
  {
    id: "concept-inspiration",
    slug: "inspiration",
    name: "Inspiration",
    conceptType: "system_function",
    bodySystem: "respiratory",
    description: "Inspiration is the breathing phase that draws air into the lungs. It connects diaphragm contraction, rib elevation, thoracic volume change, and client-friendly breathing education.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "inhalation", termType: "common" }],
  },
  {
    id: "concept-expiration",
    slug: "expiration",
    name: "Expiration",
    conceptType: "system_function",
    bodySystem: "respiratory",
    description: "Expiration is the breathing phase that moves air out of the lungs. It supports education about relaxed breathing, forced breathing, rib motion, and abdominal participation.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "exhalation", termType: "common" }],
  },
  {
    id: "concept-oxygen-transport",
    slug: "oxygen-transport",
    name: "Oxygen Transport",
    conceptType: "system_function",
    bodySystem: "cardiorespiratory",
    description: "Oxygen transport is the movement of oxygen from the lungs through blood to body tissues. It is represented as a simple bridge concept between ventilation, gas exchange, and circulation.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
  },
  {
    id: "concept-lymphatic-vessel",
    slug: "lymphatic-vessel",
    name: "Lymphatic Vessel",
    conceptType: "system_structure",
    bodySystem: "lymphatic_immune",
    description: "A lymphatic vessel carries lymph through the lymphatic system. It gives the database a structure concept for fluid return, immune surveillance, and non-diagnostic lymphatic education.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
  },
  {
    id: "concept-lymphatic-capillary",
    slug: "lymphatic-capillary",
    name: "Lymphatic Capillary",
    conceptType: "system_structure",
    bodySystem: "lymphatic_immune",
    description: "A lymphatic capillary is a small lymphatic vessel that receives fluid from tissue spaces. It supports basic education about fluid movement without making drainage treatment claims.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
  },
  {
    id: "concept-lymphatic-duct",
    slug: "lymphatic-duct",
    name: "Lymphatic Duct",
    conceptType: "system_structure",
    bodySystem: "lymphatic_immune",
    description: "A lymphatic duct is a larger lymphatic pathway that returns lymph toward venous circulation. It helps connect lymphatic and cardiovascular system education.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
  },
  {
    id: "concept-spleen",
    slug: "spleen",
    name: "Spleen",
    conceptType: "system_structure",
    bodySystem: "lymphatic_immune",
    description: "The spleen is a lymphatic and immune organ involved with blood filtration and immune activity. It is included for body-system literacy rather than palpation or treatment guidance.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
  },
  {
    id: "concept-thymus",
    slug: "thymus",
    name: "Thymus",
    conceptType: "system_structure",
    bodySystem: "lymphatic_immune",
    description: "The thymus is an immune-related organ important in T cell maturation. It supports introductory immune-system education in the anatomy foundation.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
  },
  {
    id: "concept-tonsil",
    slug: "tonsil",
    name: "Tonsil",
    conceptType: "system_structure",
    bodySystem: "lymphatic_immune",
    description: "Tonsils are lymphatic tissue associated with the throat region and immune defense. They are included as high-level lymphatic structures for A&P coverage.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
  },
  {
    id: "concept-lymph-transport",
    slug: "lymph-transport",
    name: "Lymph Transport",
    conceptType: "system_function",
    bodySystem: "lymphatic_immune",
    description: "Lymph transport is the movement of lymph through lymphatic vessels toward venous circulation. It is modeled as general physiology, not as a claim about massage treatment effects.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "lymph flow", termType: "common" }],
  },
  {
    id: "concept-immune-surveillance",
    slug: "immune-surveillance",
    name: "Immune Surveillance",
    conceptType: "system_function",
    bodySystem: "lymphatic_immune",
    description: "Immune surveillance is the body's broad monitoring for abnormal or foreign material. It gives immune-system education a simple functional concept distinct from diagnosis.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
  },
  {
    id: "concept-fluid-return",
    slug: "fluid-return",
    name: "Fluid Return",
    conceptType: "system_function",
    bodySystem: "lymphatic_immune",
    description: "Fluid return describes movement of excess tissue fluid back toward the bloodstream through lymphatic and venous pathways. It connects lymphatic and cardiovascular concepts cautiously.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "tissue fluid return", termType: "common" }],
  },
]

function termSlug(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")
}

function conceptSeedRecord(concept: ConceptSpec): AnatomyConcept {
  return {
    id: concept.id,
    slug: concept.slug,
    name: concept.name,
    conceptType: concept.conceptType,
    bodySystem: concept.bodySystem,
    description: concept.description,
    sourceRef: concept.sourceRef,
  }
}

function conceptTerms(concept: ConceptSpec): AnatomyEntityTerm[] {
  return [
    {
      id: `term-${concept.slug}-preferred`,
      anatomyEntityType: "anatomy_concept",
      anatomyEntitySlug: concept.slug,
      term: concept.name,
      termType: "preferred",
      sourceRef: concept.sourceRef,
    },
    ...(concept.terms ?? []).map((term): AnatomyEntityTerm => ({
      id: `term-${concept.slug}-${term.termType}-${termSlug(term.term)}`,
      anatomyEntityType: "anatomy_concept",
      anatomyEntitySlug: concept.slug,
      term: term.term,
      termType: term.termType,
      notes: term.notes,
      sourceRef: term.sourceRef ?? concept.sourceRef,
    })),
  ]
}

function conceptCitation(concept: ConceptSpec): AnatomyCitation {
  return {
    id: `citation-concept-${concept.slug}-clinical-summary`,
    slug: `citation-concept-${concept.slug}-clinical-summary`,
    entityType: "anatomy_concept",
    entitySlug: concept.slug,
    factType: "clinical_summary",
    factSlug: `concept:${concept.slug}`,
    sourceRef: concept.sourceRef,
    sourceLocator: concept.locator,
    citationNote: "Reviewed commercial-compatible physiology support for MassageLab-authored cardiorespiratory and lymphatic concept summary. Do not copy source prose directly.",
    reviewStatus: "reviewed",
  }
}

export const CARDIORESPIRATORY_LYMPHATIC_CONCEPTS_SECTION: AnatomySeedSection = {
  concepts: CONCEPTS.map(conceptSeedRecord),
  entityTerms: CONCEPTS.flatMap(conceptTerms),
  citations: CONCEPTS.map(conceptCitation),
}
