import type { AnatomySeedSection } from "./sections.ts"

const SERVIER_SOURCE = "servier-medical-art"
const SERVIER_ATTRIBUTION = "Image provided by Servier Medical Art (https://smart.servier.com/), licensed under CC BY 4.0."
const SERVIER_LICENSE_URL = "https://creativecommons.org/licenses/by/4.0/"
const SERVIER_LICENSE_PAGE = "https://smart.servier.com/using-smart-images-what-you-can-do/"
const SERVIER_CITATION_PAGE = "https://smart.servier.com/how-to-cite-servier-medical-art/"

const bodySystemImages = [
  {
    slug: "servier-muscle-anatomy-2d-illustration",
    title: "Servier Muscle Anatomy 2D Illustration",
    description: "Reviewed Servier Medical Art 2D muscle and tendon illustration for musculoskeletal education, flashcards, and body-system browsing.",
    sourcePage: "https://smart.servier.com/smart_image/smart-muscle-overview/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/Muscle_3.png",
    storagePath: "anatomy/servier/2d/muscle-anatomy.png",
    entityType: "anatomy_concept",
    entitySlug: "musculoskeletal-system",
    entityLinks: [
      { entityType: "anatomy_concept", entitySlug: "musculoskeletal-system", role: "primary", notes: "Primary 2D education image for musculoskeletal tissue organization." },
      { entityType: "anatomy_concept", entitySlug: "skeletal-muscle-fiber", role: "reference", notes: "Skeletal muscle fiber and fascicle context." },
      { entityType: "anatomy_concept", entitySlug: "muscle-fascicle", role: "reference", notes: "Muscle fascicle organization context." },
    ],
  },
  {
    slug: "servier-bone-structure-2d-illustration",
    title: "Servier Bone Structure 2D Illustration",
    description: "Reviewed Servier Medical Art 2D bone structure illustration for skeletal tissue education and musculoskeletal browsing.",
    sourcePage: "https://smart.servier.com/smart_image/bone-structure/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/structure_osseuse_01.png",
    storagePath: "anatomy/servier/2d/bone-structure.png",
    entityType: "anatomy_concept",
    entitySlug: "musculoskeletal-system",
    entityLinks: [
      { entityType: "anatomy_concept", entitySlug: "musculoskeletal-system", role: "reference", notes: "Skeletal tissue detail for musculoskeletal education." },
    ],
  },
  {
    slug: "servier-artery-2d-illustration",
    title: "Servier Artery 2D Illustration",
    description: "Reviewed Servier Medical Art 2D artery illustration for cardiovascular education and vessel browsing.",
    sourcePage: "https://smart.servier.com/smart_image/arteries-blood-vessel-overview/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/vaisseau_24.png",
    storagePath: "anatomy/servier/2d/artery.png",
    entityType: "anatomy_structure",
    entitySlug: "artery",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "artery", role: "primary", notes: "Primary 2D education image for arterial anatomy." },
      { entityType: "anatomy_concept", entitySlug: "artery", role: "client_education", notes: "Client-friendly artery education image." },
      { entityType: "anatomy_concept", entitySlug: "cardiovascular-system", role: "region_context", notes: "Cardiovascular system context." },
    ],
  },
  {
    slug: "servier-arterial-wall-2d-illustration",
    title: "Servier Arterial Wall 2D Illustration",
    description: "Reviewed Servier Medical Art 2D arterial wall illustration for vessel-wall education and cardiovascular browsing.",
    sourcePage: "https://smart.servier.com/smart_image/artery-wall/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/Paroi_artere.png",
    storagePath: "anatomy/servier/2d/arterial-wall.png",
    entityType: "anatomy_structure",
    entitySlug: "artery",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "artery", role: "reference", notes: "Detailed 2D artery wall reference image." },
      { entityType: "anatomy_concept", entitySlug: "cardiovascular-system", role: "reference", notes: "Vessel-wall detail for cardiovascular education." },
    ],
  },
  {
    slug: "servier-venous-circulation-2d-illustration",
    title: "Servier Venous Circulation 2D Illustration",
    description: "Reviewed Servier Medical Art 2D venous circulation illustration for vessel education and massage-relevant circulation teaching.",
    sourcePage: "https://smart.servier.com/smart_image/vein/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/Circu_veineuse_1.png",
    storagePath: "anatomy/servier/2d/venous-circulation.png",
    entityType: "anatomy_structure",
    entitySlug: "vein",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "vein", role: "primary", notes: "Primary 2D education image for vein and valve function." },
      { entityType: "anatomy_concept", entitySlug: "vein", role: "client_education", notes: "Client-friendly vein education image." },
      { entityType: "anatomy_concept", entitySlug: "cardiovascular-system", role: "reference", notes: "Venous circulation context." },
    ],
  },
  {
    slug: "servier-lymph-node-2d-illustration",
    title: "Servier Lymph Node 2D Illustration",
    description: "Reviewed Servier Medical Art 2D lymph node illustration for lymphatic education and body-system browsing.",
    sourcePage: "https://smart.servier.com/smart_image/lymph-node/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/Ganglion_lympha_1.png",
    storagePath: "anatomy/servier/2d/lymph-node.png",
    entityType: "anatomy_structure",
    entitySlug: "lymph-node",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "lymph-node", role: "primary", notes: "Primary 2D education image for lymph node anatomy." },
      { entityType: "anatomy_concept", entitySlug: "lymph-node", role: "client_education", notes: "Client-friendly lymph node education image." },
      { entityType: "anatomy_concept", entitySlug: "lymphatic-system", role: "reference", notes: "Lymphatic system context." },
    ],
  },
  {
    slug: "servier-stomach-2d-illustration",
    title: "Servier Stomach 2D Illustration",
    description: "Reviewed Servier Medical Art 2D stomach illustration for digestive-system education and organ browsing.",
    sourcePage: "https://smart.servier.com/smart_image/stomach/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/coupe_estomac.png",
    storagePath: "anatomy/servier/2d/stomach.png",
    entityType: "anatomy_structure",
    entitySlug: "stomach",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "stomach", role: "primary", notes: "Primary 2D education image for stomach anatomy." },
      { entityType: "anatomy_concept", entitySlug: "stomach", role: "client_education", notes: "Client-friendly stomach education image." },
    ],
  },
  {
    slug: "servier-liver-2d-illustration",
    title: "Servier Liver 2D Illustration",
    description: "Reviewed Servier Medical Art 2D liver illustration for digestive and abdominal-organ education.",
    sourcePage: "https://smart.servier.com/smart_image/liver/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/foie.png",
    storagePath: "anatomy/servier/2d/liver.png",
    entityType: "anatomy_structure",
    entitySlug: "liver",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "liver", role: "primary", notes: "Primary 2D education image for liver anatomy." },
      { entityType: "anatomy_concept", entitySlug: "liver", role: "client_education", notes: "Client-friendly liver education image." },
    ],
  },
  {
    slug: "servier-pancreas-2d-illustration",
    title: "Servier Pancreas 2D Illustration",
    description: "Reviewed Servier Medical Art 2D pancreas illustration for digestive and endocrine organ education.",
    sourcePage: "https://smart.servier.com/smart_image/pancreas/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/coupe_pancreas.png",
    storagePath: "anatomy/servier/2d/pancreas.png",
    entityType: "anatomy_structure",
    entitySlug: "pancreas",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "pancreas", role: "primary", notes: "Primary 2D education image for pancreas anatomy." },
      { entityType: "anatomy_concept", entitySlug: "pancreas", role: "client_education", notes: "Client-friendly pancreas education image." },
    ],
  },
  {
    slug: "servier-intestine-2d-illustration",
    title: "Servier Intestine 2D Illustration",
    description: "Reviewed Servier Medical Art 2D intestine wall illustration for digestive-system education and organ browsing.",
    sourcePage: "https://smart.servier.com/smart_image/intestine/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/coupe_intestin.png",
    storagePath: "anatomy/servier/2d/intestine.png",
    entityType: "anatomy_structure",
    entitySlug: "small-intestine",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "small-intestine", role: "primary", notes: "Primary 2D intestine education image linked to small intestine anatomy." },
      { entityType: "anatomy_concept", entitySlug: "small-intestine", role: "client_education", notes: "Client-friendly small intestine education image." },
      { entityType: "anatomy_structure", entitySlug: "large-intestine", role: "reference", notes: "General intestine wall reference for digestive anatomy." },
    ],
  },
  {
    slug: "servier-kidney-2d-illustration",
    title: "Servier Kidney 2D Illustration",
    description: "Reviewed Servier Medical Art 2D kidney illustration for urinary-system education and organ browsing.",
    sourcePage: "https://smart.servier.com/smart_image/kidney/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/rein_01.png",
    storagePath: "anatomy/servier/2d/kidney.png",
    entityType: "anatomy_structure",
    entitySlug: "kidney",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "kidney", role: "primary", notes: "Primary 2D education image for kidney anatomy." },
      { entityType: "anatomy_concept", entitySlug: "kidney", role: "client_education", notes: "Client-friendly kidney education image." },
      { entityType: "anatomy_concept", entitySlug: "urinary-system", role: "region_context", notes: "Urinary system context." },
    ],
  },
  {
    slug: "servier-neuron-2d-illustration",
    title: "Servier Neuron 2D Illustration",
    description: "Reviewed Servier Medical Art 2D neuron illustration for nervous-system education and flashcards.",
    sourcePage: "https://smart.servier.com/smart_image/neuron-green-ov/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/neurone_06.png",
    storagePath: "anatomy/servier/2d/neuron.png",
    entityType: "anatomy_concept",
    entitySlug: "neuron",
    entityLinks: [
      { entityType: "anatomy_concept", entitySlug: "neuron", role: "primary", notes: "Primary 2D education image for neuron anatomy." },
      { entityType: "anatomy_concept", entitySlug: "nervous-system", role: "reference", notes: "Nervous system context." },
    ],
  },
  {
    slug: "servier-spinal-cord-section-2d-illustration",
    title: "Servier Spinal Cord Section 2D Illustration",
    description: "Reviewed Servier Medical Art 2D spinal cord section illustration for nervous-system education and anatomy browsing.",
    sourcePage: "https://smart.servier.com/smart_image/spinal-cord/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/moelle_C5.png",
    storagePath: "anatomy/servier/2d/spinal-cord-section.png",
    entityType: "anatomy_structure",
    entitySlug: "spinal-cord",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "spinal-cord", role: "primary", notes: "Primary 2D education image for spinal cord cross-section anatomy." },
      { entityType: "anatomy_concept", entitySlug: "spinal-cord", role: "client_education", notes: "Client-friendly spinal cord education image." },
      { entityType: "anatomy_concept", entitySlug: "nervous-system", role: "reference", notes: "Nervous system context." },
    ],
  },
] as const

export const MEDIA_SERVIER_BODY_SYSTEMS_SECTION = {
  mediaAssets: bodySystemImages.map((asset) => ({
    id: `media-${asset.slug}`,
    slug: asset.slug,
    title: asset.title,
    mediaType: "image",
    description: asset.description,
    sourceRef: SERVIER_SOURCE,
    sourceUrl: asset.sourceUrl,
    storagePath: asset.storagePath,
    license: "CC BY 4.0",
    licenseUrl: SERVIER_LICENSE_URL,
    attribution: SERVIER_ATTRIBUTION,
    author: "Servier Medical Art",
    usageScope: "open_reuse",
    reviewStatus: "reviewed",
    format: "png",
    metadata: {
      r2Upload: true,
      sourceKind: "servier-2d-education-image",
      sourcePage: asset.sourcePage,
      licenseVerifiedAt: "2026-05-26",
      licensePage: SERVIER_LICENSE_PAGE,
      citationPage: SERVIER_CITATION_PAGE,
      visualStyle: "2d-medical-illustration",
      ingestionStatus: "pending_r2_upload",
    },
  })),
  mediaEntityLinks: bodySystemImages.flatMap((asset) => asset.entityLinks.map((link) => ({
    id: `media-link-${asset.slug}-${link.entityType}-${link.entitySlug}-${link.role}`,
    assetSlug: asset.slug,
    entityType: link.entityType,
    entitySlug: link.entitySlug,
    role: link.role,
    notes: link.notes,
  }))),
  citations: bodySystemImages.flatMap((asset) => [
    {
      id: `citation-${asset.slug}-media-source`,
      slug: `citation-${asset.slug}-media-source`,
      entityType: asset.entityType,
      entitySlug: asset.entitySlug,
      factType: "media_source",
      factSlug: asset.slug,
      sourceRef: SERVIER_SOURCE,
      sourceLocator: asset.sourcePage,
      citationNote: "Servier Medical Art image page selected for 2D education media ingestion with stored direct image URL, license, attribution, and R2 upload path.",
      reviewStatus: "reviewed",
    },
    {
      id: `citation-${asset.slug}-media-license`,
      slug: `citation-${asset.slug}-media-license`,
      entityType: asset.entityType,
      entitySlug: asset.entitySlug,
      factType: "media_license",
      factSlug: asset.slug,
      sourceRef: SERVIER_SOURCE,
      sourceLocator: SERVIER_LICENSE_PAGE,
      citationNote: "Servier Medical Art states SMART images are available under CC BY 4.0 and provides attribution guidance for reuse.",
      reviewStatus: "reviewed",
    },
  ]),
} satisfies AnatomySeedSection
