import type { AnatomySeedSection } from "./sections.ts"

const SERVIER_SOURCE = "servier-medical-art"
const SERVIER_ATTRIBUTION = "Image provided by Servier Medical Art (https://smart.servier.com/), licensed under CC BY 4.0."
const SERVIER_LICENSE_URL = "https://creativecommons.org/licenses/by/4.0/"
const SERVIER_LICENSE_PAGE = "https://smart.servier.com/using-smart-images-what-you-can-do/"
const SERVIER_CITATION_PAGE = "https://smart.servier.com/how-to-cite-servier-medical-art/"

const bodyAtlasImages = [
  {
    slug: "servier-aorta-2d-illustration",
    title: "Servier Aorta 2D Illustration",
    description: "Reviewed Servier Medical Art 2D aorta illustration for cardiovascular-system education and major arterial pathway browsing.",
    sourcePage: "https://smart.servier.com/smart_image/aorta/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/aorte.png",
    storagePath: "anatomy/servier/2d/aorta.png",
    entityType: "anatomy_concept",
    entitySlug: "cardiovascular-system",
    entityLinks: [
      { entityType: "anatomy_concept", entitySlug: "cardiovascular-system", role: "primary", notes: "Major systemic arterial pathway image for cardiovascular education." },
      { entityType: "blood_supply", entitySlug: "aortic-arch", role: "reference", notes: "Aortic arch region shown in the full aorta illustration." },
      { entityType: "blood_supply", entitySlug: "thoracic-aorta", role: "reference", notes: "Thoracic aorta region shown in the full aorta illustration." },
      { entityType: "blood_supply", entitySlug: "abdominal-aorta", role: "reference", notes: "Abdominal aorta region shown in the full aorta illustration." },
    ],
  },
  {
    slug: "servier-aorta-anatomical-diagram-2d-illustration",
    title: "Servier Aorta Anatomical Diagram 2D Illustration",
    description: "Reviewed Servier Medical Art 2D aorta anatomical diagram for systemic circulation and aortic-region teaching.",
    sourcePage: "https://smart.servier.com/smart_image/aorta-anatomical-diagram/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/aorte2.png",
    storagePath: "anatomy/servier/2d/aorta-anatomical-diagram.png",
    entityType: "anatomy_concept",
    entitySlug: "systemic-circulation",
    entityLinks: [
      { entityType: "anatomy_concept", entitySlug: "systemic-circulation", role: "primary", notes: "Systemic circulation context for aortic anatomy." },
      { entityType: "blood_supply", entitySlug: "aortic-arch", role: "reference", notes: "Aortic arch reference image." },
      { entityType: "blood_supply", entitySlug: "thoracic-aorta", role: "reference", notes: "Thoracic aorta reference image." },
    ],
  },
  {
    slug: "servier-abdominal-aorta-2d-illustration",
    title: "Servier Abdominal Aorta 2D Illustration",
    description: "Reviewed Servier Medical Art 2D abdominal aorta illustration for abdominal vascular anatomy and body-system browsing.",
    sourcePage: "https://smart.servier.com/smart_image/abdominal-aorta/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/aorte_abdo.png",
    storagePath: "anatomy/servier/2d/abdominal-aorta.png",
    entityType: "blood_supply",
    entitySlug: "abdominal-aorta",
    entityLinks: [
      { entityType: "blood_supply", entitySlug: "abdominal-aorta", role: "primary", notes: "Primary 2D image for abdominal aorta browsing." },
      { entityType: "region", entitySlug: "abdomen", role: "region_context", notes: "Abdominal region vascular context." },
      { entityType: "anatomy_concept", entitySlug: "systemic-circulation", role: "reference", notes: "Systemic circulation reference for abdominal arterial flow." },
    ],
  },
  {
    slug: "servier-pulmonary-circulation-2d-illustration",
    title: "Servier Pulmonary Circulation 2D Illustration",
    description: "Reviewed Servier Medical Art 2D pulmonary circulation illustration for heart-lung circulation, gas exchange, and respiratory education.",
    sourcePage: "https://smart.servier.com/smart_image/pulmonary-circulation-ov/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/echanges_pulmonary_circulation.png",
    storagePath: "anatomy/servier/2d/pulmonary-circulation.png",
    entityType: "anatomy_concept",
    entitySlug: "pulmonary-circulation",
    entityLinks: [
      { entityType: "anatomy_concept", entitySlug: "pulmonary-circulation", role: "primary", notes: "Primary 2D image for pulmonary circulation education." },
      { entityType: "blood_supply", entitySlug: "pulmonary-arteries", role: "reference", notes: "Pulmonary artery pathway shown in the circulation diagram." },
      { entityType: "blood_supply", entitySlug: "pulmonary-veins", role: "reference", notes: "Pulmonary vein return pathway shown in the circulation diagram." },
      { entityType: "anatomy_concept", entitySlug: "gas-exchange", role: "client_education", notes: "Client-friendly gas exchange context." },
    ],
  },
  {
    slug: "servier-adult-cardiomyocytes-2d-illustration",
    title: "Servier Adult Cardiomyocytes 2D Illustration",
    description: "Reviewed Servier Medical Art 2D cardiomyocyte illustration for cardiac muscle and cardiovascular physiology education.",
    sourcePage: "https://smart.servier.com/smart_image/adult-cardiomyocyte-overview/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/cardiomyocyte_10.png",
    storagePath: "anatomy/servier/2d/adult-cardiomyocytes.png",
    entityType: "anatomy_structure",
    entitySlug: "heart",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "heart", role: "primary", notes: "Cellular-level cardiac muscle context linked to heart anatomy." },
      { entityType: "anatomy_concept", entitySlug: "heart", role: "reference", notes: "Heart physiology education context." },
      { entityType: "anatomy_concept", entitySlug: "cardiovascular-system", role: "reference", notes: "Cardiovascular system teaching context." },
    ],
  },
  {
    slug: "servier-brain-arteries-2d-illustration",
    title: "Servier Brain Arteries 2D Illustration",
    description: "Reviewed Servier Medical Art 2D brain artery illustration for cranial circulation and head-neck vascular education.",
    sourcePage: "https://smart.servier.com/smart_image/brain-arteries/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/Arteres_cerveau.png",
    storagePath: "anatomy/servier/2d/brain-arteries.png",
    entityType: "anatomy_structure",
    entitySlug: "brain",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "brain", role: "primary", notes: "Brain vascular context for nervous-system browsing." },
      { entityType: "blood_supply", entitySlug: "internal-carotid-artery", role: "reference", notes: "Anterior cranial inflow context." },
      { entityType: "blood_supply", entitySlug: "vertebral-artery", role: "reference", notes: "Posterior cranial inflow context." },
      { entityType: "region", entitySlug: "head", role: "region_context", notes: "Head-region vascular orientation image." },
    ],
  },
  {
    slug: "servier-brain-circulation-2d-illustration",
    title: "Servier Brain Circulation 2D Illustration",
    description: "Reviewed Servier Medical Art 2D brain circulation illustration for head vascular anatomy and nervous-system education.",
    sourcePage: "https://smart.servier.com/smart_image/smart-brain-circulation/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/Circu_cerebrale2.png",
    storagePath: "anatomy/servier/2d/brain-circulation.png",
    entityType: "anatomy_structure",
    entitySlug: "brain",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "brain", role: "primary", notes: "Brain circulation context for nervous-system browsing." },
      { entityType: "anatomy_concept", entitySlug: "nervous-system", role: "reference", notes: "Nervous-system circulation context." },
      { entityType: "blood_supply", entitySlug: "internal-carotid-artery", role: "reference", notes: "Internal carotid contribution context." },
    ],
  },
  {
    slug: "servier-brain-sagittal-2d-illustration",
    title: "Servier Brain Sagittal 2D Illustration",
    description: "Reviewed Servier Medical Art 2D sagittal brain illustration for central nervous-system and cranial anatomy education.",
    sourcePage: "https://smart.servier.com/smart_image/brain-sagittal/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/cerveau_06.png",
    storagePath: "anatomy/servier/2d/brain-sagittal.png",
    entityType: "anatomy_structure",
    entitySlug: "brain",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "brain", role: "primary", notes: "Sagittal brain reference image for central nervous-system education." },
      { entityType: "anatomy_structure", entitySlug: "brainstem", role: "reference", notes: "Brainstem context in the sagittal view." },
      { entityType: "anatomy_concept", entitySlug: "nervous-system", role: "client_education", notes: "Client-friendly nervous-system image." },
    ],
  },
  {
    slug: "servier-respiratory-conducting-zone-2d-illustration",
    title: "Servier Respiratory Conducting Zone 2D Illustration",
    description: "Reviewed Servier Medical Art 2D conducting-zone illustration for airway anatomy and respiratory-system education.",
    sourcePage: "https://smart.servier.com/smart_image/conducting-zone/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2024/01/Conducting-Zone.png",
    storagePath: "anatomy/servier/2d/respiratory-conducting-zone.png",
    entityType: "anatomy_concept",
    entitySlug: "respiratory-system",
    entityLinks: [
      { entityType: "anatomy_concept", entitySlug: "respiratory-system", role: "primary", notes: "Airway conducting-zone overview for respiratory-system education." },
      { entityType: "anatomy_structure", entitySlug: "trachea", role: "reference", notes: "Tracheal airway context." },
      { entityType: "anatomy_structure", entitySlug: "bronchus", role: "reference", notes: "Bronchial airway context." },
      { entityType: "anatomy_structure", entitySlug: "lung", role: "region_context", notes: "Lung airway context." },
    ],
  },
  {
    slug: "servier-lung-lobes-2d-illustration",
    title: "Servier Lung Lobes 2D Illustration",
    description: "Reviewed Servier Medical Art 2D lung lobes illustration for respiratory organ and thoracic education.",
    sourcePage: "https://smart.servier.com/smart_image/lungs-lobes/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/poumon_02.png",
    storagePath: "anatomy/servier/2d/lung-lobes.png",
    entityType: "anatomy_structure",
    entitySlug: "lung-lobe",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "lung-lobe", role: "primary", notes: "Primary 2D image for lung lobe anatomy." },
      { entityType: "anatomy_structure", entitySlug: "lung", role: "reference", notes: "Whole lung anatomy context." },
      { entityType: "region", entitySlug: "thorax", role: "region_context", notes: "Thoracic respiratory orientation image." },
    ],
  },
  {
    slug: "servier-lung-lobes-cross-section-2d-illustration",
    title: "Servier Lung Lobes Cross-Section 2D Illustration",
    description: "Reviewed Servier Medical Art 2D cross-sectional lung lobes illustration for thoracic and pulmonary education.",
    sourcePage: "https://smart.servier.com/smart_image/cross-sectional-lungs-lobes/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/poumon_06.png",
    storagePath: "anatomy/servier/2d/lung-lobes-cross-section.png",
    entityType: "anatomy_structure",
    entitySlug: "lung-lobe",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "lung-lobe", role: "primary", notes: "Cross-sectional lung lobe reference image." },
      { entityType: "anatomy_structure", entitySlug: "lung", role: "reference", notes: "Lung structure context." },
    ],
  },
  {
    slug: "servier-larynx-front-view-2d-illustration",
    title: "Servier Larynx Front View 2D Illustration",
    description: "Reviewed Servier Medical Art 2D anterior larynx illustration for airway, voice box, and anterior neck education.",
    sourcePage: "https://smart.servier.com/smart_image/larynx-front-view/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/Larynx.png",
    storagePath: "anatomy/servier/2d/larynx-front-view.png",
    entityType: "anatomy_structure",
    entitySlug: "larynx",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "larynx", role: "primary", notes: "Primary anterior larynx anatomy image." },
      { entityType: "anatomy_structure", entitySlug: "thyroid-cartilage", role: "reference", notes: "Laryngeal cartilage context." },
      { entityType: "region", entitySlug: "neck", role: "region_context", notes: "Anterior neck airway context." },
    ],
  },
  {
    slug: "servier-larynx-front-cut-2d-illustration",
    title: "Servier Larynx Front Cut 2D Illustration",
    description: "Reviewed Servier Medical Art 2D cutaway larynx illustration for airway and laryngeal structure education.",
    sourcePage: "https://smart.servier.com/smart_image/larynx-front-cut/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2023/05/larynx-front-cut.png",
    storagePath: "anatomy/servier/2d/larynx-front-cut.png",
    entityType: "anatomy_structure",
    entitySlug: "larynx",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "larynx", role: "primary", notes: "Cutaway larynx anatomy image." },
      { entityType: "anatomy_concept", entitySlug: "respiratory-system", role: "reference", notes: "Respiratory-system airway context." },
    ],
  },
  {
    slug: "servier-complete-digestive-apparatus-2d-illustration",
    title: "Servier Complete Digestive Apparatus 2D Illustration",
    description: "Reviewed Servier Medical Art 2D digestive apparatus illustration for gastrointestinal-system education and abdominal browsing.",
    sourcePage: "https://smart.servier.com/smart_image/complete-digestive-apparatus/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/syst_dig_complet.png",
    storagePath: "anatomy/servier/2d/complete-digestive-apparatus.png",
    entityType: "anatomy_concept",
    entitySlug: "digestive-system",
    entityLinks: [
      { entityType: "anatomy_concept", entitySlug: "digestive-system", role: "primary", notes: "Primary digestive-system education image." },
      { entityType: "anatomy_concept", entitySlug: "gastrointestinal-tract", role: "reference", notes: "GI tract pathway context." },
      { entityType: "anatomy_structure", entitySlug: "oral-cavity", role: "reference", notes: "Oral cavity starting point of digestive tract." },
      { entityType: "anatomy_structure", entitySlug: "stomach", role: "reference", notes: "Stomach context in digestive apparatus." },
      { entityType: "anatomy_structure", entitySlug: "small-intestine", role: "reference", notes: "Small intestine context in digestive apparatus." },
      { entityType: "anatomy_structure", entitySlug: "large-intestine", role: "reference", notes: "Large intestine context in digestive apparatus." },
    ],
  },
  {
    slug: "servier-adult-teeth-2d-illustration",
    title: "Servier Adult Teeth 2D Illustration",
    description: "Reviewed Servier Medical Art 2D adult teeth illustration for oral cavity, jaw, and tooth anatomy education.",
    sourcePage: "https://smart.servier.com/smart_image/adult-teeth/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/Dents_adultes01.png",
    storagePath: "anatomy/servier/2d/adult-teeth.png",
    entityType: "anatomy_structure",
    entitySlug: "tooth",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "tooth", role: "primary", notes: "Primary 2D adult dentition image." },
      { entityType: "anatomy_structure", entitySlug: "upper-teeth", role: "reference", notes: "Upper teeth context." },
      { entityType: "anatomy_structure", entitySlug: "lower-teeth", role: "reference", notes: "Lower teeth context." },
      { entityType: "region", entitySlug: "jaw", role: "region_context", notes: "Jaw and oral anatomy context." },
    ],
  },
  {
    slug: "servier-colon-2d-illustration",
    title: "Servier Colon 2D Illustration",
    description: "Reviewed Servier Medical Art 2D colon illustration for large intestine and digestive-system education.",
    sourcePage: "https://smart.servier.com/smart_image/colon/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/colon.png",
    storagePath: "anatomy/servier/2d/colon.png",
    entityType: "anatomy_structure",
    entitySlug: "large-intestine",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "large-intestine", role: "primary", notes: "Primary 2D colon image for large intestine education." },
      { entityType: "anatomy_concept", entitySlug: "digestive-system", role: "reference", notes: "Digestive-system context." },
      { entityType: "region", entitySlug: "abdomen", role: "region_context", notes: "Abdominal body-map context." },
    ],
  },
  {
    slug: "servier-duodenum-2d-illustration",
    title: "Servier Duodenum 2D Illustration",
    description: "Reviewed Servier Medical Art 2D duodenum illustration for small intestine and upper abdominal digestive education.",
    sourcePage: "https://smart.servier.com/smart_image/duodenum-overview/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/duodenum.png",
    storagePath: "anatomy/servier/2d/duodenum.png",
    entityType: "anatomy_structure",
    entitySlug: "small-intestine",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "small-intestine", role: "primary", notes: "Duodenum view linked to small intestine browsing." },
      { entityType: "anatomy_structure", entitySlug: "pancreas", role: "reference", notes: "Upper abdominal accessory organ context." },
      { entityType: "anatomy_concept", entitySlug: "digestive-system", role: "reference", notes: "Digestive-system context." },
    ],
  },
  {
    slug: "servier-bile-secretion-2d-illustration",
    title: "Servier Bile Secretion 2D Illustration",
    description: "Reviewed Servier Medical Art 2D bile secretion illustration for liver, gallbladder, and digestive physiology education.",
    sourcePage: "https://smart.servier.com/smart_image/smart-bile-secretion/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/secretion_biliaire.png",
    storagePath: "anatomy/servier/2d/bile-secretion.png",
    entityType: "anatomy_concept",
    entitySlug: "bile",
    entityLinks: [
      { entityType: "anatomy_concept", entitySlug: "bile", role: "primary", notes: "Bile secretion pathway image for digestive physiology education." },
      { entityType: "anatomy_structure", entitySlug: "gallbladder", role: "reference", notes: "Gallbladder context in bile storage and release." },
      { entityType: "anatomy_structure", entitySlug: "liver", role: "reference", notes: "Liver context in bile production." },
      { entityType: "anatomy_structure", entitySlug: "small-intestine", role: "reference", notes: "Small intestine context in bile release." },
    ],
  },
  {
    slug: "servier-urinary-bladder-2d-illustration",
    title: "Servier Urinary Bladder 2D Illustration",
    description: "Reviewed Servier Medical Art 2D bladder illustration for urinary-system and pelvic organ education.",
    sourcePage: "https://smart.servier.com/smart_image/bladder/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/vessie.png",
    storagePath: "anatomy/servier/2d/urinary-bladder.png",
    entityType: "anatomy_structure",
    entitySlug: "urinary-bladder",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "urinary-bladder", role: "primary", notes: "Primary 2D urinary bladder anatomy image." },
      { entityType: "anatomy_concept", entitySlug: "urinary-system", role: "reference", notes: "Urinary-system education context." },
      { entityType: "region", entitySlug: "pelvis", role: "region_context", notes: "Pelvic organ body-map context." },
    ],
  },
  {
    slug: "servier-urinary-tract-2d-illustration",
    title: "Servier Urinary Tract 2D Illustration",
    description: "Reviewed Servier Medical Art 2D urinary tract illustration for kidney, ureter, bladder, and urinary-system education.",
    sourcePage: "https://smart.servier.com/smart_image/urinary-tract/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/App_urinaire_femme.png",
    storagePath: "anatomy/servier/2d/urinary-tract.png",
    entityType: "anatomy_concept",
    entitySlug: "urinary-system",
    entityLinks: [
      { entityType: "anatomy_concept", entitySlug: "urinary-system", role: "primary", notes: "Primary 2D urinary-system overview image." },
      { entityType: "anatomy_structure", entitySlug: "kidney", role: "reference", notes: "Kidney context in urinary tract." },
      { entityType: "anatomy_structure", entitySlug: "urinary-bladder", role: "reference", notes: "Bladder context in urinary tract." },
      { entityType: "region", entitySlug: "pelvis", role: "region_context", notes: "Pelvic urinary-system context." },
    ],
  },
  {
    slug: "servier-nephron-overview-2d-illustration",
    title: "Servier Nephron Overview 2D Illustration",
    description: "Reviewed Servier Medical Art 2D nephron illustration for kidney filtration and urinary physiology education.",
    sourcePage: "https://smart.servier.com/smart_image/nephron/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/nephron_01.png",
    storagePath: "anatomy/servier/2d/nephron-overview.png",
    entityType: "anatomy_structure",
    entitySlug: "nephron",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "nephron", role: "primary", notes: "Primary 2D nephron anatomy image." },
      { entityType: "anatomy_concept", entitySlug: "nephron", role: "reference", notes: "Nephron physiology concept context." },
      { entityType: "anatomy_structure", entitySlug: "kidney", role: "reference", notes: "Kidney structure context." },
    ],
  },
  {
    slug: "servier-kidney-overview-2d-illustration",
    title: "Servier Kidney Overview 2D Illustration",
    description: "Reviewed Servier Medical Art 2D kidney overview illustration for urinary organ education and abdominal anatomy browsing.",
    sourcePage: "https://smart.servier.com/smart_image/smart-kidney-ov/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/Rein_beau.png",
    storagePath: "anatomy/servier/2d/kidney-overview.png",
    entityType: "anatomy_structure",
    entitySlug: "kidney",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "kidney", role: "primary", notes: "Kidney overview image complementing the existing kidney cross-section." },
      { entityType: "anatomy_concept", entitySlug: "urinary-system", role: "reference", notes: "Urinary-system organ context." },
      { entityType: "region", entitySlug: "abdomen", role: "region_context", notes: "Abdominal organ context." },
    ],
  },
  {
    slug: "servier-thyroid-gland-2d-illustration",
    title: "Servier Thyroid Gland 2D Illustration",
    description: "Reviewed Servier Medical Art 2D thyroid gland illustration for anterior neck and endocrine-system education.",
    sourcePage: "https://smart.servier.com/smart_image/normal-thyroid/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/Thyroide_normale.png",
    storagePath: "anatomy/servier/2d/thyroid-gland.png",
    entityType: "anatomy_structure",
    entitySlug: "thyroid-gland",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "thyroid-gland", role: "primary", notes: "Primary 2D thyroid gland image." },
      { entityType: "anatomy_concept", entitySlug: "endocrine-system", role: "reference", notes: "Endocrine-system context." },
      { entityType: "region", entitySlug: "neck", role: "region_context", notes: "Anterior neck body-map context." },
    ],
  },
  {
    slug: "servier-adrenal-gland-vessels-2d-illustration",
    title: "Servier Adrenal Gland Vessels 2D Illustration",
    description: "Reviewed Servier Medical Art 2D adrenal gland vessels illustration for endocrine anatomy and abdominal organ browsing.",
    sourcePage: "https://smart.servier.com/smart_image/adrenal-gland-overview/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/Adrenal-Gland-Vessels.png",
    storagePath: "anatomy/servier/2d/adrenal-gland-vessels.png",
    entityType: "anatomy_structure",
    entitySlug: "adrenal-gland",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "adrenal-gland", role: "primary", notes: "Primary 2D adrenal gland vessel image." },
      { entityType: "anatomy_concept", entitySlug: "adrenal-gland", role: "reference", notes: "Adrenal gland physiology concept context." },
      { entityType: "anatomy_concept", entitySlug: "endocrine-system", role: "reference", notes: "Endocrine-system context." },
    ],
  },
  {
    slug: "servier-adrenal-gland-section-2d-illustration",
    title: "Servier Adrenal Gland Section 2D Illustration",
    description: "Reviewed Servier Medical Art 2D adrenal gland section illustration for endocrine gland structure education.",
    sourcePage: "https://smart.servier.com/smart_image/adrenal-mid-sagittal/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/Adrenal-gland.png",
    storagePath: "anatomy/servier/2d/adrenal-gland-section.png",
    entityType: "anatomy_structure",
    entitySlug: "adrenal-gland",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "adrenal-gland", role: "primary", notes: "Adrenal gland section image for endocrine education." },
      { entityType: "anatomy_concept", entitySlug: "endocrine-system", role: "reference", notes: "Endocrine-system context." },
    ],
  },
  {
    slug: "servier-pancreas-overview-2d-illustration",
    title: "Servier Pancreas Overview 2D Illustration",
    description: "Reviewed Servier Medical Art 2D pancreas overview illustration for digestive and endocrine anatomy education.",
    sourcePage: "https://smart.servier.com/smart_image/pancreas-overview/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/pancreas_01.png",
    storagePath: "anatomy/servier/2d/pancreas-overview.png",
    entityType: "anatomy_structure",
    entitySlug: "pancreas",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "pancreas", role: "primary", notes: "Pancreas overview image complementing existing pancreas section media." },
      { entityType: "anatomy_concept", entitySlug: "pancreas", role: "reference", notes: "Digestive/endocrine pancreas concept context." },
      { entityType: "anatomy_concept", entitySlug: "digestive-system", role: "reference", notes: "Digestive-system context." },
    ],
  },
  {
    slug: "servier-breast-sagittal-2d-illustration",
    title: "Servier Breast Sagittal 2D Illustration",
    description: "Reviewed Servier Medical Art 2D sagittal breast illustration for mammary gland and thoracic anatomy education.",
    sourcePage: "https://smart.servier.com/smart_image/breast-sagittal/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/Sein_02.png",
    storagePath: "anatomy/servier/2d/breast-sagittal.png",
    entityType: "anatomy_structure",
    entitySlug: "mammary-gland",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "mammary-gland", role: "primary", notes: "Primary 2D mammary gland anatomy image." },
      { entityType: "region", entitySlug: "thorax", role: "region_context", notes: "Thoracic body-map context." },
      { entityType: "anatomy_concept", entitySlug: "reproductive-system", role: "reference", notes: "Reproductive-system anatomy context." },
    ],
  },
  {
    slug: "servier-female-genital-apparatus-2d-illustration",
    title: "Servier Female Genital Apparatus 2D Illustration",
    description: "Reviewed Servier Medical Art 2D female reproductive apparatus illustration for pelvic and reproductive-system education.",
    sourcePage: "https://smart.servier.com/smart_image/genital-apparatus/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/app_fem.png",
    storagePath: "anatomy/servier/2d/female-genital-apparatus.png",
    entityType: "anatomy_concept",
    entitySlug: "reproductive-system",
    entityLinks: [
      { entityType: "anatomy_concept", entitySlug: "reproductive-system", role: "primary", notes: "Female pelvic reproductive-system overview image." },
      { entityType: "anatomy_structure", entitySlug: "uterus", role: "reference", notes: "Uterus context in the reproductive apparatus." },
      { entityType: "anatomy_structure", entitySlug: "ovary", role: "reference", notes: "Ovary context in the reproductive apparatus." },
      { entityType: "region", entitySlug: "pelvis", role: "region_context", notes: "Pelvic body-map context." },
    ],
  },
  {
    slug: "servier-ovary-overview-2d-illustration",
    title: "Servier Ovary Overview 2D Illustration",
    description: "Reviewed Servier Medical Art 2D ovary overview illustration for reproductive and endocrine organ education.",
    sourcePage: "https://smart.servier.com/smart_image/smart-ovary-overview/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/ovaire_2e.png",
    storagePath: "anatomy/servier/2d/ovary-overview.png",
    entityType: "anatomy_structure",
    entitySlug: "ovary",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "ovary", role: "primary", notes: "Primary 2D ovary overview image." },
      { entityType: "anatomy_concept", entitySlug: "ovary", role: "reference", notes: "Ovary concept context." },
      { entityType: "anatomy_concept", entitySlug: "reproductive-system", role: "reference", notes: "Reproductive-system context." },
    ],
  },
  {
    slug: "servier-male-genital-apparatus-2d-illustration",
    title: "Servier Male Genital Apparatus 2D Illustration",
    description: "Reviewed Servier Medical Art 2D male reproductive apparatus illustration for pelvic and reproductive-system education.",
    sourcePage: "https://smart.servier.com/smart_image/penis/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/app_masc.png",
    storagePath: "anatomy/servier/2d/male-genital-apparatus.png",
    entityType: "anatomy_concept",
    entitySlug: "reproductive-system",
    entityLinks: [
      { entityType: "anatomy_concept", entitySlug: "reproductive-system", role: "primary", notes: "Male pelvic reproductive-system overview image." },
      { entityType: "anatomy_structure", entitySlug: "penis", role: "reference", notes: "Penis context in reproductive apparatus." },
      { entityType: "anatomy_structure", entitySlug: "testis", role: "reference", notes: "Testis context in reproductive apparatus." },
      { entityType: "region", entitySlug: "pelvis", role: "region_context", notes: "Pelvic body-map context." },
    ],
  },
  {
    slug: "servier-adult-human-body-2d-illustration",
    title: "Servier Adult Human Body 2D Illustration",
    description: "Reviewed Servier Medical Art 2D adult human body illustration for whole-body orientation, body maps, and education prompts.",
    sourcePage: "https://smart.servier.com/smart_image/adult-human/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/Adulte03.png",
    storagePath: "anatomy/servier/2d/adult-human-body.png",
    entityType: "region",
    entitySlug: "trunk-spine-pelvis",
    entityLinks: [
      { entityType: "region", entitySlug: "trunk-spine-pelvis", role: "primary", notes: "Whole-body orientation image centered on trunk and limb body-map context." },
      { entityType: "region", entitySlug: "head", role: "region_context", notes: "Head body-map context." },
      { entityType: "region", entitySlug: "upper-limb", role: "region_context", notes: "Upper limb body-map context." },
      { entityType: "region", entitySlug: "lower-limb", role: "region_context", notes: "Lower limb body-map context." },
    ],
  },
  {
    slug: "servier-arm-bones-2d-illustration",
    title: "Servier Arm Bones 2D Illustration",
    description: "Reviewed Servier Medical Art 2D arm bone illustration for upper-limb orientation and skeletal education.",
    sourcePage: "https://smart.servier.com/smart_image/arm-bones/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/bras_01.png",
    storagePath: "anatomy/servier/2d/arm-bones.png",
    entityType: "region",
    entitySlug: "upper-limb",
    entityLinks: [
      { entityType: "region", entitySlug: "upper-limb", role: "primary", notes: "Primary 2D upper-limb skeletal orientation image." },
      { entityType: "region", entitySlug: "arm", role: "region_context", notes: "Arm body-map context." },
      { entityType: "bone", entitySlug: "humerus", role: "reference", notes: "Arm bone context." },
      { entityType: "bone", entitySlug: "radius", role: "reference", notes: "Forearm bone context." },
      { entityType: "bone", entitySlug: "ulna", role: "reference", notes: "Forearm bone context." },
    ],
  },
  {
    slug: "servier-bone-mass-2d-illustration",
    title: "Servier Bone Mass 2D Illustration",
    description: "Reviewed Servier Medical Art 2D bone mass illustration for skeletal tissue and musculoskeletal education.",
    sourcePage: "https://smart.servier.com/smart_image/bone-mass/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/Bone_mass1.png",
    storagePath: "anatomy/servier/2d/bone-mass.png",
    entityType: "anatomy_concept",
    entitySlug: "musculoskeletal-system",
    entityLinks: [
      { entityType: "anatomy_concept", entitySlug: "musculoskeletal-system", role: "primary", notes: "Skeletal tissue education image for musculoskeletal-system browsing." },
      { entityType: "anatomy_structure", entitySlug: "bone-marrow", role: "reference", notes: "Bone interior context for skeletal tissue education." },
    ],
  },
  {
    slug: "servier-mouth-2d-illustration",
    title: "Servier Mouth 2D Illustration",
    description: "Reviewed Servier Medical Art 2D mouth illustration for oral cavity, jaw, and digestive-entry anatomy education.",
    sourcePage: "https://smart.servier.com/smart_image/mouth/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/bouche.png",
    storagePath: "anatomy/servier/2d/mouth.png",
    entityType: "anatomy_structure",
    entitySlug: "oral-cavity",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "oral-cavity", role: "primary", notes: "Primary 2D mouth/oral cavity education image." },
      { entityType: "anatomy_concept", entitySlug: "mouth", role: "reference", notes: "Mouth concept context for digestive-system education." },
      { entityType: "region", entitySlug: "jaw", role: "region_context", notes: "Jaw and oral-region context." },
    ],
  },
  {
    slug: "servier-right-lung-lobes-2d-illustration",
    title: "Servier Right Lung Lobes 2D Illustration",
    description: "Reviewed Servier Medical Art 2D right lung lobes illustration for lung-lobe and thoracic anatomy education.",
    sourcePage: "https://smart.servier.com/smart_image/right-lungs/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/poumon_09.png",
    storagePath: "anatomy/servier/2d/right-lung-lobes.png",
    entityType: "anatomy_structure",
    entitySlug: "lung-lobe",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "lung-lobe", role: "primary", notes: "Right lung lobe orientation image." },
      { entityType: "anatomy_structure", entitySlug: "lung", role: "reference", notes: "Whole lung structure context." },
      { entityType: "region", entitySlug: "thorax", role: "region_context", notes: "Thoracic respiratory context." },
    ],
  },
  {
    slug: "servier-left-lung-lobes-2d-illustration",
    title: "Servier Left Lung Lobes 2D Illustration",
    description: "Reviewed Servier Medical Art 2D left lung lobes illustration for lung-lobe and thoracic anatomy education.",
    sourcePage: "https://smart.servier.com/smart_image/left-lungs-lobes/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/poumon_04.png",
    storagePath: "anatomy/servier/2d/left-lung-lobes.png",
    entityType: "anatomy_structure",
    entitySlug: "lung-lobe",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "lung-lobe", role: "primary", notes: "Left lung lobe orientation image." },
      { entityType: "anatomy_structure", entitySlug: "lung", role: "reference", notes: "Whole lung structure context." },
      { entityType: "region", entitySlug: "thorax", role: "region_context", notes: "Thoracic respiratory context." },
    ],
  },
  {
    slug: "servier-intrapulmonary-airways-2d-illustration",
    title: "Servier Intrapulmonary Airways 2D Illustration",
    description: "Reviewed Servier Medical Art 2D intrapulmonary airway illustration for bronchial tree and respiratory anatomy education.",
    sourcePage: "https://smart.servier.com/smart_image/intrapulmonary-airways/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/poumon_07.png",
    storagePath: "anatomy/servier/2d/intrapulmonary-airways.png",
    entityType: "anatomy_structure",
    entitySlug: "bronchus",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "bronchus", role: "primary", notes: "Primary intrapulmonary airway image for bronchial anatomy." },
      { entityType: "anatomy_structure", entitySlug: "lung", role: "reference", notes: "Lung structure context." },
      { entityType: "anatomy_concept", entitySlug: "respiratory-system", role: "reference", notes: "Respiratory-system context." },
    ],
  },
  {
    slug: "servier-intrapulmonary-airways-lungs-2d-illustration",
    title: "Servier Intrapulmonary Airways and Lungs 2D Illustration",
    description: "Reviewed Servier Medical Art 2D intrapulmonary airways and lungs illustration for respiratory tree education.",
    sourcePage: "https://smart.servier.com/smart_image/intrapulmonary-airways-lungs/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/poumon_10.png",
    storagePath: "anatomy/servier/2d/intrapulmonary-airways-lungs.png",
    entityType: "anatomy_structure",
    entitySlug: "lung",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "lung", role: "primary", notes: "Whole lung image with intrapulmonary airway context." },
      { entityType: "anatomy_structure", entitySlug: "bronchus", role: "reference", notes: "Bronchial branching context." },
      { entityType: "anatomy_concept", entitySlug: "respiratory-system", role: "reference", notes: "Respiratory-system context." },
    ],
  },
  {
    slug: "servier-nephron-detail-2d-illustration",
    title: "Servier Nephron Detail 2D Illustration",
    description: "Reviewed Servier Medical Art 2D nephron detail illustration for kidney filtration and urinary physiology education.",
    sourcePage: "https://smart.servier.com/smart_image/smart-nephron/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/nephron_02.png",
    storagePath: "anatomy/servier/2d/nephron-detail.png",
    entityType: "anatomy_structure",
    entitySlug: "nephron",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "nephron", role: "primary", notes: "Detailed nephron image for urinary-system education." },
      { entityType: "anatomy_structure", entitySlug: "kidney", role: "reference", notes: "Kidney structure context." },
      { entityType: "anatomy_concept", entitySlug: "urinary-system", role: "reference", notes: "Urinary-system context." },
    ],
  },
  {
    slug: "servier-islet-of-langerhans-2d-illustration",
    title: "Servier Islet of Langerhans 2D Illustration",
    description: "Reviewed Servier Medical Art 2D pancreatic islet illustration for pancreas and endocrine-system education.",
    sourcePage: "https://smart.servier.com/smart_image/smart-islet-of-langerhans/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/langherans2.png",
    storagePath: "anatomy/servier/2d/islet-of-langerhans.png",
    entityType: "anatomy_structure",
    entitySlug: "pancreas",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "pancreas", role: "primary", notes: "Pancreatic endocrine tissue context linked to pancreas browsing." },
      { entityType: "anatomy_concept", entitySlug: "pancreas", role: "reference", notes: "Pancreas digestive/endocrine concept context." },
      { entityType: "anatomy_concept", entitySlug: "endocrine-system", role: "reference", notes: "Endocrine-system context." },
    ],
  },
  {
    slug: "servier-breast-overview-2d-illustration",
    title: "Servier Breast Overview 2D Illustration",
    description: "Reviewed Servier Medical Art 2D breast overview illustration for mammary gland and thoracic anatomy education.",
    sourcePage: "https://smart.servier.com/smart_image/breast/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/Sein_01.png",
    storagePath: "anatomy/servier/2d/breast-overview.png",
    entityType: "anatomy_structure",
    entitySlug: "mammary-gland",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "mammary-gland", role: "primary", notes: "Breast overview image for mammary gland education." },
      { entityType: "region", entitySlug: "thorax", role: "region_context", notes: "Thoracic region context." },
      { entityType: "anatomy_concept", entitySlug: "reproductive-system", role: "reference", notes: "Reproductive-system context." },
    ],
  },
  {
    slug: "servier-pancreas-coronal-2d-illustration",
    title: "Servier Pancreas Coronal 2D Illustration",
    description: "Reviewed Servier Medical Art 2D pancreas coronal illustration for digestive/endocrine organ education.",
    sourcePage: "https://smart.servier.com/smart_image/pancreas-coronal/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/pancreas_coupe.png",
    storagePath: "anatomy/servier/2d/pancreas-coronal.png",
    entityType: "anatomy_structure",
    entitySlug: "pancreas",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "pancreas", role: "primary", notes: "Coronal pancreas image for organ-level education." },
      { entityType: "anatomy_concept", entitySlug: "pancreas", role: "reference", notes: "Pancreas concept context." },
      { entityType: "anatomy_concept", entitySlug: "digestive-system", role: "reference", notes: "Digestive-system context." },
    ],
  },
  {
    slug: "servier-ovary-cycle-2d-illustration",
    title: "Servier Ovary Cycle 2D Illustration",
    description: "Reviewed Servier Medical Art 2D ovary cycle illustration for reproductive physiology education.",
    sourcePage: "https://smart.servier.com/smart_image/ovary/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/ovaire_1.png",
    storagePath: "anatomy/servier/2d/ovary-cycle.png",
    entityType: "anatomy_structure",
    entitySlug: "ovary",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "ovary", role: "primary", notes: "Ovary cycle image for reproductive-system education." },
      { entityType: "anatomy_concept", entitySlug: "ovary", role: "reference", notes: "Ovary concept context." },
      { entityType: "anatomy_concept", entitySlug: "reproductive-system", role: "reference", notes: "Reproductive-system context." },
    ],
  },
  {
    slug: "servier-ovary-structure-2d-illustration",
    title: "Servier Ovary Structure 2D Illustration",
    description: "Reviewed Servier Medical Art 2D ovary structure illustration for pelvic reproductive anatomy education.",
    sourcePage: "https://smart.servier.com/smart_image/smart-ovary/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/ovaire_2c.png",
    storagePath: "anatomy/servier/2d/ovary-structure.png",
    entityType: "anatomy_structure",
    entitySlug: "ovary",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "ovary", role: "primary", notes: "Ovary structure image for reproductive anatomy browsing." },
      { entityType: "anatomy_concept", entitySlug: "reproductive-system", role: "reference", notes: "Reproductive-system context." },
    ],
  },
  {
    slug: "servier-ovary-view-2d-illustration",
    title: "Servier Ovary View 2D Illustration",
    description: "Reviewed Servier Medical Art 2D ovary view illustration for reproductive organ education.",
    sourcePage: "https://smart.servier.com/smart_image/smart-ovary-view/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/ovaire_2d.png",
    storagePath: "anatomy/servier/2d/ovary-view.png",
    entityType: "anatomy_structure",
    entitySlug: "ovary",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "ovary", role: "primary", notes: "Additional ovary view for anatomy browsing." },
      { entityType: "region", entitySlug: "pelvis", role: "region_context", notes: "Pelvic organ context." },
    ],
  },
  {
    slug: "servier-kidney-with-adrenal-gland-2d-illustration",
    title: "Servier Kidney with Adrenal Gland 2D Illustration",
    description: "Reviewed Servier Medical Art 2D kidney with adrenal gland illustration for urinary and endocrine adjacency education.",
    sourcePage: "https://smart.servier.com/smart_image/adrenal/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/rein_surrenale.png",
    storagePath: "anatomy/servier/2d/kidney-with-adrenal-gland.png",
    entityType: "anatomy_structure",
    entitySlug: "adrenal-gland",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "adrenal-gland", role: "primary", notes: "Adrenal gland position relative to kidney." },
      { entityType: "anatomy_structure", entitySlug: "kidney", role: "reference", notes: "Kidney-adrenal adjacency context." },
      { entityType: "anatomy_concept", entitySlug: "endocrine-system", role: "reference", notes: "Endocrine-system context." },
    ],
  },
  {
    slug: "servier-adrenal-gland-longitudinal-section-2d-illustration",
    title: "Servier Adrenal Gland Longitudinal Section 2D Illustration",
    description: "Reviewed Servier Medical Art 2D adrenal gland longitudinal section illustration for endocrine gland structure education.",
    sourcePage: "https://smart.servier.com/smart_image/longitudinal-section-adrenal/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/surrenale.png",
    storagePath: "anatomy/servier/2d/adrenal-gland-longitudinal-section.png",
    entityType: "anatomy_structure",
    entitySlug: "adrenal-gland",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "adrenal-gland", role: "primary", notes: "Longitudinal adrenal section for endocrine education." },
      { entityType: "anatomy_concept", entitySlug: "adrenal-gland", role: "reference", notes: "Adrenal concept context." },
    ],
  },
  {
    slug: "servier-adult-anatomical-diagram-2d-illustration",
    title: "Servier Adult Anatomical Diagram 2D Illustration",
    description: "Reviewed Servier Medical Art 2D adult anatomical diagram for body-map orientation and whole-body education.",
    sourcePage: "https://smart.servier.com/smart_image/adult-anatomical-diagram/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/Adulte01.png",
    storagePath: "anatomy/servier/2d/adult-anatomical-diagram.png",
    entityType: "region",
    entitySlug: "trunk-spine-pelvis",
    entityLinks: [
      { entityType: "region", entitySlug: "trunk-spine-pelvis", role: "primary", notes: "Whole-body anatomical diagram linked to trunk and body-map context." },
      { entityType: "region", entitySlug: "head", role: "region_context", notes: "Head body-map context." },
      { entityType: "region", entitySlug: "upper-limb", role: "region_context", notes: "Upper-limb body-map context." },
      { entityType: "region", entitySlug: "lower-limb", role: "region_context", notes: "Lower-limb body-map context." },
    ],
  },
] as const

export const MEDIA_SERVIER_BODY_ATLAS_SECTION = {
  mediaAssets: bodyAtlasImages.map((asset) => ({
    id: `media-${asset.slug}`,
    slug: asset.slug,
    title: asset.title,
    mediaType: "image",
    description: asset.description,
    sourceRef: SERVIER_SOURCE,
    sourceUrl: asset.sourceUrl,
    storagePath: asset.storagePath,
    license: "CC BY 4.0",
    licenseUrl: SERVIER_LICENSE_URL,
    attribution: SERVIER_ATTRIBUTION,
    author: "Servier Medical Art",
    usageScope: "open_reuse",
    reviewStatus: "reviewed",
    format: "png",
    metadata: {
      r2Upload: true,
      sourceKind: "servier-2d-education-image",
      sourcePage: asset.sourcePage,
      licenseVerifiedAt: "2026-05-26",
      licensePage: SERVIER_LICENSE_PAGE,
      citationPage: SERVIER_CITATION_PAGE,
      visualStyle: "2d-medical-illustration",
      ingestionStatus: "pending_r2_upload",
    },
  })),
  mediaEntityLinks: bodyAtlasImages.flatMap((asset) => asset.entityLinks.map((link) => ({
    id: `media-link-${asset.slug}-${link.entityType}-${link.entitySlug}-${link.role}`,
    assetSlug: asset.slug,
    entityType: link.entityType,
    entitySlug: link.entitySlug,
    role: link.role,
    notes: link.notes,
  }))),
  citations: bodyAtlasImages.flatMap((asset) => [
    {
      id: `citation-${asset.slug}-media-source`,
      slug: `citation-${asset.slug}-media-source`,
      entityType: asset.entityType,
      entitySlug: asset.entitySlug,
      factType: "media_source",
      factSlug: asset.slug,
      sourceRef: SERVIER_SOURCE,
      sourceLocator: asset.sourcePage,
      citationNote: "Servier Medical Art image page selected for 2D body-atlas education media ingestion with stored direct image URL, license, attribution, and R2 upload path.",
      reviewStatus: "reviewed",
    },
    {
      id: `citation-${asset.slug}-media-license`,
      slug: `citation-${asset.slug}-media-license`,
      entityType: asset.entityType,
      entitySlug: asset.entitySlug,
      factType: "media_license",
      factSlug: asset.slug,
      sourceRef: SERVIER_SOURCE,
      sourceLocator: SERVIER_LICENSE_PAGE,
      citationNote: "Servier Medical Art states SMART images are available under CC BY 4.0 and provides attribution guidance for reuse.",
      reviewStatus: "reviewed",
    },
  ]),
} satisfies AnatomySeedSection
