import type { AnatomySeedSection } from "./sections.ts"

const SERVIER_SOURCE = "servier-medical-art"
const SERVIER_ATTRIBUTION = "Image provided by Servier Medical Art (https://smart.servier.com/), licensed under CC BY 4.0."
const SERVIER_LICENSE_URL = "https://creativecommons.org/licenses/by/4.0/"
const SERVIER_LICENSE_PAGE = "https://smart.servier.com/using-smart-images-what-you-can-do/"
const SERVIER_CITATION_PAGE = "https://smart.servier.com/how-to-cite-servier-medical-art/"

const organDetailImages = [
  {
    slug: "servier-spleen-overview-2d-illustration",
    title: "Servier Spleen Overview 2D Illustration",
    description: "Reviewed Servier Medical Art 2D spleen illustration for lymphatic-system and abdominal-organ education.",
    sourcePage: "https://smart.servier.com/smart_image/spleen-2/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2025/09/Spleen.png",
    storagePath: "anatomy/servier/2d/spleen-overview.png",
    entityType: "anatomy_structure",
    entitySlug: "spleen",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "spleen", role: "primary", notes: "Primary 2D spleen image for lymphatic and immune-system education." },
      { entityType: "anatomy_concept", entitySlug: "spleen", role: "client_education", notes: "Client-friendly spleen concept image." },
      { entityType: "anatomy_concept", entitySlug: "lymphatic-system", role: "reference", notes: "Lymphatic-system organ context." },
    ],
  },
  {
    slug: "servier-splenic-vein-and-artery-2d-illustration",
    title: "Servier Splenic Vein and Artery 2D Illustration",
    description: "Reviewed Servier Medical Art 2D splenic vessel illustration for spleen vascular anatomy and abdominal circulation education.",
    sourcePage: "https://smart.servier.com/smart_image/splenic-vein-and-artery/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2025/09/Splenic-Vein-and-Artery.png",
    storagePath: "anatomy/servier/2d/splenic-vein-and-artery.png",
    entityType: "anatomy_structure",
    entitySlug: "spleen",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "spleen", role: "primary", notes: "Spleen vascular orientation image." },
      { entityType: "blood_supply", entitySlug: "splenic-artery", role: "reference", notes: "Splenic artery pathway context shown with the spleen." },
      { entityType: "anatomy_concept", entitySlug: "cardiovascular-system", role: "reference", notes: "Abdominal circulation context." },
    ],
  },
  {
    slug: "servier-thymus-2d-illustration",
    title: "Servier Thymus 2D Illustration",
    description: "Reviewed Servier Medical Art 2D thymus illustration for lymphatic, immune, and mediastinal education.",
    sourcePage: "https://smart.servier.com/smart_image/thymus/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/thymus.png",
    storagePath: "anatomy/servier/2d/thymus.png",
    entityType: "anatomy_structure",
    entitySlug: "thymus",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "thymus", role: "primary", notes: "Primary thymus education image." },
      { entityType: "anatomy_concept", entitySlug: "thymus", role: "client_education", notes: "Client-friendly thymus concept image." },
      { entityType: "region", entitySlug: "thorax", role: "region_context", notes: "Thoracic organ context." },
    ],
  },
  {
    slug: "servier-esophagus-cutaway-2d-illustration",
    title: "Servier Esophagus Cutaway 2D Illustration",
    description: "Reviewed Servier Medical Art 2D esophagus cutaway illustration for digestive-tract and thoracic anatomy education.",
    sourcePage: "https://smart.servier.com/smart_image/smart-esophagus/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/oesophage_coupe.png",
    storagePath: "anatomy/servier/2d/esophagus-cutaway.png",
    entityType: "anatomy_structure",
    entitySlug: "esophagus",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "esophagus", role: "primary", notes: "Primary esophageal cutaway image." },
      { entityType: "anatomy_concept", entitySlug: "gastrointestinal-tract", role: "reference", notes: "Digestive tract pathway context." },
      { entityType: "region", entitySlug: "thorax", role: "region_context", notes: "Thoracic digestive structure context." },
    ],
  },
  {
    slug: "servier-esophagus-overview-2d-illustration",
    title: "Servier Esophagus Overview 2D Illustration",
    description: "Reviewed Servier Medical Art 2D esophagus overview illustration for digestive-system pathway education.",
    sourcePage: "https://smart.servier.com/smart_image/esophagus-ov/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/oesophage.png",
    storagePath: "anatomy/servier/2d/esophagus-overview.png",
    entityType: "anatomy_structure",
    entitySlug: "esophagus",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "esophagus", role: "primary", notes: "Esophagus overview image for pathway orientation." },
      { entityType: "anatomy_concept", entitySlug: "digestive-system", role: "reference", notes: "Digestive-system context." },
    ],
  },
  {
    slug: "servier-gallbladder-duodenum-2d-illustration",
    title: "Servier Gallbladder and Duodenum 2D Illustration",
    description: "Reviewed Servier Medical Art 2D gallbladder and duodenum illustration for biliary and upper-abdominal digestive education.",
    sourcePage: "https://smart.servier.com/smart_image/smart-gallbladder/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/vesiculebil_duo.png",
    storagePath: "anatomy/servier/2d/gallbladder-duodenum.png",
    entityType: "anatomy_structure",
    entitySlug: "gallbladder",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "gallbladder", role: "primary", notes: "Primary gallbladder image with biliary-drainage context." },
      { entityType: "anatomy_structure", entitySlug: "small-intestine", role: "reference", notes: "Duodenal context for biliary flow." },
      { entityType: "anatomy_concept", entitySlug: "bile", role: "client_education", notes: "Client-friendly bile pathway image." },
    ],
  },
  {
    slug: "servier-liver-and-gallbladder-2d-illustration",
    title: "Servier Liver and Gallbladder 2D Illustration",
    description: "Reviewed Servier Medical Art 2D liver and gallbladder illustration for accessory digestive organ education.",
    sourcePage: "https://smart.servier.com/smart_image/liver-and-gallbladder/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/foie_vesicule.png",
    storagePath: "anatomy/servier/2d/liver-and-gallbladder.png",
    entityType: "anatomy_structure",
    entitySlug: "liver",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "liver", role: "primary", notes: "Liver image with gallbladder adjacency." },
      { entityType: "anatomy_structure", entitySlug: "gallbladder", role: "reference", notes: "Gallbladder relationship to liver and bile pathway." },
      { entityType: "anatomy_concept", entitySlug: "accessory-digestive-organs", role: "reference", notes: "Accessory digestive organ context." },
    ],
  },
  {
    slug: "servier-liver-lobule-2d-illustration",
    title: "Servier Liver Lobule 2D Illustration",
    description: "Reviewed Servier Medical Art 2D liver lobule illustration for liver tissue organization and digestive physiology education.",
    sourcePage: "https://smart.servier.com/smart_image/liver-overview/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/foie_coupe.png",
    storagePath: "anatomy/servier/2d/liver-lobule.png",
    entityType: "anatomy_structure",
    entitySlug: "liver",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "liver", role: "primary", notes: "Liver internal tissue organization image." },
      { entityType: "anatomy_concept", entitySlug: "digestive-system", role: "reference", notes: "Digestive physiology context." },
    ],
  },
  {
    slug: "servier-stomach-overview-2d-illustration",
    title: "Servier Stomach Overview 2D Illustration",
    description: "Reviewed Servier Medical Art 2D stomach overview illustration for digestive-organ and upper-abdominal education.",
    sourcePage: "https://smart.servier.com/smart_image/smart-stomach/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/estomac_01.png",
    storagePath: "anatomy/servier/2d/stomach-overview.png",
    entityType: "anatomy_structure",
    entitySlug: "stomach",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "stomach", role: "primary", notes: "Stomach overview image." },
      { entityType: "anatomy_concept", entitySlug: "stomach", role: "client_education", notes: "Client-friendly stomach concept image." },
      { entityType: "region", entitySlug: "abdomen", role: "region_context", notes: "Upper abdominal organ context." },
    ],
  },
  {
    slug: "servier-stomach-lymphatic-system-2d-illustration",
    title: "Servier Stomach Lymphatic System 2D Illustration",
    description: "Reviewed Servier Medical Art 2D stomach lymphatic illustration for lymphatic drainage and abdominal-organ education.",
    sourcePage: "https://smart.servier.com/smart_image/lymphatic-system-stomach/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/Estomac_syst_lymphatique.png",
    storagePath: "anatomy/servier/2d/stomach-lymphatic-system.png",
    entityType: "anatomy_structure",
    entitySlug: "stomach",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "stomach", role: "primary", notes: "Stomach lymphatic drainage image." },
      { entityType: "anatomy_concept", entitySlug: "lymphatic-system", role: "reference", notes: "Lymphatic drainage context." },
      { entityType: "anatomy_structure", entitySlug: "lymph-node", role: "reference", notes: "Lymph node pathway context." },
    ],
  },
  {
    slug: "servier-intestine-segmentation-2d-illustration",
    title: "Servier Intestine Segmentation 2D Illustration",
    description: "Reviewed Servier Medical Art 2D intestine segmentation illustration for digestive-tract education.",
    sourcePage: "https://smart.servier.com/smart_image/smart-intestine-segmentation/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/Segmentation2.png",
    storagePath: "anatomy/servier/2d/intestine-segmentation.png",
    entityType: "anatomy_structure",
    entitySlug: "small-intestine",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "small-intestine", role: "primary", notes: "Small intestine and intestinal segmentation context." },
      { entityType: "anatomy_structure", entitySlug: "large-intestine", role: "reference", notes: "Large intestine context in digestive pathway." },
      { entityType: "anatomy_concept", entitySlug: "gastrointestinal-tract", role: "reference", notes: "GI tract pathway context." },
    ],
  },
  {
    slug: "servier-rectum-2d-illustration",
    title: "Servier Rectum 2D Illustration",
    description: "Reviewed Servier Medical Art 2D rectum illustration for distal digestive-system and pelvic anatomy education.",
    sourcePage: "https://smart.servier.com/smart_image/rectum/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/Rectum.png",
    storagePath: "anatomy/servier/2d/rectum.png",
    entityType: "anatomy_structure",
    entitySlug: "rectum",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "rectum", role: "primary", notes: "Primary rectum image." },
      { entityType: "region", entitySlug: "pelvis", role: "region_context", notes: "Pelvic digestive structure context." },
      { entityType: "anatomy_concept", entitySlug: "bowel-elimination", role: "reference", notes: "Bowel-elimination physiology context." },
    ],
  },
  {
    slug: "servier-uterus-frontal-2d-illustration",
    title: "Servier Uterus Frontal 2D Illustration",
    description: "Reviewed Servier Medical Art 2D uterus illustration for reproductive-system and pelvic organ education.",
    sourcePage: "https://smart.servier.com/smart_image/uterus/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/uterus_1.png",
    storagePath: "anatomy/servier/2d/uterus-frontal.png",
    entityType: "anatomy_structure",
    entitySlug: "uterus",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "uterus", role: "primary", notes: "Primary frontal uterus image." },
      { entityType: "anatomy_concept", entitySlug: "uterus", role: "client_education", notes: "Client-friendly uterus concept image." },
      { entityType: "region", entitySlug: "pelvis", role: "region_context", notes: "Pelvic organ context." },
    ],
  },
  {
    slug: "servier-uterus-lateral-2d-illustration",
    title: "Servier Uterus Lateral 2D Illustration",
    description: "Reviewed Servier Medical Art 2D lateral uterus illustration for pelvic organ orientation and reproductive education.",
    sourcePage: "https://smart.servier.com/smart_image/uterus-lateral-view/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/uterus_2.png",
    storagePath: "anatomy/servier/2d/uterus-lateral.png",
    entityType: "anatomy_structure",
    entitySlug: "uterus",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "uterus", role: "primary", notes: "Lateral uterus image for pelvic orientation." },
      { entityType: "anatomy_concept", entitySlug: "reproductive-system", role: "reference", notes: "Reproductive-system context." },
    ],
  },
  {
    slug: "servier-pituitary-gland-overview-2d-illustration",
    title: "Servier Pituitary Gland Overview 2D Illustration",
    description: "Reviewed Servier Medical Art 2D pituitary gland illustration for endocrine-system and cranial education.",
    sourcePage: "https://smart.servier.com/smart_image/smart-pituitary-gland/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/AHH_02.png",
    storagePath: "anatomy/servier/2d/pituitary-gland-overview.png",
    entityType: "anatomy_structure",
    entitySlug: "pituitary-gland",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "pituitary-gland", role: "primary", notes: "Primary pituitary gland image." },
      { entityType: "anatomy_concept", entitySlug: "pituitary-gland", role: "client_education", notes: "Client-friendly pituitary gland concept image." },
      { entityType: "anatomy_concept", entitySlug: "endocrine-system", role: "reference", notes: "Endocrine-system context." },
    ],
  },
  {
    slug: "servier-pituitary-gland-location-2d-illustration",
    title: "Servier Pituitary Gland Location 2D Illustration",
    description: "Reviewed Servier Medical Art 2D pituitary gland location illustration for endocrine and head-region education.",
    sourcePage: "https://smart.servier.com/smart_image/pituitary-gland/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/AHH_01.png",
    storagePath: "anatomy/servier/2d/pituitary-gland-location.png",
    entityType: "anatomy_structure",
    entitySlug: "pituitary-gland",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "pituitary-gland", role: "primary", notes: "Pituitary gland location image." },
      { entityType: "region", entitySlug: "head", role: "region_context", notes: "Head-region endocrine orientation." },
    ],
  },
  {
    slug: "servier-thyroid-posterior-view-2d-illustration",
    title: "Servier Thyroid Posterior View 2D Illustration",
    description: "Reviewed Servier Medical Art 2D posterior thyroid illustration for endocrine and anterior-neck education.",
    sourcePage: "https://smart.servier.com/smart_image/thyroid-overview/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/thyroide_post.png",
    storagePath: "anatomy/servier/2d/thyroid-posterior-view.png",
    entityType: "anatomy_structure",
    entitySlug: "thyroid-gland",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "thyroid-gland", role: "primary", notes: "Posterior thyroid image." },
      { entityType: "anatomy_structure", entitySlug: "parathyroid-gland", role: "reference", notes: "Posterior thyroid/parathyroid orientation context." },
      { entityType: "region", entitySlug: "neck", role: "region_context", notes: "Anterior neck endocrine context." },
    ],
  },
  {
    slug: "servier-skin-section-2d-illustration",
    title: "Servier Skin Section 2D Illustration",
    description: "Reviewed Servier Medical Art 2D skin section illustration for integumentary-system, layer, and gland education.",
    sourcePage: "https://smart.servier.com/smart_image/skin/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/peau.png",
    storagePath: "anatomy/servier/2d/skin-section.png",
    entityType: "anatomy_structure",
    entitySlug: "skin",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "skin", role: "primary", notes: "Primary skin cross-section image." },
      { entityType: "anatomy_structure", entitySlug: "epidermis", role: "reference", notes: "Epidermal layer context." },
      { entityType: "anatomy_structure", entitySlug: "dermis", role: "reference", notes: "Dermal layer context." },
      { entityType: "anatomy_structure", entitySlug: "hypodermis", role: "reference", notes: "Subcutaneous tissue context." },
      { entityType: "anatomy_concept", entitySlug: "integumentary-system", role: "client_education", notes: "Client-friendly integumentary-system image." },
    ],
  },
  {
    slug: "servier-cochlea-2d-illustration",
    title: "Servier Cochlea 2D Illustration",
    description: "Reviewed Servier Medical Art 2D cochlea illustration for ear and special-sense anatomy education.",
    sourcePage: "https://smart.servier.com/smart_image/cochlea/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/Oreille_interne_5.png",
    storagePath: "anatomy/servier/2d/cochlea.png",
    entityType: "anatomy_structure",
    entitySlug: "cochlea",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "cochlea", role: "primary", notes: "Primary cochlear anatomy image." },
      { entityType: "anatomy_structure", entitySlug: "ear", role: "reference", notes: "Inner ear context." },
      { entityType: "anatomy_concept", entitySlug: "hearing", role: "client_education", notes: "Client-friendly hearing concept image." },
    ],
  },
  {
    slug: "servier-retina-2d-illustration",
    title: "Servier Retina 2D Illustration",
    description: "Reviewed Servier Medical Art 2D retina illustration for eye and visual-system education.",
    sourcePage: "https://smart.servier.com/smart_image/smart-retina/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/retine_20.png",
    storagePath: "anatomy/servier/2d/retina.png",
    entityType: "anatomy_structure",
    entitySlug: "retina",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "retina", role: "primary", notes: "Primary retina anatomy image." },
      { entityType: "anatomy_structure", entitySlug: "eye", role: "reference", notes: "Eye anatomy context." },
      { entityType: "anatomy_concept", entitySlug: "vision", role: "client_education", notes: "Client-friendly vision concept image." },
    ],
  },
  {
    slug: "servier-spinal-cord-lumbar-section-2d-illustration",
    title: "Servier Spinal Cord Lumbar Section 2D Illustration",
    description: "Reviewed Servier Medical Art 2D spinal cord section illustration for nervous-system and spinal anatomy education.",
    sourcePage: "https://smart.servier.com/smart_image/spinal-cord-view/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/moelle_L2.png",
    storagePath: "anatomy/servier/2d/spinal-cord-lumbar-section.png",
    entityType: "anatomy_structure",
    entitySlug: "spinal-cord",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "spinal-cord", role: "primary", notes: "Spinal cord section image for lumbar-level orientation." },
      { entityType: "anatomy_concept", entitySlug: "central-nervous-system", role: "reference", notes: "Central nervous system context." },
    ],
  },
  {
    slug: "servier-neuron-overview-2d-illustration",
    title: "Servier Neuron Overview 2D Illustration",
    description: "Reviewed Servier Medical Art 2D neuron overview illustration for nervous-system education and flashcards.",
    sourcePage: "https://smart.servier.com/smart_image/smart-neuron-overview/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/neurone05.png",
    storagePath: "anatomy/servier/2d/neuron-overview.png",
    entityType: "anatomy_concept",
    entitySlug: "neuron",
    entityLinks: [
      { entityType: "anatomy_concept", entitySlug: "neuron", role: "primary", notes: "Neuron structure overview image." },
      { entityType: "anatomy_concept", entitySlug: "nervous-system", role: "reference", notes: "Nervous-system context." },
      { entityType: "anatomy_concept", entitySlug: "nerve-impulse", role: "reference", notes: "Nerve impulse physiology context." },
    ],
  },
  {
    slug: "servier-sciatic-nerve-2d-illustration",
    title: "Servier Sciatic Nerve 2D Illustration",
    description: "Reviewed Servier Medical Art 2D sciatic nerve illustration for lower-limb nervous-system education.",
    sourcePage: "https://smart.servier.com/smart_image/sciatic-nerve/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/Sciatique.png",
    storagePath: "anatomy/servier/2d/sciatic-nerve.png",
    entityType: "nerve",
    entitySlug: "sciatic-nerve",
    entityLinks: [
      { entityType: "nerve", entitySlug: "sciatic-nerve", role: "primary", notes: "Primary sciatic nerve education image." },
      { entityType: "region", entitySlug: "lower-limb", role: "region_context", notes: "Lower-limb nerve pathway context." },
      { entityType: "anatomy_concept", entitySlug: "peripheral-nervous-system", role: "reference", notes: "Peripheral nervous system context." },
    ],
  },
  {
    slug: "servier-nervous-system-overview-2d-illustration",
    title: "Servier Nervous System Overview 2D Illustration",
    description: "Reviewed Servier Medical Art 2D nervous-system overview illustration for CNS/PNS education and body-system browsing.",
    sourcePage: "https://smart.servier.com/smart_image/nervous-system/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/Systeme_nerveux.png",
    storagePath: "anatomy/servier/2d/nervous-system-overview.png",
    entityType: "anatomy_concept",
    entitySlug: "nervous-system",
    entityLinks: [
      { entityType: "anatomy_concept", entitySlug: "nervous-system", role: "primary", notes: "Primary nervous-system overview image." },
      { entityType: "anatomy_structure", entitySlug: "brain", role: "reference", notes: "Brain/CNS context." },
      { entityType: "anatomy_structure", entitySlug: "spinal-cord", role: "reference", notes: "Spinal cord/CNS context." },
      { entityType: "anatomy_concept", entitySlug: "peripheral-nervous-system", role: "client_education", notes: "Peripheral nerve pathway context." },
    ],
  },
  {
    slug: "servier-pancreas-lymphatic-drainage-2d-illustration",
    title: "Servier Pancreas Lymphatic Drainage 2D Illustration",
    description: "Reviewed Servier Medical Art 2D pancreas lymphatic drainage illustration for digestive-endocrine organ and lymphatic education.",
    sourcePage: "https://smart.servier.com/smart_image/pancreas-lymphatic-drainage/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2025/09/Pancreas-Lymphatic-drainage.png",
    storagePath: "anatomy/servier/2d/pancreas-lymphatic-drainage.png",
    entityType: "anatomy_structure",
    entitySlug: "pancreas",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "pancreas", role: "primary", notes: "Pancreas lymphatic drainage image." },
      { entityType: "anatomy_concept", entitySlug: "lymphatic-system", role: "reference", notes: "Lymphatic drainage context." },
      { entityType: "region", entitySlug: "abdomen", role: "region_context", notes: "Abdominal organ context." },
    ],
  },
  {
    slug: "servier-parotid-gland-2d-illustration",
    title: "Servier Parotid Gland 2D Illustration",
    description: "Reviewed Servier Medical Art 2D parotid gland illustration linked to salivary gland anatomy until individual salivary gland structures are split out.",
    sourcePage: "https://smart.servier.com/smart_image/parotid-gland/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2017/03/Parotid-gland.png",
    storagePath: "anatomy/servier/2d/parotid-gland.png",
    entityType: "anatomy_structure",
    entitySlug: "salivary-gland",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "salivary-gland", role: "primary", notes: "Parotid gland image linked to current salivary gland structure group." },
      { entityType: "region", entitySlug: "face", role: "region_context", notes: "Facial salivary gland context." },
      { entityType: "anatomy_concept", entitySlug: "digestive-system", role: "reference", notes: "Accessory digestive organ context." },
    ],
  },
  {
    slug: "servier-sublingual-gland-2d-illustration",
    title: "Servier Sublingual Gland 2D Illustration",
    description: "Reviewed Servier Medical Art 2D sublingual gland illustration linked to salivary gland anatomy until individual salivary gland structures are split out.",
    sourcePage: "https://smart.servier.com/smart_image/sublingual-gland/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2017/03/Sublingual-gland.png",
    storagePath: "anatomy/servier/2d/sublingual-gland.png",
    entityType: "anatomy_structure",
    entitySlug: "salivary-gland",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "salivary-gland", role: "primary", notes: "Sublingual gland image linked to current salivary gland structure group." },
      { entityType: "anatomy_structure", entitySlug: "oral-cavity", role: "reference", notes: "Oral cavity salivary gland context." },
    ],
  },
  {
    slug: "servier-submaxillary-gland-2d-illustration",
    title: "Servier Submaxillary Gland 2D Illustration",
    description: "Reviewed Servier Medical Art 2D submaxillary gland illustration linked to salivary gland anatomy until individual salivary gland structures are split out.",
    sourcePage: "https://smart.servier.com/smart_image/submaxillary-gland/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2017/03/Submaxillary-gland.png",
    storagePath: "anatomy/servier/2d/submaxillary-gland.png",
    entityType: "anatomy_structure",
    entitySlug: "salivary-gland",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "salivary-gland", role: "primary", notes: "Submaxillary gland image linked to current salivary gland structure group." },
      { entityType: "region", entitySlug: "jaw", role: "region_context", notes: "Jaw and oral region context." },
    ],
  },
  {
    slug: "servier-eye-iris-2d-illustration",
    title: "Servier Eye Iris 2D Illustration",
    description: "Reviewed Servier Medical Art 2D iris illustration for eye anatomy and visual-system education.",
    sourcePage: "https://smart.servier.com/smart_image/eye-iris/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/Oeil_iris.png",
    storagePath: "anatomy/servier/2d/eye-iris.png",
    entityType: "anatomy_structure",
    entitySlug: "iris",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "iris", role: "primary", notes: "Primary iris image for eye anatomy browsing." },
      { entityType: "anatomy_structure", entitySlug: "eye", role: "reference", notes: "Eye structure context." },
      { entityType: "anatomy_concept", entitySlug: "vision", role: "client_education", notes: "Client-friendly vision education context." },
    ],
  },
  {
    slug: "servier-eye-cornea-2d-illustration",
    title: "Servier Eye Cornea 2D Illustration",
    description: "Reviewed Servier Medical Art 2D cornea illustration for eye anatomy and visual-system education.",
    sourcePage: "https://smart.servier.com/smart_image/eye-cornea/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/Oeil_cornee.png",
    storagePath: "anatomy/servier/2d/eye-cornea.png",
    entityType: "anatomy_structure",
    entitySlug: "cornea",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "cornea", role: "primary", notes: "Primary cornea image for eye anatomy browsing." },
      { entityType: "anatomy_structure", entitySlug: "eye", role: "reference", notes: "Eye structure context." },
    ],
  },
  {
    slug: "servier-eye-lens-2d-illustration",
    title: "Servier Eye Lens 2D Illustration",
    description: "Reviewed Servier Medical Art 2D lens illustration for eye anatomy and visual-system education.",
    sourcePage: "https://smart.servier.com/smart_image/eye-lens/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/Oeil_cristallin.png",
    storagePath: "anatomy/servier/2d/eye-lens.png",
    entityType: "anatomy_structure",
    entitySlug: "lens",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "lens", role: "primary", notes: "Primary lens image for eye anatomy browsing." },
      { entityType: "anatomy_structure", entitySlug: "eye", role: "reference", notes: "Eye structure context." },
    ],
  },
  {
    slug: "servier-inner-ear-overview-2d-illustration",
    title: "Servier Inner Ear Overview 2D Illustration",
    description: "Reviewed Servier Medical Art 2D inner ear illustration for hearing, vestibular, and special-sense anatomy education.",
    sourcePage: "https://smart.servier.com/smart_image/inner-ear/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/Oreille_interne.png",
    storagePath: "anatomy/servier/2d/inner-ear-overview.png",
    entityType: "anatomy_structure",
    entitySlug: "ear",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "ear", role: "primary", notes: "Inner ear overview linked to ear anatomy." },
      { entityType: "anatomy_structure", entitySlug: "cochlea", role: "reference", notes: "Cochlear hearing context." },
      { entityType: "anatomy_structure", entitySlug: "vestibular-apparatus", role: "reference", notes: "Vestibular apparatus context." },
      { entityType: "anatomy_concept", entitySlug: "hearing", role: "client_education", notes: "Client-friendly hearing context." },
    ],
  },
  {
    slug: "servier-eardrum-2d-illustration",
    title: "Servier Eardrum 2D Illustration",
    description: "Reviewed Servier Medical Art 2D eardrum illustration for tympanic membrane and ear anatomy education.",
    sourcePage: "https://smart.servier.com/smart_image/eardrum/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/Oreille_interne_1.png",
    storagePath: "anatomy/servier/2d/eardrum.png",
    entityType: "anatomy_structure",
    entitySlug: "tympanic-membrane",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "tympanic-membrane", role: "primary", notes: "Primary eardrum/tympanic membrane image." },
      { entityType: "anatomy_structure", entitySlug: "ear", role: "reference", notes: "Ear structure context." },
    ],
  },
  {
    slug: "servier-malleus-2d-illustration",
    title: "Servier Malleus 2D Illustration",
    description: "Reviewed Servier Medical Art 2D hammer/malleus illustration for auditory ossicle education.",
    sourcePage: "https://smart.servier.com/smart_image/hammer/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/Oreille_interne_2.png",
    storagePath: "anatomy/servier/2d/malleus.png",
    entityType: "bone",
    entitySlug: "malleus",
    entityLinks: [
      { entityType: "bone", entitySlug: "malleus", role: "primary", notes: "Primary malleus image using Servier's hammer label." },
      { entityType: "anatomy_structure", entitySlug: "auditory-ossicles", role: "reference", notes: "Auditory ossicle group context." },
      { entityType: "anatomy_structure", entitySlug: "ear", role: "region_context", notes: "Ear anatomy context." },
    ],
  },
  {
    slug: "servier-incus-2d-illustration",
    title: "Servier Incus 2D Illustration",
    description: "Reviewed Servier Medical Art 2D anvil/incus illustration for auditory ossicle education.",
    sourcePage: "https://smart.servier.com/smart_image/anvil/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/Oreille_interne_3.png",
    storagePath: "anatomy/servier/2d/incus.png",
    entityType: "bone",
    entitySlug: "incus",
    entityLinks: [
      { entityType: "bone", entitySlug: "incus", role: "primary", notes: "Primary incus image using Servier's anvil label." },
      { entityType: "anatomy_structure", entitySlug: "auditory-ossicles", role: "reference", notes: "Auditory ossicle group context." },
      { entityType: "anatomy_structure", entitySlug: "ear", role: "region_context", notes: "Ear anatomy context." },
    ],
  },
  {
    slug: "servier-vestibulocochlear-nerve-2d-illustration",
    title: "Servier Vestibulocochlear Nerve 2D Illustration",
    description: "Reviewed Servier Medical Art 2D auditory nerve illustration linked to vestibulocochlear nerve anatomy.",
    sourcePage: "https://smart.servier.com/smart_image/auditive-nerve/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/Oreille_interne_6.png",
    storagePath: "anatomy/servier/2d/vestibulocochlear-nerve.png",
    entityType: "nerve",
    entitySlug: "vestibulocochlear-nerve",
    entityLinks: [
      { entityType: "nerve", entitySlug: "vestibulocochlear-nerve", role: "primary", notes: "Auditory nerve image linked to vestibulocochlear nerve." },
      { entityType: "anatomy_structure", entitySlug: "ear", role: "region_context", notes: "Inner ear nerve pathway context." },
      { entityType: "anatomy_concept", entitySlug: "hearing", role: "client_education", notes: "Hearing concept context." },
    ],
  },
  {
    slug: "servier-peripheral-nerve-2d-illustration",
    title: "Servier Peripheral Nerve 2D Illustration",
    description: "Reviewed Servier Medical Art 2D nerve illustration for peripheral nervous-system education.",
    sourcePage: "https://smart.servier.com/smart_image/nerve/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/Nerf.png",
    storagePath: "anatomy/servier/2d/peripheral-nerve.png",
    entityType: "anatomy_structure",
    entitySlug: "peripheral-nerve",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "peripheral-nerve", role: "primary", notes: "Primary peripheral nerve structure image." },
      { entityType: "anatomy_concept", entitySlug: "peripheral-nervous-system", role: "client_education", notes: "Client-friendly peripheral nervous-system image." },
    ],
  },
  {
    slug: "servier-sympathetic-nervous-system-2d-illustration",
    title: "Servier Sympathetic Nervous System 2D Illustration",
    description: "Reviewed Servier Medical Art 2D sympathetic nervous-system illustration for autonomic nervous-system education.",
    sourcePage: "https://smart.servier.com/smart_image/sympathetic-nervous-system/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/SNS.png",
    storagePath: "anatomy/servier/2d/sympathetic-nervous-system.png",
    entityType: "anatomy_concept",
    entitySlug: "sympathetic-division",
    entityLinks: [
      { entityType: "anatomy_concept", entitySlug: "sympathetic-division", role: "primary", notes: "Primary sympathetic nervous-system education image." },
      { entityType: "anatomy_concept", entitySlug: "autonomic-nervous-system", role: "reference", notes: "Autonomic nervous-system context." },
      { entityType: "anatomy_concept", entitySlug: "stress-response", role: "client_education", notes: "Client-friendly stress-response physiology context." },
    ],
  },
  {
    slug: "servier-testis-section-2d-illustration",
    title: "Servier Testis Section 2D Illustration",
    description: "Reviewed Servier Medical Art 2D testicle/testis illustration for reproductive anatomy education.",
    sourcePage: "https://smart.servier.com/smart_image/testicle/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/testicle.png",
    storagePath: "anatomy/servier/2d/testis-section.png",
    entityType: "anatomy_structure",
    entitySlug: "testis",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "testis", role: "primary", notes: "Primary testis image using Servier's testicle label." },
      { entityType: "anatomy_concept", entitySlug: "testis", role: "client_education", notes: "Client-friendly testis concept image." },
      { entityType: "anatomy_concept", entitySlug: "reproductive-system", role: "reference", notes: "Reproductive-system context." },
    ],
  },
  {
    slug: "servier-testis-overview-2d-illustration",
    title: "Servier Testis Overview 2D Illustration",
    description: "Reviewed Servier Medical Art 2D testicle/testis overview illustration for reproductive-system education.",
    sourcePage: "https://smart.servier.com/smart_image/testicle-ov/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/testicle-2.png",
    storagePath: "anatomy/servier/2d/testis-overview.png",
    entityType: "anatomy_structure",
    entitySlug: "testis",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "testis", role: "primary", notes: "Testis overview image using Servier's testicle label." },
      { entityType: "anatomy_concept", entitySlug: "gametogenesis", role: "reference", notes: "Gametogenesis physiology context." },
    ],
  },
  {
    slug: "servier-trachea-and-bronchi-2d-illustration",
    title: "Servier Trachea and Bronchi 2D Illustration",
    description: "Reviewed Servier Medical Art 2D trachea and bronchi illustration for respiratory-system education.",
    sourcePage: "https://smart.servier.com/smart_image/lungs/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/poumon_01.png",
    storagePath: "anatomy/servier/2d/trachea-and-bronchi.png",
    entityType: "anatomy_structure",
    entitySlug: "trachea",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "trachea", role: "primary", notes: "Trachea and main airway image." },
      { entityType: "anatomy_structure", entitySlug: "bronchus", role: "reference", notes: "Bronchial airway context." },
      { entityType: "anatomy_structure", entitySlug: "lung", role: "reference", notes: "Lung airway context." },
      { entityType: "anatomy_concept", entitySlug: "respiratory-system", role: "client_education", notes: "Client-friendly respiratory-system context." },
    ],
  },
  {
    slug: "servier-nasal-cavity-2d-illustration",
    title: "Servier Nasal Cavity 2D Illustration",
    description: "Reviewed Servier Medical Art 2D nasal cavity illustration for upper-airway and head-region education.",
    sourcePage: "https://smart.servier.com/smart_image/nasal-cavity/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/Cavite_nasale.png",
    storagePath: "anatomy/servier/2d/nasal-cavity.png",
    entityType: "anatomy_structure",
    entitySlug: "nasal-cavity",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "nasal-cavity", role: "primary", notes: "Primary nasal cavity image." },
      { entityType: "region", entitySlug: "face", role: "region_context", notes: "Face and upper-airway region context." },
      { entityType: "anatomy_concept", entitySlug: "respiratory-system", role: "reference", notes: "Respiratory-system context." },
    ],
  },
] as const

export const MEDIA_SERVIER_ORGAN_DETAIL_SECTION = {
  mediaAssets: organDetailImages.map((asset) => ({
    id: `media-${asset.slug}`,
    slug: asset.slug,
    title: asset.title,
    mediaType: "image",
    description: asset.description,
    sourceRef: SERVIER_SOURCE,
    sourceUrl: asset.sourceUrl,
    storagePath: asset.storagePath,
    license: "CC BY 4.0",
    licenseUrl: SERVIER_LICENSE_URL,
    attribution: SERVIER_ATTRIBUTION,
    author: "Servier Medical Art",
    usageScope: "open_reuse",
    reviewStatus: "reviewed",
    format: "png",
    metadata: {
      r2Upload: true,
      sourceKind: "servier-2d-education-image",
      sourcePage: asset.sourcePage,
      licenseVerifiedAt: "2026-05-26",
      licensePage: SERVIER_LICENSE_PAGE,
      citationPage: SERVIER_CITATION_PAGE,
      visualStyle: "2d-medical-illustration",
      ingestionStatus: "pending_r2_upload",
    },
  })),
  mediaEntityLinks: organDetailImages.flatMap((asset) => asset.entityLinks.map((link) => ({
    id: `media-link-${asset.slug}-${link.entityType}-${link.entitySlug}-${link.role}`,
    assetSlug: asset.slug,
    entityType: link.entityType,
    entitySlug: link.entitySlug,
    role: link.role,
    notes: link.notes,
  }))),
  citations: organDetailImages.flatMap((asset) => [
    {
      id: `citation-${asset.slug}-media-source`,
      slug: `citation-${asset.slug}-media-source`,
      entityType: asset.entityType,
      entitySlug: asset.entitySlug,
      factType: "media_source",
      factSlug: asset.slug,
      sourceRef: SERVIER_SOURCE,
      sourceLocator: asset.sourcePage,
      citationNote: "Servier Medical Art image page selected for 2D organ and tissue detail media ingestion with stored direct image URL, license, attribution, and R2 upload path.",
      reviewStatus: "reviewed",
    },
    {
      id: `citation-${asset.slug}-media-license`,
      slug: `citation-${asset.slug}-media-license`,
      entityType: asset.entityType,
      entitySlug: asset.entitySlug,
      factType: "media_license",
      factSlug: asset.slug,
      sourceRef: SERVIER_SOURCE,
      sourceLocator: SERVIER_LICENSE_PAGE,
      citationNote: "Servier Medical Art states SMART images are available under CC BY 4.0 and provides attribution guidance for reuse.",
      reviewStatus: "reviewed",
    },
  ]),
} satisfies AnatomySeedSection
