import type { AnatomySeedSection } from "./sections.ts"

const SERVIER_SOURCE = "servier-medical-art"
const SERVIER_ATTRIBUTION = "Image provided by Servier Medical Art (https://smart.servier.com/), licensed under CC BY 4.0."
const SERVIER_LICENSE_URL = "https://creativecommons.org/licenses/by/4.0/"
const SERVIER_LICENSE_PAGE = "https://smart.servier.com/using-smart-images-what-you-can-do/"
const SERVIER_CITATION_PAGE = "https://smart.servier.com/how-to-cite-servier-medical-art/"

const locomotorImages = [
  {
    slug: "servier-vertebral-column-2d-illustration",
    title: "Servier Vertebral Column 2D Illustration",
    description: "Reviewed Servier Medical Art 2D vertebral column illustration for spine education, body-map orientation, and flashcard prompts.",
    sourcePage: "https://smart.servier.com/smart_image/vertebral-column/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/colonne_01.png",
    storagePath: "anatomy/servier/2d/vertebral-column.png",
    entityType: "region",
    entitySlug: "trunk-spine-pelvis",
    entityLinks: [
      { entityType: "region", entitySlug: "trunk-spine-pelvis", role: "primary", notes: "Primary 2D spine orientation image for trunk, spine, and pelvis browsing." },
      { entityType: "bone", entitySlug: "lumbar-vertebrae", role: "reference", notes: "Lumbar vertebral region shown within the column." },
      { entityType: "bone", entitySlug: "sacrum", role: "reference", notes: "Sacral base shown at the inferior end of the column." },
      { entityType: "anatomy_structure", entitySlug: "intervertebral-disc", role: "reference", notes: "Intervertebral disc spacing visible in the illustration." },
    ],
  },
  {
    slug: "servier-vertebra-2d-illustration",
    title: "Servier Vertebra 2D Illustration",
    description: "Reviewed Servier Medical Art 2D single vertebra illustration for axial skeleton education and spinal landmark browsing.",
    sourcePage: "https://smart.servier.com/smart_image/vertebra/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/vertebre_01.png",
    storagePath: "anatomy/servier/2d/vertebra.png",
    entityType: "bone",
    entitySlug: "c3-vertebra",
    entityLinks: [
      { entityType: "bone", entitySlug: "c3-vertebra", role: "primary", notes: "Representative individual vertebra image for cervical-level browsing." },
      { entityType: "bone", entitySlug: "t1-vertebra", role: "reference", notes: "Representative vertebral anatomy reference for thoracic-level browsing." },
      { entityType: "bone", entitySlug: "l1-vertebra", role: "reference", notes: "Representative vertebral anatomy reference for lumbar-level browsing." },
    ],
  },
  {
    slug: "servier-rib-cage-2d-illustration",
    title: "Servier Rib Cage 2D Illustration",
    description: "Reviewed Servier Medical Art 2D rib cage illustration for thoracic cage, breathing mechanics, and chest-wall education.",
    sourcePage: "https://smart.servier.com/smart_image/rib-cage/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/squelette_04.png",
    storagePath: "anatomy/servier/2d/rib-cage.png",
    entityType: "joint",
    entitySlug: "thoracic-cage",
    entityLinks: [
      { entityType: "joint", entitySlug: "thoracic-cage", role: "primary", notes: "Primary 2D image for thoracic cage and rib movement education." },
      { entityType: "bone", entitySlug: "first-rib", role: "reference", notes: "Superior rib context visible in the rib cage." },
      { entityType: "anatomy_structure", entitySlug: "costal-cartilages", role: "reference", notes: "Costal cartilage context visible anteriorly." },
      { entityType: "region", entitySlug: "thorax", role: "region_context", notes: "Thorax body-map orientation image." },
    ],
  },
  {
    slug: "servier-skull-2d-illustration",
    title: "Servier Skull 2D Illustration",
    description: "Reviewed Servier Medical Art 2D skull illustration for head, face, jaw, and craniofacial bone browsing.",
    sourcePage: "https://smart.servier.com/smart_image/skull/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/crane_01.png",
    storagePath: "anatomy/servier/2d/skull.png",
    entityType: "region",
    entitySlug: "head-face-jaw",
    entityLinks: [
      { entityType: "region", entitySlug: "head-face-jaw", role: "primary", notes: "Primary 2D craniofacial orientation image for head, face, and jaw browsing." },
      { entityType: "bone", entitySlug: "frontal-bone", role: "reference", notes: "Frontal bone context shown in the skull illustration." },
      { entityType: "bone", entitySlug: "mandible", role: "reference", notes: "Mandible context shown in the skull illustration." },
      { entityType: "joint", entitySlug: "temporomandibular-joint", role: "reference", notes: "TMJ region context for jaw education." },
    ],
  },
  {
    slug: "servier-tendon-anatomy-2d-illustration",
    title: "Servier Tendon Anatomy 2D Illustration",
    description: "Reviewed Servier Medical Art 2D tendon structure illustration for connective-tissue, tendon, and proprioceptor education.",
    sourcePage: "https://smart.servier.com/smart_image/tendon-anatomy/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/Tendon_structure.png",
    storagePath: "anatomy/servier/2d/tendon-anatomy.png",
    entityType: "anatomy_concept",
    entitySlug: "musculoskeletal-system",
    entityLinks: [
      { entityType: "anatomy_concept", entitySlug: "musculoskeletal-system", role: "primary", notes: "General musculoskeletal connective-tissue education image." },
      { entityType: "anatomy_structure", entitySlug: "biceps-tendon", role: "reference", notes: "Representative tendon structure image for upper-limb tendon browsing." },
      { entityType: "anatomy_structure", entitySlug: "patellar-tendon", role: "reference", notes: "Representative tendon structure image for knee tendon browsing." },
      { entityType: "anatomy_concept", entitySlug: "golgi-tendon-organ", role: "reference", notes: "Connective-tissue context for proprioceptor education." },
    ],
  },
  {
    slug: "servier-normal-joint-2d-illustration",
    title: "Servier Normal Joint 2D Illustration",
    description: "Reviewed Servier Medical Art 2D normal joint illustration for synovial joint, capsule, cartilage, and ROM education.",
    sourcePage: "https://smart.servier.com/smart_image/normal-joint/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/Articulation_normale.png",
    storagePath: "anatomy/servier/2d/normal-joint.png",
    entityType: "anatomy_structure",
    entitySlug: "joint-capsule",
    entityLinks: [
      { entityType: "anatomy_structure", entitySlug: "joint-capsule", role: "primary", notes: "Primary 2D image for synovial joint capsule education." },
      { entityType: "anatomy_structure", entitySlug: "articular-cartilage", role: "reference", notes: "Articular cartilage surfaces visible in the diagram." },
      { entityType: "anatomy_concept", entitySlug: "joint-movement", role: "reference", notes: "Reusable joint anatomy image for ROM education." },
      { entityType: "anatomy_concept", entitySlug: "joint-stability", role: "client_education", notes: "Client-friendly joint stability illustration." },
    ],
  },
  {
    slug: "servier-elbow-anterior-2d-illustration",
    title: "Servier Elbow Anterior 2D Illustration",
    description: "Reviewed Servier Medical Art 2D anterior elbow illustration for elbow joint, ligament, tendon, and upper-limb education.",
    sourcePage: "https://smart.servier.com/smart_image/smart-joint-elbow/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/articulation_04.png",
    storagePath: "anatomy/servier/2d/elbow-anterior.png",
    entityType: "joint",
    entitySlug: "elbow-joint",
    entityLinks: [
      { entityType: "joint", entitySlug: "elbow-joint", role: "primary", notes: "Primary anterior elbow joint education view." },
      { entityType: "bone", entitySlug: "radius", role: "reference", notes: "Radius participation in elbow anatomy." },
      { entityType: "bone", entitySlug: "ulna", role: "reference", notes: "Ulna participation in elbow anatomy." },
      { entityType: "anatomy_structure", entitySlug: "common-flexor-tendon", role: "reference", notes: "Medial elbow tendon context for education." },
    ],
  },
  {
    slug: "servier-elbow-frontal-2d-illustration",
    title: "Servier Elbow Frontal 2D Illustration",
    description: "Reviewed Servier Medical Art 2D frontal elbow illustration for elbow joint cross-section and ROM education.",
    sourcePage: "https://smart.servier.com/smart_image/joint-elbow/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/articulation_01.png",
    storagePath: "anatomy/servier/2d/elbow-frontal.png",
    entityType: "joint",
    entitySlug: "elbow-joint",
    entityLinks: [
      { entityType: "joint", entitySlug: "elbow-joint", role: "primary", notes: "Frontal/coronal elbow joint context." },
      { entityType: "anatomy_structure", entitySlug: "articular-cartilage", role: "reference", notes: "Articular cartilage and joint-space context." },
    ],
  },
  {
    slug: "servier-elbow-lateral-2d-illustration",
    title: "Servier Elbow Lateral 2D Illustration",
    description: "Reviewed Servier Medical Art 2D lateral elbow illustration for sagittal elbow anatomy and joint education.",
    sourcePage: "https://smart.servier.com/smart_image/joint-overview/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/articulation_02.png",
    storagePath: "anatomy/servier/2d/elbow-lateral.png",
    entityType: "joint",
    entitySlug: "elbow-joint",
    entityLinks: [
      { entityType: "joint", entitySlug: "elbow-joint", role: "primary", notes: "Lateral/sagittal elbow joint context." },
      { entityType: "anatomy_structure", entitySlug: "joint-capsule", role: "reference", notes: "Capsule and joint-space context for education." },
    ],
  },
  {
    slug: "servier-elbow-posterior-2d-illustration",
    title: "Servier Elbow Posterior 2D Illustration",
    description: "Reviewed Servier Medical Art 2D posterior elbow illustration for posterior elbow ligament and tendon education.",
    sourcePage: "https://smart.servier.com/smart_image/smart-overview-joint/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/articulation_03.png",
    storagePath: "anatomy/servier/2d/elbow-posterior.png",
    entityType: "joint",
    entitySlug: "elbow-joint",
    entityLinks: [
      { entityType: "joint", entitySlug: "elbow-joint", role: "primary", notes: "Posterior elbow joint context." },
      { entityType: "anatomy_structure", entitySlug: "triceps-tendon", role: "reference", notes: "Posterior elbow tendon context for education." },
    ],
  },
  {
    slug: "servier-knee-frontal-2d-illustration",
    title: "Servier Knee Frontal 2D Illustration",
    description: "Reviewed Servier Medical Art 2D frontal knee illustration for knee joint, extensor mechanism, and lower-limb education.",
    sourcePage: "https://smart.servier.com/smart_image/smart-knee-frontal-view/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/articulation_08.png",
    storagePath: "anatomy/servier/2d/knee-frontal.png",
    entityType: "joint",
    entitySlug: "knee-joint",
    entityLinks: [
      { entityType: "joint", entitySlug: "knee-joint", role: "primary", notes: "Primary frontal knee joint education view." },
      { entityType: "bone", entitySlug: "patella", role: "reference", notes: "Patella and anterior knee context." },
      { entityType: "anatomy_structure", entitySlug: "patellar-tendon", role: "reference", notes: "Patellar tendon/extensor mechanism context." },
      { entityType: "anatomy_structure", entitySlug: "quadriceps-tendon", role: "reference", notes: "Quadriceps tendon context for anterior knee education." },
    ],
  },
  {
    slug: "servier-knee-parasagittal-2d-illustration",
    title: "Servier Knee Parasagittal 2D Illustration",
    description: "Reviewed Servier Medical Art 2D parasagittal knee illustration for joint-space, meniscus, cartilage, and ROM education.",
    sourcePage: "https://smart.servier.com/smart_image/knee-parasagittal-section/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/articulation_05.png",
    storagePath: "anatomy/servier/2d/knee-parasagittal.png",
    entityType: "joint",
    entitySlug: "knee-joint",
    entityLinks: [
      { entityType: "joint", entitySlug: "knee-joint", role: "primary", notes: "Parasagittal knee joint context." },
      { entityType: "anatomy_structure", entitySlug: "knee-meniscus", role: "reference", notes: "Meniscus and joint-space context." },
      { entityType: "anatomy_structure", entitySlug: "articular-cartilage", role: "reference", notes: "Cartilage surfaces visible in the knee section." },
    ],
  },
  {
    slug: "servier-knee-posterior-2d-illustration",
    title: "Servier Knee Posterior 2D Illustration",
    description: "Reviewed Servier Medical Art 2D posterior knee illustration for posterior capsule, ligament, and lower-limb education.",
    sourcePage: "https://smart.servier.com/smart_image/knee-posterior-view/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/articulation_07.png",
    storagePath: "anatomy/servier/2d/knee-posterior.png",
    entityType: "joint",
    entitySlug: "knee-joint",
    entityLinks: [
      { entityType: "joint", entitySlug: "knee-joint", role: "primary", notes: "Posterior knee joint education view." },
      { entityType: "ligament", entitySlug: "posterior-cruciate-ligament", role: "reference", notes: "Posterior knee ligament context." },
    ],
  },
  {
    slug: "servier-hand-2d-illustration",
    title: "Servier Hand 2D Illustration",
    description: "Reviewed Servier Medical Art 2D hand illustration for body-map orientation, client education, and hand/wrist anatomy browsing.",
    sourcePage: "https://smart.servier.com/smart_image/hand/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/Main.png",
    storagePath: "anatomy/servier/2d/hand.png",
    entityType: "region",
    entitySlug: "hand",
    entityLinks: [
      { entityType: "region", entitySlug: "hand", role: "primary", notes: "Primary 2D hand body-map orientation image." },
      { entityType: "pain_map_region", entitySlug: "wrist-hand", role: "client_education", notes: "Client-friendly hand and wrist region image." },
      { entityType: "bone", entitySlug: "metacarpals", role: "reference", notes: "Palm-region skeletal context for hand browsing." },
      { entityType: "bone", entitySlug: "hand-phalanges", role: "reference", notes: "Finger-region skeletal context for hand browsing." },
    ],
  },
  {
    slug: "servier-foot-2d-illustration",
    title: "Servier Foot 2D Illustration",
    description: "Reviewed Servier Medical Art 2D foot illustration for body-map orientation, client education, and foot/ankle anatomy browsing.",
    sourcePage: "https://smart.servier.com/smart_image/foot/",
    sourceUrl: "https://smart.servier.com/wp-content/uploads/2016/10/Pied.png",
    storagePath: "anatomy/servier/2d/foot.png",
    entityType: "region",
    entitySlug: "foot",
    entityLinks: [
      { entityType: "region", entitySlug: "foot", role: "primary", notes: "Primary 2D foot body-map orientation image." },
      { entityType: "pain_map_region", entitySlug: "foot-arch", role: "client_education", notes: "Client-friendly foot region image." },
      { entityType: "bone", entitySlug: "metatarsals", role: "reference", notes: "Forefoot skeletal context for foot browsing." },
      { entityType: "bone", entitySlug: "foot-phalanges", role: "reference", notes: "Toe-region skeletal context for foot browsing." },
    ],
  },
] as const

export const MEDIA_SERVIER_LOCOMOTOR_SECTION = {
  mediaAssets: locomotorImages.map((asset) => ({
    id: `media-${asset.slug}`,
    slug: asset.slug,
    title: asset.title,
    mediaType: "image",
    description: asset.description,
    sourceRef: SERVIER_SOURCE,
    sourceUrl: asset.sourceUrl,
    storagePath: asset.storagePath,
    license: "CC BY 4.0",
    licenseUrl: SERVIER_LICENSE_URL,
    attribution: SERVIER_ATTRIBUTION,
    author: "Servier Medical Art",
    usageScope: "open_reuse",
    reviewStatus: "reviewed",
    format: "png",
    metadata: {
      r2Upload: true,
      sourceKind: "servier-2d-education-image",
      sourcePage: asset.sourcePage,
      licenseVerifiedAt: "2026-05-26",
      licensePage: SERVIER_LICENSE_PAGE,
      citationPage: SERVIER_CITATION_PAGE,
      visualStyle: "2d-medical-illustration",
      ingestionStatus: "pending_r2_upload",
    },
  })),
  mediaEntityLinks: locomotorImages.flatMap((asset) => asset.entityLinks.map((link) => ({
    id: `media-link-${asset.slug}-${link.entityType}-${link.entitySlug}-${link.role}`,
    assetSlug: asset.slug,
    entityType: link.entityType,
    entitySlug: link.entitySlug,
    role: link.role,
    notes: link.notes,
  }))),
  citations: locomotorImages.flatMap((asset) => [
    {
      id: `citation-${asset.slug}-media-source`,
      slug: `citation-${asset.slug}-media-source`,
      entityType: asset.entityType,
      entitySlug: asset.entitySlug,
      factType: "media_source",
      factSlug: asset.slug,
      sourceRef: SERVIER_SOURCE,
      sourceLocator: asset.sourcePage,
      citationNote: "Servier Medical Art image page selected for 2D locomotor education media ingestion with stored direct image URL, license, attribution, and R2 upload path.",
      reviewStatus: "reviewed",
    },
    {
      id: `citation-${asset.slug}-media-license`,
      slug: `citation-${asset.slug}-media-license`,
      entityType: asset.entityType,
      entitySlug: asset.entitySlug,
      factType: "media_license",
      factSlug: asset.slug,
      sourceRef: SERVIER_SOURCE,
      sourceLocator: SERVIER_LICENSE_PAGE,
      citationNote: "Servier Medical Art states SMART images are available under CC BY 4.0 and provides attribution guidance for reuse.",
      reviewStatus: "reviewed",
    },
  ]),
} satisfies AnatomySeedSection
