import type { AnatomyCitation, AnatomyConcept, AnatomyEntityTerm } from "../anatomy-foundation.ts"
import type { AnatomySeedSection } from "./sections.ts"

type TermSpec = {
  term: string
  termType: "preferred" | "formal" | "common" | "clinical" | "historical" | "eponym" | "abbreviation" | "alternate"
  sourceRef?: string
  notes?: string
}

type ConceptSpec = AnatomyConcept & {
  locator: string
  terms?: TermSpec[]
}

const PHYSIOLOGY_SOURCE = "openstax-human-biology"
const LOCATOR = "OpenStax CNX Human Biology movement, connective-tissue, and tissue-repair review source; MassageLab-authored summary."

const CONCEPTS: ConceptSpec[] = [
  {
    id: "concept-joint-movement",
    slug: "joint-movement",
    name: "Joint Movement",
    conceptType: "musculoskeletal_function",
    bodySystem: "musculoskeletal",
    description: "Joint movement is motion that occurs at or through an articulation. MassageLab uses the concept to connect ROM values, movement names, muscle actions, and client-friendly movement education.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "arthrokinematics", termType: "clinical" }, { term: "joint motion", termType: "common" }],
  },
  {
    id: "concept-muscle-action",
    slug: "muscle-action",
    name: "Muscle Action",
    conceptType: "musculoskeletal_function",
    bodySystem: "musculoskeletal",
    description: "A muscle action describes how a muscle contributes to movement or stabilization at a joint. The role can vary by position, load, task, and whether the muscle is shortening, lengthening, or holding.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "muscle function", termType: "common" }, { term: "muscular action", termType: "alternate" }],
  },
  {
    id: "concept-force-production",
    slug: "force-production",
    name: "Force Production",
    conceptType: "musculoskeletal_function",
    bodySystem: "musculoskeletal",
    description: "Force production is the generation and transfer of mechanical force by muscle and connective tissue. It helps explain effort, stabilization, movement control, and tissue loading without implying a diagnosis.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "muscle force", termType: "common" }, { term: "force generation", termType: "alternate" }],
  },
  {
    id: "concept-joint-stability",
    slug: "joint-stability",
    name: "Joint Stability",
    conceptType: "musculoskeletal_function",
    bodySystem: "musculoskeletal",
    description: "Joint stability is the ability to maintain controlled joint position during posture or movement. It depends on joint shape, connective tissues, muscle activity, proprioception, and task demands.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "stabilization", termType: "common" }, { term: "dynamic stability", termType: "clinical" }],
  },
  {
    id: "concept-mobility",
    slug: "mobility",
    name: "Mobility",
    conceptType: "musculoskeletal_function",
    bodySystem: "musculoskeletal",
    description: "Mobility is the capacity for controlled movement through available range. It combines joint motion, soft-tissue extensibility, motor control, and the person's ability to use motion in context.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "movement capacity", termType: "common" }, { term: "available motion", termType: "alternate" }],
  },
  {
    id: "concept-postural-control",
    slug: "postural-control",
    name: "Postural Control",
    conceptType: "musculoskeletal_function",
    bodySystem: "nervous",
    description: "Postural control is the coordinated nervous-system and musculoskeletal activity that manages body position against gravity and changing task demands. It supports education about balance, bracing, and efficient movement.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "postural stability", termType: "clinical" }, { term: "body control", termType: "common" }],
  },
  {
    id: "concept-kinetic-chain",
    slug: "kinetic-chain",
    name: "Kinetic Chain",
    conceptType: "musculoskeletal_function",
    bodySystem: "musculoskeletal",
    description: "A kinetic chain is a linked system of body segments where movement or loading in one region can influence another. It helps organize education about whole-body movement patterns.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "movement chain", termType: "common" }, { term: "linked segment movement", termType: "clinical" }],
  },
  {
    id: "concept-open-chain-movement",
    slug: "open-chain-movement",
    name: "Open Chain Movement",
    conceptType: "musculoskeletal_function",
    bodySystem: "musculoskeletal",
    description: "Open chain movement occurs when the distal segment is relatively free to move. The concept helps distinguish isolated limb motion from loaded or fixed-segment movement patterns.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "open kinetic chain", termType: "clinical" }, { term: "free-end movement", termType: "common" }],
  },
  {
    id: "concept-closed-chain-movement",
    slug: "closed-chain-movement",
    name: "Closed Chain Movement",
    conceptType: "musculoskeletal_function",
    bodySystem: "musculoskeletal",
    description: "Closed chain movement occurs when the distal segment is relatively fixed or loaded. It supports education about weight-bearing movement, regional load transfer, and multi-joint coordination.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "closed kinetic chain", termType: "clinical" }, { term: "fixed-end movement", termType: "common" }],
  },
  {
    id: "concept-lever-system",
    slug: "lever-system",
    name: "Lever System",
    conceptType: "musculoskeletal_function",
    bodySystem: "musculoskeletal",
    description: "A lever system describes how bones, joints, and muscles interact mechanically to create or control movement. It is useful for explaining effort, leverage, and why joint position changes muscle demand.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "body lever", termType: "common" }, { term: "musculoskeletal lever", termType: "clinical" }],
  },
  {
    id: "concept-length-tension-relationship",
    slug: "length-tension-relationship",
    name: "Length-Tension Relationship",
    conceptType: "musculoskeletal_function",
    bodySystem: "musculoskeletal",
    description: "The length-tension relationship describes how a muscle's force potential changes with its length. It gives a non-diagnostic framework for discussing posture, stretch, strength, and movement efficiency.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "length tension", termType: "common" }, { term: "muscle length-force relationship", termType: "clinical" }],
  },
  {
    id: "concept-load-transfer",
    slug: "load-transfer",
    name: "Load Transfer",
    conceptType: "musculoskeletal_function",
    bodySystem: "musculoskeletal",
    description: "Load transfer is the movement of force through tissues and body regions. MassageLab uses it to connect fascia, joints, muscles, and posture in a cautious movement-education context.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "force transfer", termType: "common" }, { term: "load transmission", termType: "clinical" }],
  },
  {
    id: "concept-functional-movement",
    slug: "functional-movement",
    name: "Functional Movement",
    conceptType: "musculoskeletal_function",
    bodySystem: "musculoskeletal",
    description: "Functional movement is a movement pattern used in daily activity, work, sport, or self-care. It provides a practical bridge from named anatomy to how a person uses the body.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "task movement", termType: "common" }, { term: "activity movement", termType: "alternate" }],
  },
  {
    id: "concept-motor-learning",
    slug: "motor-learning",
    name: "Motor Learning",
    conceptType: "musculoskeletal_function",
    bodySystem: "nervous",
    description: "Motor learning is practice-related change in movement skill, coordination, or control. It supports anatomy education that separates learning and awareness from claims about treating disease.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "movement learning", termType: "common" }, { term: "skill acquisition", termType: "clinical" }],
  },
  {
    id: "concept-collagen-remodeling",
    slug: "collagen-remodeling",
    name: "Collagen Remodeling",
    conceptType: "tissue_repair",
    bodySystem: "integumentary",
    description: "Collagen remodeling is the ongoing reorganization of collagen during tissue repair and adaptation. It supports careful education about tissue history, load tolerance, and time-based change.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "collagen reorganization", termType: "clinical" }, { term: "tissue remodeling", termType: "common" }],
  },
  {
    id: "concept-granulation-tissue",
    slug: "granulation-tissue",
    name: "Granulation Tissue",
    conceptType: "tissue_repair",
    bodySystem: "integumentary",
    description: "Granulation tissue is new vascular connective tissue associated with repair after tissue injury. MassageLab stores it for broad A&P literacy and scope-aware wound or injury history language.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "repair tissue", termType: "common" }, { term: "new connective tissue", termType: "alternate" }],
  },
  {
    id: "concept-edema",
    slug: "edema",
    name: "Edema",
    conceptType: "tissue_repair",
    bodySystem: "lymphatic",
    description: "Edema is fluid accumulation in tissue spaces. It can appear in many contexts, so MassageLab treats it as anatomy and physiology vocabulary that may require referral rather than a massage diagnosis.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "swelling", termType: "common" }, { term: "fluid accumulation", termType: "clinical" }],
  },
  {
    id: "concept-fibrosis",
    slug: "fibrosis",
    name: "Fibrosis",
    conceptType: "tissue_repair",
    bodySystem: "integumentary",
    description: "Fibrosis is increased fibrous connective tissue in an area. It is included as cautious tissue vocabulary for education and history taking, not as a label assigned from palpation alone.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "fibrotic tissue", termType: "clinical" }, { term: "excess scar-like tissue", termType: "common" }],
  },
  {
    id: "concept-acute-injury",
    slug: "acute-injury",
    name: "Acute Injury",
    conceptType: "tissue_repair",
    bodySystem: "musculoskeletal",
    description: "An acute injury is a recent tissue insult or event. In MassageLab it helps guide safety language, intake questions, and referral awareness without replacing medical evaluation.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "recent injury", termType: "common" }, { term: "acute tissue injury", termType: "clinical" }],
  },
  {
    id: "concept-subacute-repair",
    slug: "subacute-repair",
    name: "Subacute Repair",
    conceptType: "tissue_repair",
    bodySystem: "musculoskeletal",
    description: "Subacute repair describes a middle recovery period after the earliest acute response and before longer-term remodeling is complete. It supports conservative, time-aware education language.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "subacute phase", termType: "common" }, { term: "repair phase", termType: "clinical" }],
  },
  {
    id: "concept-chronic-tissue-change",
    slug: "chronic-tissue-change",
    name: "Chronic Tissue Change",
    conceptType: "tissue_repair",
    bodySystem: "musculoskeletal",
    description: "Chronic tissue change refers to longer-duration changes in tissue tolerance, texture, mobility, or use history. The concept is deliberately broad so therapists avoid over-specific diagnostic claims.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "long-term tissue change", termType: "common" }, { term: "chronic tissue adaptation", termType: "clinical" }],
  },
  {
    id: "concept-tissue-irritability",
    slug: "tissue-irritability",
    name: "Tissue Irritability",
    conceptType: "tissue_repair",
    bodySystem: "musculoskeletal",
    description: "Tissue irritability describes how easily symptoms or protective responses are provoked by load, movement, or pressure. It is a scope-aware observation concept rather than a diagnosis.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "irritable tissue", termType: "common" }, { term: "symptom irritability", termType: "clinical" }],
  },
  {
    id: "concept-tissue-load-tolerance",
    slug: "tissue-load-tolerance",
    name: "Tissue Load Tolerance",
    conceptType: "tissue_repair",
    bodySystem: "musculoskeletal",
    description: "Tissue load tolerance is the amount or type of load a tissue or region appears able to handle comfortably in context. It supports conservative pressure, movement, and referral decisions.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "load tolerance", termType: "common" }, { term: "tissue tolerance", termType: "alternate" }],
  },
  {
    id: "concept-protective-muscle-guarding",
    slug: "protective-muscle-guarding",
    name: "Protective Muscle Guarding",
    conceptType: "tissue_repair",
    bodySystem: "nervous",
    description: "Protective muscle guarding is increased muscle activity that may occur as a protective response to perceived threat, pain, or instability. MassageLab uses it as cautious observation language.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "muscle guarding", termType: "common" }, { term: "protective guarding", termType: "clinical" }],
  },
  {
    id: "concept-contraindication-red-flag",
    slug: "contraindication-red-flag",
    name: "Contraindication Red Flag",
    conceptType: "tissue_repair",
    bodySystem: "general",
    description: "A contraindication red flag is a safety concern that may require avoiding, modifying, postponing, or referring care. It supports clinical reasoning without trying to diagnose the underlying condition.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "red flag", termType: "common" }, { term: "safety concern", termType: "common" }],
  },
  {
    id: "concept-scope-aware-referral",
    slug: "scope-aware-referral",
    name: "Scope-Aware Referral",
    conceptType: "tissue_repair",
    bodySystem: "general",
    description: "Scope-aware referral is the decision to direct a client toward an appropriate licensed professional when findings or history fall outside massage scope. It is a safety and ethics concept.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "refer out", termType: "common" }, { term: "clinical referral", termType: "clinical" }],
  },
]

function termSlug(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")
}

function conceptSeedRecord(concept: ConceptSpec): AnatomyConcept {
  return {
    id: concept.id,
    slug: concept.slug,
    name: concept.name,
    conceptType: concept.conceptType,
    bodySystem: concept.bodySystem,
    description: concept.description,
    sourceRef: concept.sourceRef,
  }
}

function conceptTerms(concept: ConceptSpec): AnatomyEntityTerm[] {
  return [
    {
      id: `term-${concept.slug}-preferred`,
      anatomyEntityType: "anatomy_concept",
      anatomyEntitySlug: concept.slug,
      term: concept.name,
      termType: "preferred",
      sourceRef: concept.sourceRef,
    },
    ...(concept.terms ?? []).map((term): AnatomyEntityTerm => ({
      id: `term-${concept.slug}-${term.termType}-${termSlug(term.term)}`,
      anatomyEntityType: "anatomy_concept",
      anatomyEntitySlug: concept.slug,
      term: term.term,
      termType: term.termType,
      notes: term.notes,
      sourceRef: term.sourceRef ?? concept.sourceRef,
    })),
  ]
}

function conceptCitation(concept: ConceptSpec): AnatomyCitation {
  return {
    id: `citation-concept-${concept.slug}-clinical-summary`,
    slug: `citation-concept-${concept.slug}-clinical-summary`,
    entityType: "anatomy_concept",
    entitySlug: concept.slug,
    factType: "clinical_summary",
    factSlug: `concept:${concept.slug}`,
    sourceRef: concept.sourceRef,
    sourceLocator: concept.locator,
    citationNote: "Reviewed commercial-compatible support for MassageLab-authored movement and tissue-repair concept summary. Do not copy source prose directly.",
    reviewStatus: "reviewed",
  }
}

export const MOVEMENT_TISSUE_CONCEPTS_SECTION: AnatomySeedSection = {
  concepts: CONCEPTS.map(conceptSeedRecord),
  entityTerms: CONCEPTS.flatMap(conceptTerms),
  citations: CONCEPTS.map(conceptCitation),
}
