import type { AnatomySeedSection } from "./sections.ts"

const STARTER_SOURCE = "massagelab-initial-anatomy-foundation"
const FIPAT_SOURCE = "fipat-ta2"
const APPLIED_HUMAN_ANATOMY_SOURCE = "applied-human-anatomy"
const OLS_UBERON_SOURCE = "ols-uberon"
const BIOPORTAL_FMA_SOURCE = "bioportal-fma"
const APPLIED_HUMAN_ANATOMY_LOCATOR = "https://open.umn.edu/opentextbooks/textbooks/1266"

type CitationSeedRows = NonNullable<AnatomySeedSection["citations"]>

const NECK_REVIEWED_MUSCLE_CITATION_SPECS = [
  {
    slug: "longus-colli",
    termFact: "term-longus-colli-preferred-fipat",
    identifierFact: "external-longus-colli-uberon",
    identifierLocator: "UBERON:0001121",
    identifierSourceRef: OLS_UBERON_SOURCE,
    originFact: "attach-longus-colli-origin-cervical-bodies",
    insertionFact: "attach-longus-colli-insertion-atlas",
    actionFact: "action-longus-colli-cervical-flexion",
    innervationFact: "innervation-longus-colli-cervical-plexus",
    officialLocator: "FIPAT TA2: Longus colli",
  },
  {
    slug: "longus-capitis",
    termFact: "term-longus-capitis-preferred-fipat",
    identifierFact: "external-longus-capitis-uberon",
    identifierLocator: "UBERON:0001563",
    identifierSourceRef: OLS_UBERON_SOURCE,
    originFact: "attach-longus-capitis-origin-cervical-transverse",
    insertionFact: "attach-longus-capitis-insertion-occipital",
    actionFact: "action-longus-capitis-cervical-flexion",
    innervationFact: "innervation-longus-capitis-cervical-plexus",
    officialLocator: "FIPAT TA2: Longus capitis",
  },
  {
    slug: "anterior-scalene",
    termFact: "term-anterior-scalene-preferred-fipat",
    identifierFact: "external-anterior-scalene-uberon",
    identifierLocator: "UBERON:0008622",
    identifierSourceRef: OLS_UBERON_SOURCE,
    originFact: "attach-anterior-scalene-origin-cervical-transverse",
    insertionFact: "attach-anterior-scalene-insertion-first-rib",
    actionFact: "action-anterior-scalene-cervical-lateral-flexion",
    innervationFact: "innervation-anterior-scalene-cervical-plexus",
    officialLocator: "FIPAT TA2: Scalenus anterior",
  },
  {
    slug: "middle-scalene",
    termFact: "term-middle-scalene-preferred-fipat",
    identifierFact: "external-middle-scalene-uberon",
    identifierLocator: "UBERON:0001122",
    identifierSourceRef: OLS_UBERON_SOURCE,
    originFact: "attach-middle-scalene-origin-cervical-transverse",
    insertionFact: "attach-middle-scalene-insertion-first-rib",
    actionFact: "action-middle-scalene-cervical-lateral-flexion",
    innervationFact: "innervation-middle-scalene-cervical-plexus",
    officialLocator: "FIPAT TA2: Scalenus medius",
  },
  {
    slug: "posterior-scalene",
    termFact: "term-posterior-scalene-preferred-fipat",
    identifierFact: "external-posterior-scalene-uberon",
    identifierLocator: "UBERON:0001123",
    identifierSourceRef: OLS_UBERON_SOURCE,
    originFact: "attach-posterior-scalene-origin-cervical-transverse",
    insertionFact: "attach-posterior-scalene-insertion-second-rib",
    actionFact: "action-posterior-scalene-rib-elevation",
    innervationFact: "innervation-posterior-scalene-cervical-plexus",
    officialLocator: "FIPAT TA2: Scalenus posterior",
  },
  {
    slug: "rectus-capitis-posterior-major",
    termFact: "term-rcp-major-preferred-fipat",
    identifierFact: "external-rcp-major-uberon",
    identifierLocator: "UBERON:0008454",
    identifierSourceRef: OLS_UBERON_SOURCE,
    originFact: "attach-rcp-major-origin-axis",
    insertionFact: "attach-rcp-major-insertion-occipital",
    actionFact: "action-rcp-major-atlanto-occipital-extension",
    innervationFact: "innervation-rcp-major-suboccipital",
    officialLocator: "FIPAT TA2: Rectus capitis posterior major",
  },
  {
    slug: "rectus-capitis-posterior-minor",
    termFact: "term-rcp-minor-preferred-fipat",
    identifierFact: "external-rcp-minor-uberon",
    identifierLocator: "UBERON:0008455",
    identifierSourceRef: OLS_UBERON_SOURCE,
    originFact: "attach-rcp-minor-origin-atlas",
    insertionFact: "attach-rcp-minor-insertion-occipital",
    actionFact: "action-rcp-minor-atlanto-occipital-extension",
    innervationFact: "innervation-rcp-minor-suboccipital",
    officialLocator: "FIPAT TA2: Rectus capitis posterior minor",
  },
  {
    slug: "obliquus-capitis-superior",
    termFact: "term-ocs-preferred-fipat",
    identifierFact: "external-obliquus-capitis-superior-fma",
    identifierLocator: "FMA:32527",
    identifierSourceRef: BIOPORTAL_FMA_SOURCE,
    originFact: "attach-ocs-origin-atlas",
    insertionFact: "attach-ocs-insertion-occipital",
    actionFact: "action-ocs-atlanto-occipital-extension",
    innervationFact: "innervation-ocs-suboccipital",
    officialLocator: "FIPAT TA2: Obliquus capitis superior",
  },
  {
    slug: "obliquus-capitis-inferior",
    termFact: "term-oci-preferred-fipat",
    identifierFact: "external-obliquus-capitis-inferior-fma",
    identifierLocator: "FMA:32528",
    identifierSourceRef: BIOPORTAL_FMA_SOURCE,
    originFact: "attach-oci-origin-axis",
    insertionFact: "attach-oci-insertion-atlas",
    actionFact: "action-oci-atlantoaxial-rotation",
    innervationFact: "innervation-oci-suboccipital",
    officialLocator: "FIPAT TA2: Obliquus capitis inferior",
  },
] as const

const NECK_REVIEWED_MUSCLE_CITATIONS: CitationSeedRows = NECK_REVIEWED_MUSCLE_CITATION_SPECS.flatMap((spec) => [
  {
    id: `citation-${spec.slug}-fipat-term`,
    slug: `citation-${spec.slug}-fipat-term`,
    entityType: "muscle",
    entitySlug: spec.slug,
    factType: "official_term",
    factSlug: spec.termFact,
    sourceRef: FIPAT_SOURCE,
    sourceLocator: spec.officialLocator,
    citationNote: "FIPAT TA2 official anatomical terminology used for preferred term row.",
    reviewStatus: "reviewed",
  },
  {
    id: `citation-${spec.slug}-external-identifier`,
    slug: `citation-${spec.slug}-external-identifier`,
    entityType: "muscle",
    entitySlug: spec.slug,
    factType: "external_identifier",
    factSlug: spec.identifierFact,
    sourceRef: spec.identifierSourceRef,
    sourceLocator: spec.identifierLocator,
    citationNote: "Ontology identifier used as stable external alignment metadata, not as MassageLab display wording.",
    reviewStatus: "reviewed",
  },
  {
    id: `citation-${spec.slug}-clinical-summary`,
    slug: `citation-${spec.slug}-clinical-summary`,
    entityType: "muscle",
    entitySlug: spec.slug,
    factType: "clinical_summary",
    sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE,
    sourceLocator: APPLIED_HUMAN_ANATOMY_LOCATOR,
    citationNote: "MassageLab-authored summary verified against open-reuse applied anatomy material.",
    reviewStatus: "reviewed",
  },
  {
    id: `citation-${spec.slug}-origin`,
    slug: `citation-${spec.slug}-origin`,
    entityType: "muscle",
    entitySlug: spec.slug,
    factType: "origin",
    factSlug: spec.originFact,
    sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE,
    sourceLocator: APPLIED_HUMAN_ANATOMY_LOCATOR,
    citationNote: "Origin fact verified against open-reuse applied anatomy material.",
    reviewStatus: "reviewed",
  },
  {
    id: `citation-${spec.slug}-insertion`,
    slug: `citation-${spec.slug}-insertion`,
    entityType: "muscle",
    entitySlug: spec.slug,
    factType: "insertion",
    factSlug: spec.insertionFact,
    sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE,
    sourceLocator: APPLIED_HUMAN_ANATOMY_LOCATOR,
    citationNote: "Insertion fact verified against open-reuse applied anatomy material.",
    reviewStatus: "reviewed",
  },
  {
    id: `citation-${spec.slug}-action`,
    slug: `citation-${spec.slug}-action`,
    entityType: "muscle",
    entitySlug: spec.slug,
    factType: "action",
    factSlug: spec.actionFact,
    sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE,
    sourceLocator: APPLIED_HUMAN_ANATOMY_LOCATOR,
    citationNote: "Action fact verified against open-reuse applied anatomy material.",
    reviewStatus: "reviewed",
  },
  {
    id: `citation-${spec.slug}-innervation`,
    slug: `citation-${spec.slug}-innervation`,
    entityType: "muscle",
    entitySlug: spec.slug,
    factType: "innervation",
    factSlug: spec.innervationFact,
    sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE,
    sourceLocator: APPLIED_HUMAN_ANATOMY_LOCATOR,
    citationNote: "Innervation fact verified against open-reuse applied anatomy material.",
    reviewStatus: "reviewed",
  },
])

export const NECK_SHOULDER_UPPER_BACK_SECTION: AnatomySeedSection = {
  boneLandmarks: [
    { id: "landmark-anterior-tubercle-atlas", slug: "anterior-tubercle-atlas", name: "Anterior Tubercle of Atlas", bone: "atlas", description: "Anterior C1 landmark used for deep prevertebral muscle attachment mapping.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "landmark-transverse-process-atlas", slug: "transverse-process-atlas", name: "Transverse Process of Atlas", bone: "atlas", description: "Lateral C1 landmark used by suboccipital muscles and upper cervical rotation mechanics.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "landmark-posterior-tubercle-atlas", slug: "posterior-tubercle-atlas", name: "Posterior Tubercle of Atlas", bone: "atlas", description: "Posterior C1 landmark for rectus capitis posterior minor attachment mapping.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "landmark-basilar-part-occipital", slug: "basilar-part-occipital-bone", name: "Basilar Part of Occipital Bone", bone: "occipital-bone", description: "Anterior occipital landmark used by longus capitis attachment mapping.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "landmark-cervical-vertebral-bodies", slug: "cervical-vertebral-bodies", name: "Cervical Vertebral Bodies", bone: "cervical-vertebrae", description: "Anterior cervical body region used by longus colli attachment mapping.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "landmark-anterior-cervical-transverse-processes", slug: "anterior-cervical-transverse-processes", name: "Anterior Cervical Transverse Processes", bone: "cervical-vertebrae", description: "Anterior tubercle region of cervical transverse processes for prevertebral and scalene attachments.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "landmark-scalene-tubercle-first-rib", slug: "scalene-tubercle-first-rib", name: "Scalene Tubercle of First Rib", bone: "ribs", description: "First rib landmark associated with anterior scalene insertion and thoracic inlet anatomy.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "landmark-second-rib", slug: "second-rib", name: "Second Rib", bone: "ribs", description: "Second rib attachment region for posterior scalene mapping.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
  ],
  muscles: [
    {
      id: "muscle-longus-colli",
      slug: "longus-colli",
      name: "Longus Colli",
      formalName: "Longus colli",
      alternateNames: ["longus colli muscle", "deep front neck flexor", "prevertebral neck flexor"],
      description: "Longus colli is a deep prevertebral neck muscle lying along the anterior cervical spine. It assists cervical flexion, segmental stabilization, and subtle side-bending control.",
      region: "neck",
      relativeDepth: "deep",
      depthNotes: "Deep to sternocleidomastoid, infrahyoid soft tissues, and visceral neck structures.",
      sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE,
    },
    {
      id: "muscle-longus-capitis",
      slug: "longus-capitis",
      name: "Longus Capitis",
      formalName: "Longus capitis",
      alternateNames: ["longus capitis muscle", "deep head flexor", "prevertebral head flexor"],
      description: "Longus capitis is a deep anterior upper cervical muscle running from cervical transverse processes to the occipital base. It helps flex the head and stabilize the upper neck.",
      region: "neck",
      relativeDepth: "deep",
      depthNotes: "Deep to sternocleidomastoid and anterior cervical fascia in the prevertebral layer.",
      sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE,
    },
    {
      id: "muscle-anterior-scalene",
      slug: "anterior-scalene",
      name: "Anterior Scalene",
      formalName: "Scalenus anterior",
      alternateNames: ["scalenus anterior", "side neck breathing muscle", "anterior scalene muscle"],
      description: "Anterior scalene is a lateral neck muscle from cervical transverse processes to the first rib. It contributes to cervical side bending and can assist first-rib elevation during breathing mechanics.",
      region: "lateral-neck",
      relativeDepth: "intermediate",
      depthNotes: "Deep to sternocleidomastoid and anterior to the brachial plexus within the scalene region.",
      sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE,
    },
    {
      id: "muscle-middle-scalene",
      slug: "middle-scalene",
      name: "Middle Scalene",
      formalName: "Scalenus medius",
      alternateNames: ["scalenus medius", "middle scalene muscle", "side neck stabilizer"],
      description: "Middle scalene is a lateral cervical muscle descending from cervical transverse processes to the first rib. It assists cervical side bending, rib elevation, and scalene triangle context.",
      region: "lateral-neck",
      relativeDepth: "intermediate",
      depthNotes: "Posterior to the brachial plexus passage and deep to more superficial lateral neck tissues.",
      sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE,
    },
    {
      id: "muscle-posterior-scalene",
      slug: "posterior-scalene",
      name: "Posterior Scalene",
      formalName: "Scalenus posterior",
      alternateNames: ["scalenus posterior", "posterior scalene muscle", "deep side neck rib lifter"],
      description: "Posterior scalene is a small posterior member of the scalene group attaching from lower cervical transverse processes to the second rib. It assists rib elevation and lateral neck control.",
      region: "lateral-neck",
      relativeDepth: "deep",
      depthNotes: "Deep to trapezius and levator scapulae in the posterior-lateral neck region.",
      sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE,
    },
    {
      id: "muscle-rcp-major",
      slug: "rectus-capitis-posterior-major",
      name: "Rectus Capitis Posterior Major",
      formalName: "Rectus capitis posterior major",
      alternateNames: ["large posterior rectus capitis", "small base of skull muscles", "RCP major"],
      description: "Rectus capitis posterior major is a small deep suboccipital muscle from the axis spinous process to the occipital bone. It assists upper cervical extension and ipsilateral rotation.",
      region: "base-of-skull",
      relativeDepth: "deep",
      depthNotes: "Deep to semispinalis capitis and superficial posterior neck muscles.",
      sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE,
    },
    {
      id: "muscle-rcp-minor",
      slug: "rectus-capitis-posterior-minor",
      name: "Rectus Capitis Posterior Minor",
      formalName: "Rectus capitis posterior minor",
      alternateNames: ["small posterior rectus capitis", "suboccipital stabilizer", "RCP minor"],
      description: "Rectus capitis posterior minor is a small deep suboccipital muscle from the posterior atlas to the occipital bone. It helps fine-control atlanto-occipital extension and head position.",
      region: "base-of-skull",
      relativeDepth: "deep",
      depthNotes: "Deep in the suboccipital layer beneath larger posterior neck extensors.",
      sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE,
    },
    {
      id: "muscle-obliquus-capitis-superior",
      slug: "obliquus-capitis-superior",
      name: "Obliquus Capitis Superior",
      formalName: "Obliquus capitis superior",
      alternateNames: ["superior oblique capitis", "suboccipital head extender"],
      description: "Obliquus capitis superior is a small suboccipital muscle from the atlas transverse process to the occipital bone. It assists upper cervical extension and fine head positioning.",
      region: "base-of-skull",
      relativeDepth: "deep",
      depthNotes: "Forms the superolateral border of the suboccipital triangle region.",
      sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE,
    },
    {
      id: "muscle-obliquus-capitis-inferior",
      slug: "obliquus-capitis-inferior",
      name: "Obliquus Capitis Inferior",
      formalName: "Obliquus capitis inferior",
      alternateNames: ["inferior oblique capitis", "head rotation at atlas axis"],
      description: "Obliquus capitis inferior is a deep suboccipital muscle from the axis spinous process to the atlas transverse process. It is a key contributor to atlantoaxial rotation.",
      region: "base-of-skull",
      relativeDepth: "deep",
      depthNotes: "Forms the inferolateral border of the suboccipital triangle and lies deep to semispinalis capitis.",
      sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE,
    },
  ],
  muscleAttachments: [
    { id: "attach-longus-colli-origin-cervical-bodies", muscle: "longus-colli", type: "origin", bone: "cervical-vertebrae", landmark: "cervical-vertebral-bodies", description: "Anterior bodies and transverse process regions of lower and middle cervical vertebrae.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "attach-longus-colli-insertion-atlas", muscle: "longus-colli", type: "insertion", bone: "atlas", landmark: "anterior-tubercle-atlas", description: "Anterior tubercle of the atlas and adjacent upper cervical anterior vertebral region.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "attach-longus-capitis-origin-cervical-transverse", muscle: "longus-capitis", type: "origin", bone: "cervical-vertebrae", landmark: "anterior-cervical-transverse-processes", description: "Anterior tubercles of cervical transverse processes, especially mid-cervical levels.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "attach-longus-capitis-insertion-occipital", muscle: "longus-capitis", type: "insertion", bone: "occipital-bone", landmark: "basilar-part-occipital-bone", description: "Basilar part of the occipital bone anterior to the foramen magnum region.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "attach-anterior-scalene-origin-cervical-transverse", muscle: "anterior-scalene", type: "origin", bone: "cervical-vertebrae", landmark: "anterior-cervical-transverse-processes", description: "Anterior tubercles of cervical transverse processes.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "attach-anterior-scalene-insertion-first-rib", muscle: "anterior-scalene", type: "insertion", bone: "ribs", landmark: "scalene-tubercle-first-rib", description: "Scalene tubercle and superior surface of the first rib.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "attach-middle-scalene-origin-cervical-transverse", muscle: "middle-scalene", type: "origin", bone: "cervical-vertebrae", landmark: "cervical-transverse-processes", description: "Posterior tubercle region of cervical transverse processes.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "attach-middle-scalene-insertion-first-rib", muscle: "middle-scalene", type: "insertion", bone: "ribs", landmark: "first-rib", description: "Superior surface of the first rib posterior to the subclavian groove region.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "attach-posterior-scalene-origin-cervical-transverse", muscle: "posterior-scalene", type: "origin", bone: "cervical-vertebrae", landmark: "cervical-transverse-processes", description: "Posterior tubercle region of lower cervical transverse processes.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "attach-posterior-scalene-insertion-second-rib", muscle: "posterior-scalene", type: "insertion", bone: "ribs", landmark: "second-rib", description: "Outer surface of the second rib.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "attach-rcp-major-origin-axis", muscle: "rectus-capitis-posterior-major", type: "origin", bone: "axis", landmark: "axis-spinous-process", description: "Spinous process of the axis.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "attach-rcp-major-insertion-occipital", muscle: "rectus-capitis-posterior-major", type: "insertion", bone: "occipital-bone", landmark: "inferior-nuchal-line", description: "Lateral part of the inferior nuchal line region.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "attach-rcp-minor-origin-atlas", muscle: "rectus-capitis-posterior-minor", type: "origin", bone: "atlas", landmark: "posterior-tubercle-atlas", description: "Posterior tubercle of the atlas.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "attach-rcp-minor-insertion-occipital", muscle: "rectus-capitis-posterior-minor", type: "insertion", bone: "occipital-bone", landmark: "inferior-nuchal-line", description: "Medial part of the inferior nuchal line region.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "attach-ocs-origin-atlas", muscle: "obliquus-capitis-superior", type: "origin", bone: "atlas", landmark: "transverse-process-atlas", description: "Transverse process of the atlas.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "attach-ocs-insertion-occipital", muscle: "obliquus-capitis-superior", type: "insertion", bone: "occipital-bone", landmark: "inferior-nuchal-line", description: "Occipital bone between the nuchal line regions.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "attach-oci-origin-axis", muscle: "obliquus-capitis-inferior", type: "origin", bone: "axis", landmark: "axis-spinous-process", description: "Spinous process of the axis.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "attach-oci-insertion-atlas", muscle: "obliquus-capitis-inferior", type: "insertion", bone: "atlas", landmark: "transverse-process-atlas", description: "Transverse process of the atlas.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
  ],
  muscleActions: [
    { id: "action-longus-colli-cervical-flexion", muscle: "longus-colli", joint: "cervical-spine", movement: "cervical-flexion", role: "primary", contractionType: "concentric", description: "Flexes the cervical spine and supports segmental anterior neck control.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "action-longus-colli-cervical-lateral-flexion", muscle: "longus-colli", joint: "cervical-spine", movement: "cervical-lateral-flexion", role: "stabilizer", contractionType: "isometric", description: "Supports subtle side-bending and segmental stabilization of the cervical spine.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "action-longus-capitis-cervical-flexion", muscle: "longus-capitis", joint: "cervical-spine", movement: "cervical-flexion", role: "primary", contractionType: "concentric", description: "Flexes the head and upper cervical region from the occipital base toward the cervical spine.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "action-anterior-scalene-cervical-lateral-flexion", muscle: "anterior-scalene", joint: "cervical-spine", movement: "cervical-lateral-flexion", role: "primary", contractionType: "concentric", description: "Laterally flexes the cervical spine on the same side when the rib attachment is controlled.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "action-anterior-scalene-rib-elevation", muscle: "anterior-scalene", joint: "cervical-spine", movement: "rib-elevation", role: "secondary", contractionType: "concentric", description: "Assists elevation of the first rib during accessory breathing mechanics.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "action-middle-scalene-cervical-lateral-flexion", muscle: "middle-scalene", joint: "cervical-spine", movement: "cervical-lateral-flexion", role: "primary", contractionType: "concentric", description: "Laterally flexes the cervical spine and helps stabilize the lateral neck.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "action-middle-scalene-rib-elevation", muscle: "middle-scalene", joint: "cervical-spine", movement: "rib-elevation", role: "secondary", contractionType: "concentric", description: "Assists first-rib elevation and thoracic inlet breathing mechanics.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "action-posterior-scalene-cervical-lateral-flexion", muscle: "posterior-scalene", joint: "cervical-spine", movement: "cervical-lateral-flexion", role: "secondary", contractionType: "concentric", description: "Assists cervical side bending from the posterior scalene line of pull.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "action-posterior-scalene-rib-elevation", muscle: "posterior-scalene", joint: "cervical-spine", movement: "rib-elevation", role: "secondary", contractionType: "concentric", description: "Assists elevation of the second rib during accessory breathing mechanics.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "action-rcp-major-atlanto-occipital-extension", muscle: "rectus-capitis-posterior-major", joint: "atlanto-occipital", movement: "atlanto-occipital-extension", role: "primary", contractionType: "concentric", description: "Extends the head at the upper cervical region.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "action-rcp-major-cervical-rotation", muscle: "rectus-capitis-posterior-major", joint: "cervical-spine", movement: "cervical-rotation", role: "secondary", contractionType: "concentric", description: "Assists ipsilateral upper cervical rotation as part of the suboccipital group.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "action-rcp-minor-atlanto-occipital-extension", muscle: "rectus-capitis-posterior-minor", joint: "atlanto-occipital", movement: "atlanto-occipital-extension", role: "stabilizer", contractionType: "isometric", description: "Supports fine extension and stabilization at the atlanto-occipital region.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "action-ocs-atlanto-occipital-extension", muscle: "obliquus-capitis-superior", joint: "atlanto-occipital", movement: "atlanto-occipital-extension", role: "secondary", contractionType: "concentric", description: "Assists upper cervical extension and subtle lateral head positioning.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "action-oci-atlantoaxial-rotation", muscle: "obliquus-capitis-inferior", joint: "atlantoaxial", movement: "atlantoaxial-rotation", role: "primary", contractionType: "concentric", description: "Rotates the atlas on the axis and contributes strongly to same-side upper cervical rotation.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "action-oci-cervical-rotation", muscle: "obliquus-capitis-inferior", joint: "cervical-spine", movement: "cervical-rotation", role: "secondary", contractionType: "concentric", description: "Assists head rotation at the atlas-axis region within broader cervical rotation.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
  ],
  muscleInnervations: [
    { id: "innervation-longus-colli-cervical-plexus", muscle: "longus-colli", nerve: "cervical-plexus", description: "Anterior rami of cervical spinal nerves commonly grouped with cervical plexus contributions.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "innervation-longus-capitis-cervical-plexus", muscle: "longus-capitis", nerve: "cervical-plexus", description: "Anterior rami of cervical spinal nerves commonly grouped with cervical plexus contributions.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "innervation-anterior-scalene-cervical-plexus", muscle: "anterior-scalene", nerve: "cervical-plexus", description: "Cervical spinal nerve contributions to the lateral neck scalene group.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "innervation-middle-scalene-cervical-plexus", muscle: "middle-scalene", nerve: "cervical-plexus", description: "Cervical spinal nerve contributions to the lateral neck scalene group.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "innervation-posterior-scalene-cervical-plexus", muscle: "posterior-scalene", nerve: "cervical-plexus", description: "Cervical spinal nerve contributions to the lateral neck scalene group.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "innervation-rcp-major-suboccipital", muscle: "rectus-capitis-posterior-major", nerve: "suboccipital-nerve", description: "Suboccipital nerve, the dorsal ramus of C1.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "innervation-rcp-minor-suboccipital", muscle: "rectus-capitis-posterior-minor", nerve: "suboccipital-nerve", description: "Suboccipital nerve, the dorsal ramus of C1.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "innervation-ocs-suboccipital", muscle: "obliquus-capitis-superior", nerve: "suboccipital-nerve", description: "Suboccipital nerve, the dorsal ramus of C1.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "innervation-oci-suboccipital", muscle: "obliquus-capitis-inferior", nerve: "suboccipital-nerve", description: "Suboccipital nerve, the dorsal ramus of C1.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
  ],
  bloodSupply: [
    { id: "blood-ascending-cervical-artery", slug: "ascending-cervical-artery", name: "Ascending Cervical Artery", kind: "artery", region: "neck", description: "Cervical arterial branch used as a regional supply reference for deep prevertebral and lateral neck muscles.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "blood-occipital-artery", slug: "occipital-artery", name: "Occipital Artery", kind: "artery", region: "base-of-skull", description: "Posterior head and upper neck artery used as a regional supply reference for suboccipital tissues.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
  ],
  structures: [
    { id: "structure-prevertebral-muscle-group", slug: "prevertebral-muscle-group", name: "Prevertebral Muscle Group", structureType: "muscle_group", region: "neck", description: "Deep anterior cervical muscle group including longus colli and longus capitis for flexion and segmental stabilization mapping.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "structure-scalene-triangle", slug: "scalene-triangle", name: "Scalene Triangle", structureType: "neurovascular_space", region: "lateral-neck", description: "Lateral neck interval between anterior and middle scalene muscles through which the brachial plexus and subclavian artery region pass.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "structure-suboccipital-triangle", slug: "suboccipital-triangle", name: "Suboccipital Triangle", structureType: "muscle_triangle", region: "base-of-skull", description: "Deep posterior upper cervical triangle bordered by rectus capitis posterior major and obliquus capitis muscles.", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
  ],
  clientTerms: [
    { id: "client-term-deep-front-neck-tightness", slug: "deep-front-neck-tightness", term: "deep front neck tightness", plainLanguageDescription: "Client phrase for deep anterior cervical tightness or throat-side neck tension.", mappedRegionSlug: "neck", mappedMuscleSlug: "longus-colli", confidence: "likely", clinicalUse: "non-diagnostic", likelyRegions: ["neck"], likelyStructures: ["longus-colli", "longus-capitis", "prevertebral-muscle-group"], therapistPrompt: "Clarify location, swallowing or breathing concerns, red flags, and whether motion changes the sensation.", sourceRef: STARTER_SOURCE },
    { id: "client-term-side-neck-breathing-muscle-tightness", slug: "side-neck-breathing-muscle-tightness", term: "side neck breathing muscle tightness", plainLanguageDescription: "Client phrase for lateral neck tightness around the scalene region.", mappedRegionSlug: "lateral-neck", mappedMuscleSlug: "anterior-scalene", confidence: "likely", clinicalUse: "non-diagnostic", likelyRegions: ["lateral-neck", "neck", "top-of-shoulder"], likelyStructures: ["anterior-scalene", "middle-scalene", "scalene-triangle"], therapistPrompt: "Clarify side, breathing effort, arm symptoms, and exact point of tension before choosing structures.", sourceRef: STARTER_SOURCE },
    { id: "client-term-base-of-skull-tiny-muscles", slug: "base-of-skull-tiny-muscles", term: "base of skull tiny muscles", plainLanguageDescription: "Client phrase for small deep muscles under the occipital ridge.", mappedRegionSlug: "base-of-skull", mappedMuscleSlug: "rectus-capitis-posterior-major", confidence: "likely", clinicalUse: "non-diagnostic", likelyRegions: ["base-of-skull", "posterior-neck"], likelyStructures: ["rectus-capitis-posterior-major", "rectus-capitis-posterior-minor", "suboccipital-triangle"], therapistPrompt: "Clarify exact base-of-skull location, headache red flags, dizziness, and response to upper cervical movement.", sourceRef: STARTER_SOURCE },
    { id: "client-term-under-skull-rotation-tightness", slug: "under-skull-rotation-tightness", term: "under skull rotation tightness", plainLanguageDescription: "Client phrase for upper cervical tightness noticed with head turning.", mappedRegionSlug: "base-of-skull", mappedMuscleSlug: "obliquus-capitis-inferior", confidence: "likely", clinicalUse: "non-diagnostic", likelyRegions: ["base-of-skull", "posterior-neck"], likelyStructures: ["obliquus-capitis-inferior", "atlantoaxial", "suboccipital-triangle"], therapistPrompt: "Clarify which direction of rotation, dizziness or neurological symptoms, and whether referral is appropriate.", sourceRef: STARTER_SOURCE },
  ],
  entityTerms: [
    { id: "term-longus-colli-preferred-fipat", anatomyEntityType: "muscle", anatomyEntitySlug: "longus-colli", term: "Longus colli", termType: "preferred", sourceRef: FIPAT_SOURCE },
    { id: "term-longus-colli-common-deep-front-neck-flexor", anatomyEntityType: "muscle", anatomyEntitySlug: "longus-colli", term: "deep front neck flexor", termType: "common", sourceRef: STARTER_SOURCE },
    { id: "term-longus-capitis-preferred-fipat", anatomyEntityType: "muscle", anatomyEntitySlug: "longus-capitis", term: "Longus capitis", termType: "preferred", sourceRef: FIPAT_SOURCE },
    { id: "term-longus-capitis-common-deep-head-flexor", anatomyEntityType: "muscle", anatomyEntitySlug: "longus-capitis", term: "deep head flexor", termType: "common", sourceRef: STARTER_SOURCE },
    { id: "term-anterior-scalene-preferred-fipat", anatomyEntityType: "muscle", anatomyEntitySlug: "anterior-scalene", term: "Scalenus anterior", termType: "preferred", sourceRef: FIPAT_SOURCE },
    { id: "term-anterior-scalene-common-side-neck-breathing", anatomyEntityType: "muscle", anatomyEntitySlug: "anterior-scalene", term: "side neck breathing muscle", termType: "common", sourceRef: STARTER_SOURCE },
    { id: "term-middle-scalene-preferred-fipat", anatomyEntityType: "muscle", anatomyEntitySlug: "middle-scalene", term: "Scalenus medius", termType: "preferred", sourceRef: FIPAT_SOURCE },
    { id: "term-middle-scalene-common", anatomyEntityType: "muscle", anatomyEntitySlug: "middle-scalene", term: "middle scalene", termType: "common", sourceRef: STARTER_SOURCE },
    { id: "term-posterior-scalene-preferred-fipat", anatomyEntityType: "muscle", anatomyEntitySlug: "posterior-scalene", term: "Scalenus posterior", termType: "preferred", sourceRef: FIPAT_SOURCE },
    { id: "term-posterior-scalene-common", anatomyEntityType: "muscle", anatomyEntitySlug: "posterior-scalene", term: "posterior scalene", termType: "common", sourceRef: STARTER_SOURCE },
    { id: "term-rcp-major-preferred-fipat", anatomyEntityType: "muscle", anatomyEntitySlug: "rectus-capitis-posterior-major", term: "Rectus capitis posterior major", termType: "preferred", sourceRef: FIPAT_SOURCE },
    { id: "term-rcp-major-common-small-base-skull", anatomyEntityType: "muscle", anatomyEntitySlug: "rectus-capitis-posterior-major", term: "small base of skull muscles", termType: "common", sourceRef: STARTER_SOURCE },
    { id: "term-rcp-minor-preferred-fipat", anatomyEntityType: "muscle", anatomyEntitySlug: "rectus-capitis-posterior-minor", term: "Rectus capitis posterior minor", termType: "preferred", sourceRef: FIPAT_SOURCE },
    { id: "term-rcp-minor-common", anatomyEntityType: "muscle", anatomyEntitySlug: "rectus-capitis-posterior-minor", term: "small posterior rectus capitis", termType: "common", sourceRef: STARTER_SOURCE },
    { id: "term-ocs-preferred-fipat", anatomyEntityType: "muscle", anatomyEntitySlug: "obliquus-capitis-superior", term: "Obliquus capitis superior", termType: "preferred", sourceRef: FIPAT_SOURCE },
    { id: "term-ocs-common", anatomyEntityType: "muscle", anatomyEntitySlug: "obliquus-capitis-superior", term: "suboccipital head extender", termType: "common", sourceRef: STARTER_SOURCE },
    { id: "term-oci-preferred-fipat", anatomyEntityType: "muscle", anatomyEntitySlug: "obliquus-capitis-inferior", term: "Obliquus capitis inferior", termType: "preferred", sourceRef: FIPAT_SOURCE },
    { id: "term-oci-common-head-rotation", anatomyEntityType: "muscle", anatomyEntitySlug: "obliquus-capitis-inferior", term: "head rotation at atlas axis", termType: "common", sourceRef: STARTER_SOURCE },
    { id: "term-prevertebral-muscle-group-common", anatomyEntityType: "anatomy_structure", anatomyEntitySlug: "prevertebral-muscle-group", term: "prevertebral muscles", termType: "common", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "term-scalene-triangle-common", anatomyEntityType: "anatomy_structure", anatomyEntitySlug: "scalene-triangle", term: "scalene triangle", termType: "common", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "term-suboccipital-triangle-common", anatomyEntityType: "anatomy_structure", anatomyEntitySlug: "suboccipital-triangle", term: "suboccipital triangle", termType: "common", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
  ],
  relationships: [
    { id: "relationship-longus-colli-part-of-prevertebral-group", sourceEntityType: "muscle", sourceEntitySlug: "longus-colli", relationshipType: "part_of", targetEntityType: "anatomy_structure", targetEntitySlug: "prevertebral-muscle-group", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "relationship-longus-capitis-part-of-prevertebral-group", sourceEntityType: "muscle", sourceEntitySlug: "longus-capitis", relationshipType: "part_of", targetEntityType: "anatomy_structure", targetEntitySlug: "prevertebral-muscle-group", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "relationship-anterior-scalene-forms-scalene-triangle", sourceEntityType: "muscle", sourceEntitySlug: "anterior-scalene", relationshipType: "forms_boundary_of", targetEntityType: "anatomy_structure", targetEntitySlug: "scalene-triangle", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "relationship-middle-scalene-forms-scalene-triangle", sourceEntityType: "muscle", sourceEntitySlug: "middle-scalene", relationshipType: "forms_boundary_of", targetEntityType: "anatomy_structure", targetEntitySlug: "scalene-triangle", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "relationship-scalene-triangle-contains-brachial-plexus", sourceEntityType: "anatomy_structure", sourceEntitySlug: "scalene-triangle", relationshipType: "contains", targetEntityType: "nerve", targetEntitySlug: "brachial-plexus", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "relationship-scalene-triangle-contains-subclavian-artery", sourceEntityType: "anatomy_structure", sourceEntitySlug: "scalene-triangle", relationshipType: "contains", targetEntityType: "blood_supply", targetEntitySlug: "subclavian-artery", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "relationship-longus-colli-deep-to-scm", sourceEntityType: "muscle", sourceEntitySlug: "longus-colli", relationshipType: "deep_to", targetEntityType: "muscle", targetEntitySlug: "sternocleidomastoid", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "relationship-sternocleidomastoid-superficial-to-longus-colli", sourceEntityType: "muscle", sourceEntitySlug: "sternocleidomastoid", relationshipType: "superficial_to", targetEntityType: "muscle", targetEntitySlug: "longus-colli", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "relationship-rcp-major-part-of-suboccipital-group", sourceEntityType: "muscle", sourceEntitySlug: "rectus-capitis-posterior-major", relationshipType: "part_of", targetEntityType: "muscle", targetEntitySlug: "suboccipital-muscles", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "relationship-rcp-minor-part-of-suboccipital-group", sourceEntityType: "muscle", sourceEntitySlug: "rectus-capitis-posterior-minor", relationshipType: "part_of", targetEntityType: "muscle", targetEntitySlug: "suboccipital-muscles", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "relationship-ocs-part-of-suboccipital-group", sourceEntityType: "muscle", sourceEntitySlug: "obliquus-capitis-superior", relationshipType: "part_of", targetEntityType: "muscle", targetEntitySlug: "suboccipital-muscles", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "relationship-oci-part-of-suboccipital-group", sourceEntityType: "muscle", sourceEntitySlug: "obliquus-capitis-inferior", relationshipType: "part_of", targetEntityType: "muscle", targetEntitySlug: "suboccipital-muscles", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "relationship-rcp-major-forms-suboccipital-triangle", sourceEntityType: "muscle", sourceEntitySlug: "rectus-capitis-posterior-major", relationshipType: "forms_boundary_of", targetEntityType: "anatomy_structure", targetEntitySlug: "suboccipital-triangle", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "relationship-ocs-forms-suboccipital-triangle", sourceEntityType: "muscle", sourceEntitySlug: "obliquus-capitis-superior", relationshipType: "forms_boundary_of", targetEntityType: "anatomy_structure", targetEntitySlug: "suboccipital-triangle", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "relationship-oci-forms-suboccipital-triangle", sourceEntityType: "muscle", sourceEntitySlug: "obliquus-capitis-inferior", relationshipType: "forms_boundary_of", targetEntityType: "anatomy_structure", targetEntitySlug: "suboccipital-triangle", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "relationship-ascending-cervical-supplies-prevertebral-group", sourceEntityType: "blood_supply", sourceEntitySlug: "ascending-cervical-artery", relationshipType: "supplies", targetEntityType: "anatomy_structure", targetEntitySlug: "prevertebral-muscle-group", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
    { id: "relationship-occipital-artery-supplies-suboccipital-triangle", sourceEntityType: "blood_supply", sourceEntitySlug: "occipital-artery", relationshipType: "supplies", targetEntityType: "anatomy_structure", targetEntitySlug: "suboccipital-triangle", sourceRef: APPLIED_HUMAN_ANATOMY_SOURCE },
  ],
  externalIdentifiers: [
    { id: "external-longus-colli-uberon", entityType: "muscle", entitySlug: "longus-colli", provider: "UBERON", identifier: "UBERON:0001121", iri: "http://purl.obolibrary.org/obo/UBERON_0001121", label: "longus colli muscle", sourceRef: OLS_UBERON_SOURCE },
    { id: "external-longus-capitis-uberon", entityType: "muscle", entitySlug: "longus-capitis", provider: "UBERON", identifier: "UBERON:0001563", iri: "http://purl.obolibrary.org/obo/UBERON_0001563", label: "longus capitis muscle", sourceRef: OLS_UBERON_SOURCE },
    { id: "external-anterior-scalene-uberon", entityType: "muscle", entitySlug: "anterior-scalene", provider: "UBERON", identifier: "UBERON:0008622", iri: "http://purl.obolibrary.org/obo/UBERON_0008622", label: "scalenus anterior", sourceRef: OLS_UBERON_SOURCE },
    { id: "external-middle-scalene-uberon", entityType: "muscle", entitySlug: "middle-scalene", provider: "UBERON", identifier: "UBERON:0001122", iri: "http://purl.obolibrary.org/obo/UBERON_0001122", label: "scalenus medius", sourceRef: OLS_UBERON_SOURCE },
    { id: "external-posterior-scalene-uberon", entityType: "muscle", entitySlug: "posterior-scalene", provider: "UBERON", identifier: "UBERON:0001123", iri: "http://purl.obolibrary.org/obo/UBERON_0001123", label: "scalenus posterior", sourceRef: OLS_UBERON_SOURCE },
    { id: "external-rcp-major-uberon", entityType: "muscle", entitySlug: "rectus-capitis-posterior-major", provider: "UBERON", identifier: "UBERON:0008454", iri: "http://purl.obolibrary.org/obo/UBERON_0008454", label: "rectus capitis posterior major", sourceRef: OLS_UBERON_SOURCE },
    { id: "external-rcp-minor-uberon", entityType: "muscle", entitySlug: "rectus-capitis-posterior-minor", provider: "UBERON", identifier: "UBERON:0008455", iri: "http://purl.obolibrary.org/obo/UBERON_0008455", label: "rectus capitis posterior minor", sourceRef: OLS_UBERON_SOURCE },
    { id: "external-obliquus-capitis-superior-fma", entityType: "muscle", entitySlug: "obliquus-capitis-superior", provider: "FMA", identifier: "FMA:32527", iri: "http://purl.org/sig/ont/fma/fma32527", label: "Obliquus capitis superior", sourceRef: BIOPORTAL_FMA_SOURCE },
    { id: "external-obliquus-capitis-inferior-fma", entityType: "muscle", entitySlug: "obliquus-capitis-inferior", provider: "FMA", identifier: "FMA:32528", iri: "http://purl.org/sig/ont/fma/fma32528", label: "Obliquus capitis inferior", sourceRef: BIOPORTAL_FMA_SOURCE },
  ],
  citations: [
    ...NECK_REVIEWED_MUSCLE_CITATIONS,
  ],
}
