import type { AnatomyCitation, AnatomyConcept, AnatomyEntityTerm } from "../anatomy-foundation.ts"
import type { AnatomySeedSection } from "./sections.ts"

type ConceptSpec = AnatomyConcept & {
  locator: string
  terms?: Array<{
    term: string
    termType: "preferred" | "formal" | "common" | "clinical" | "historical" | "eponym" | "abbreviation" | "alternate"
    sourceRef?: string
    notes?: string
  }>
}

const PHYSIOLOGY_SOURCE = "openstax-human-biology"
const NCI_SOURCE = "nci-thesaurus"
const LOCATOR = "OpenStax CNX Human Biology physiology review source; MassageLab-authored summary."

const CONCEPTS: ConceptSpec[] = [
  {
    id: "concept-skeletal-muscle-fiber",
    slug: "skeletal-muscle-fiber",
    name: "Skeletal Muscle Fiber",
    conceptType: "muscle_component",
    bodySystem: "musculoskeletal",
    description: "A skeletal muscle fiber is a long contractile muscle cell organized into myofibrils. It is the cellular unit therapists reference when teaching muscle contraction, tone, fatigue, and recovery.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "muscle cell", termType: "common" }, { term: "skeletal muscle cell", termType: "clinical" }],
  },
  {
    id: "concept-muscle-fascicle",
    slug: "muscle-fascicle",
    name: "Muscle Fascicle",
    conceptType: "muscle_component",
    bodySystem: "musculoskeletal",
    description: "A muscle fascicle is a bundle of muscle fibers wrapped by connective tissue. Fascicle direction helps explain muscle shape, force direction, and why some muscles pull at different angles.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "fascicle", termType: "common" }, { term: "muscle bundle", termType: "common" }],
  },
  {
    id: "concept-motor-unit",
    slug: "motor-unit",
    name: "Motor Unit",
    conceptType: "muscle_component",
    bodySystem: "nervous",
    description: "A motor unit is a motor neuron and the skeletal muscle fibers it controls. It links nervous-system signaling with muscle force, coordination, and graded contraction.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "motor neuron unit", termType: "alternate" }],
  },
  {
    id: "concept-neuromuscular-junction",
    slug: "neuromuscular-junction",
    name: "Neuromuscular Junction",
    conceptType: "muscle_component",
    bodySystem: "nervous",
    description: "The neuromuscular junction is the contact region where a motor neuron communicates with a skeletal muscle fiber. It explains how nerve impulses initiate muscle contraction.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "NMJ", termType: "abbreviation" }, { term: "motor end plate", termType: "alternate" }],
  },
  {
    id: "concept-sarcomere",
    slug: "sarcomere",
    name: "Sarcomere",
    conceptType: "muscle_component",
    bodySystem: "musculoskeletal",
    description: "A sarcomere is the repeating contractile unit inside skeletal muscle. It provides the microscopic basis for muscle shortening, lengthening under load, and resting tone.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "contractile unit", termType: "common" }],
  },
  {
    id: "concept-actin-myosin-filaments",
    slug: "actin-myosin-filaments",
    name: "Actin and Myosin Filaments",
    conceptType: "muscle_component",
    bodySystem: "musculoskeletal",
    description: "Actin and myosin are the main protein filaments that slide past one another during skeletal muscle contraction. This concept supports client-friendly explanations of contraction and relaxation.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "sliding filaments", termType: "common" }],
  },
  {
    id: "concept-concentric-contraction",
    slug: "concentric-contraction",
    name: "Concentric Contraction",
    conceptType: "muscle_contraction",
    bodySystem: "musculoskeletal",
    description: "A concentric contraction occurs when a muscle produces force while shortening. It is useful for describing the lifting or accelerating portion of a movement.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "shortening contraction", termType: "common" }],
  },
  {
    id: "concept-eccentric-contraction",
    slug: "eccentric-contraction",
    name: "Eccentric Contraction",
    conceptType: "muscle_contraction",
    bodySystem: "musculoskeletal",
    description: "An eccentric contraction occurs when a muscle produces force while lengthening. It is useful for describing controlled lowering, deceleration, and loaded stretch contexts.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "lengthening contraction", termType: "common" }],
  },
  {
    id: "concept-isometric-contraction",
    slug: "isometric-contraction",
    name: "Isometric Contraction",
    conceptType: "muscle_contraction",
    bodySystem: "musculoskeletal",
    description: "An isometric contraction occurs when a muscle produces force without visible joint movement. It is used in stabilization, holding postures, and resisted assessment contexts.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "static contraction", termType: "common" }],
  },
  {
    id: "concept-agonist-muscle-role",
    slug: "agonist-muscle-role",
    name: "Agonist Muscle Role",
    conceptType: "muscle_contraction",
    bodySystem: "musculoskeletal",
    description: "An agonist is the muscle or muscle group chiefly responsible for producing a movement in a specific context. The role can change with joint position and task.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "prime mover", termType: "common" }],
  },
  {
    id: "concept-antagonist-muscle-role",
    slug: "antagonist-muscle-role",
    name: "Antagonist Muscle Role",
    conceptType: "muscle_contraction",
    bodySystem: "musculoskeletal",
    description: "An antagonist is a muscle that can oppose, control, or balance an agonist movement. It helps explain coordinated motion, braking, and reciprocal muscle activity.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "opposing muscle", termType: "common" }],
  },
  {
    id: "concept-synergist-muscle-role",
    slug: "synergist-muscle-role",
    name: "Synergist Muscle Role",
    conceptType: "muscle_contraction",
    bodySystem: "musculoskeletal",
    description: "A synergist assists another muscle in producing or refining a movement. This concept supports game prompts and education about shared muscle actions.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "helper muscle", termType: "common" }],
  },
  {
    id: "concept-stabilizer-muscle-role",
    slug: "stabilizer-muscle-role",
    name: "Stabilizer Muscle Role",
    conceptType: "muscle_contraction",
    bodySystem: "musculoskeletal",
    description: "A stabilizer helps hold a body part steady while other structures move. It is important for explaining scapular, spinal, pelvic, and postural control.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "fixator", termType: "alternate" }],
  },
  {
    id: "concept-muscle-spindle",
    slug: "muscle-spindle",
    name: "Muscle Spindle",
    conceptType: "proprioception",
    bodySystem: "nervous",
    description: "A muscle spindle is a sensory receptor in skeletal muscle that helps detect stretch and changes in muscle length. It supports proprioception and stretch-reflex education.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "proprioceptor", termType: "common", sourceRef: NCI_SOURCE }, { term: "stretch receptor", termType: "common" }],
  },
  {
    id: "concept-golgi-tendon-organ",
    slug: "golgi-tendon-organ",
    name: "Golgi Tendon Organ",
    conceptType: "proprioception",
    bodySystem: "nervous",
    description: "A Golgi tendon organ is a sensory receptor associated with tendon that helps detect tension. It contributes to body awareness and reflex regulation of muscle force.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "GTO", termType: "abbreviation" }, { term: "tendon organ", termType: "alternate" }],
  },
  {
    id: "concept-joint-mechanoreceptor",
    slug: "joint-mechanoreceptor",
    name: "Joint Mechanoreceptor",
    conceptType: "proprioception",
    bodySystem: "nervous",
    description: "Joint mechanoreceptors are sensory receptors associated with joint tissues that respond to mechanical change. They contribute to movement awareness and joint-position sense.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "joint receptor", termType: "common" }],
  },
  {
    id: "concept-proprioception",
    slug: "proprioception",
    name: "Proprioception",
    conceptType: "proprioception",
    bodySystem: "nervous",
    description: "Proprioception is the body's sense of position and movement. It depends on sensory input from muscles, tendons, joints, and the nervous system.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "body position sense", termType: "common" }, { term: "joint position sense", termType: "clinical" }],
  },
  {
    id: "concept-stretch-reflex",
    slug: "stretch-reflex",
    name: "Stretch Reflex",
    conceptType: "proprioception",
    bodySystem: "nervous",
    description: "The stretch reflex is a nervous-system response to sudden muscle stretch. It is relevant to muscle tone, guarding language, and client-friendly explanations of quick stretch responses.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "myotatic reflex", termType: "clinical" }],
  },
  {
    id: "concept-active-range-of-motion",
    slug: "active-range-of-motion",
    name: "Active Range of Motion",
    conceptType: "range_of_motion",
    bodySystem: "musculoskeletal",
    description: "Active range of motion is movement produced by the client using their own muscle activity. It helps distinguish voluntary movement capacity from passive tissue motion.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "AROM", termType: "abbreviation" }],
  },
  {
    id: "concept-passive-range-of-motion",
    slug: "passive-range-of-motion",
    name: "Passive Range of Motion",
    conceptType: "range_of_motion",
    bodySystem: "musculoskeletal",
    description: "Passive range of motion is movement applied by an outside force while the client remains relaxed. It helps separate joint or soft-tissue motion from active muscle control.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "PROM", termType: "abbreviation" }],
  },
  {
    id: "concept-resisted-range-of-motion",
    slug: "resisted-range-of-motion",
    name: "Resisted Range of Motion",
    conceptType: "range_of_motion",
    bodySystem: "musculoskeletal",
    description: "Resisted range of motion asks the client to move or hold against resistance. It gives non-diagnostic information about muscle participation, comfort, and force tolerance.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "RROM", termType: "abbreviation" }, { term: "resisted movement", termType: "common" }],
  },
  {
    id: "concept-inflammation",
    slug: "inflammation",
    name: "Inflammation",
    conceptType: "tissue_repair",
    bodySystem: "immune",
    description: "Inflammation is a protective tissue response involving immune activity, fluid changes, and chemical signaling. It belongs in education as context, not as a diagnosis from massage assessment alone.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "inflammatory response", termType: "clinical" }],
  },
  {
    id: "concept-hemostasis",
    slug: "hemostasis",
    name: "Hemostasis",
    conceptType: "tissue_repair",
    bodySystem: "cardiovascular",
    description: "Hemostasis is the process that limits bleeding after tissue injury. In the dataset it supports broad tissue-repair education and contraindication-aware language.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "clotting response", termType: "common" }],
  },
  {
    id: "concept-proliferative-repair-phase",
    slug: "proliferative-repair-phase",
    name: "Proliferative Repair Phase",
    conceptType: "tissue_repair",
    bodySystem: "integumentary",
    description: "The proliferative repair phase is a broad healing period involving new tissue formation and wound closure processes. MassageLab uses it as education context, not client diagnosis.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "proliferation phase", termType: "common" }],
  },
  {
    id: "concept-remodeling-repair-phase",
    slug: "remodeling-repair-phase",
    name: "Remodeling Repair Phase",
    conceptType: "tissue_repair",
    bodySystem: "integumentary",
    description: "The remodeling repair phase is a broad healing period in which collagen organization and tissue strength continue to change. It supports cautious education about tissue adaptation over time.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "maturation phase", termType: "alternate" }],
  },
  {
    id: "concept-tissue-repair",
    slug: "tissue-repair",
    name: "Tissue Repair",
    conceptType: "tissue_repair",
    bodySystem: "integumentary",
    description: "Tissue repair describes the broad biological process of restoring tissue integrity after injury. The concept is used for education and source mapping, not for making diagnostic claims.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "healing process", termType: "common" }],
  },
  {
    id: "concept-scar-tissue",
    slug: "scar-tissue",
    name: "Scar Tissue",
    conceptType: "tissue_repair",
    bodySystem: "integumentary",
    description: "Scar tissue is connective tissue formed during repair after tissue damage. It should be discussed carefully as a tissue history and education concept rather than a diagnosis made from appearance alone.",
    sourceRef: PHYSIOLOGY_SOURCE,
    locator: LOCATOR,
    terms: [{ term: "fibrotic tissue", termType: "clinical" }],
  },
]

function termSlug(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")
}

function conceptSeedRecord(concept: ConceptSpec): AnatomyConcept {
  return {
    id: concept.id,
    slug: concept.slug,
    name: concept.name,
    conceptType: concept.conceptType,
    bodySystem: concept.bodySystem,
    description: concept.description,
    sourceRef: concept.sourceRef,
  }
}

function conceptTerms(concept: ConceptSpec): AnatomyEntityTerm[] {
  return [
    {
      id: `term-${concept.slug}-preferred`,
      anatomyEntityType: "anatomy_concept",
      anatomyEntitySlug: concept.slug,
      term: concept.name,
      termType: "preferred",
      sourceRef: concept.sourceRef,
    },
    ...(concept.terms ?? []).map((term): AnatomyEntityTerm => ({
      id: `term-${concept.slug}-${term.termType}-${termSlug(term.term)}`,
      anatomyEntityType: "anatomy_concept",
      anatomyEntitySlug: concept.slug,
      term: term.term,
      termType: term.termType,
      notes: term.notes,
      sourceRef: term.sourceRef ?? concept.sourceRef,
    })),
  ]
}

function conceptCitation(concept: ConceptSpec): AnatomyCitation {
  return {
    id: `citation-concept-${concept.slug}-clinical-summary`,
    slug: `citation-concept-${concept.slug}-clinical-summary`,
    entityType: "anatomy_concept",
    entitySlug: concept.slug,
    factType: "clinical_summary",
    factSlug: `concept:${concept.slug}`,
    sourceRef: concept.sourceRef,
    sourceLocator: concept.locator,
    citationNote: "Reviewed commercial-compatible physiology support for MassageLab-authored concept summary. Do not copy source prose directly.",
    reviewStatus: "reviewed",
  }
}

export const PHYSIOLOGY_CONCEPTS_CORE_SECTION: AnatomySeedSection = {
  concepts: CONCEPTS.map(conceptSeedRecord),
  entityTerms: CONCEPTS.flatMap(conceptTerms),
  citations: CONCEPTS.map(conceptCitation),
}
