import type { AnatomySeedSection } from "./sections.ts"

export const SOURCES_SEED_SECTION: AnatomySeedSection = {
  sources: [
    {
      id: "source-wikidata-anatomy",
      slug: "wikidata-anatomy",
      name: "Wikidata anatomy identifiers",
      url: "https://www.wikidata.org/",
      license: "CC0 1.0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      usageScope: "open_reuse",
      accessedAt: "2026-05-22T00:00:00.000Z",
      attribution: "Wikidata structured anatomy identifiers and labels.",
      sourceRef: "Open linked-data identifier source for future cross-references.",
    },
    {
      id: "source-cdc-normal-joint-rom",
      slug: "cdc-normal-joint-rom",
      name: "CDC Normal Joint Range of Motion Public Use Dataset",
      url: "https://stacks.cdc.gov/view/cdc/153156",
      license: "Public domain",
      licenseUrl: "https://www.cdc.gov/other/agencymaterials.html",
      usageScope: "open_reuse",
      accessedAt: "2026-05-23T00:00:00.000Z",
      attribution: "Centers for Disease Control and Prevention, Public Use Dataset for Normal Joint Range of Motion.",
      sourceRef: "Public-domain reference dataset and measurement-method source for non-diagnostic ROM tracking values.",
    },
    {
      id: "source-openstax-human-biology",
      slug: "openstax-human-biology",
      name: "OpenStax CNX Human Biology",
      url: "https://open.umn.edu/opentextbooks/textbooks/576",
      license: "CC BY",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      usageScope: "open_reuse",
      accessedAt: "2026-05-23T00:00:00.000Z",
      notes: "Commercial-compatible physiology reference used to support MassageLab-authored concept summaries. Do not copy source prose directly.",
      attribution: "OpenStax CNX, Human Biology, listed by Open Textbook Library under a Creative Commons Attribution license.",
      sourceRef: "Open physiology reference for reviewed concept summaries and MBLEx A&P coverage mapping.",
    },
    {
      id: "source-servier-medical-art",
      slug: "servier-medical-art",
      name: "Servier Medical Art",
      url: "https://smart.servier.com/",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      usageScope: "open_reuse",
      accessedAt: "2026-05-26T00:00:00.000Z",
      notes: "Commercial-compatible 2D medical illustration source. Store exact image page, direct source URL, license URL, and attribution on every imported asset.",
      attribution: "Image provided by Servier Medical Art (https://smart.servier.com/), licensed under CC BY 4.0.",
      sourceRef: "Reviewed commercial-safe 2D anatomy and physiology illustration source for client education, flashcards, and body-system summaries.",
    },
    {
      id: "source-bodyparts3d-stl-github-mirror",
      slug: "bodyparts3d-stl-github-mirror",
      name: "Kevin Mattheus Moerman BodyParts3D STL Mirror",
      url: "https://github.com/Kevin-Mattheus-Moerman/BodyParts3D",
      license: "CC BY-SA 2.1 Japan for derived geometry; MIT for repository code",
      licenseUrl: "https://github.com/Kevin-Mattheus-Moerman/BodyParts3D/blob/main/LICENSE_content",
      usageScope: "review_only",
      accessedAt: "2026-05-26T00:00:00.000Z",
      notes: "Review-only 3D candidate. The repository README states the geometry is derived from BodyParts3D/Anatomography 3.0 and uses CC BY-SA 2.1 Japan; ShareAlike implications must be reviewed before product use.",
      attribution: "BodyParts3D, (c) The Database Center for Life Science licensed under CC Attribution-Share Alike 2.1 Japan; Kevin Mattheus Moerman GitHub mirror.",
      sourceRef: "Candidate source for future STL/3D anatomy media, not marked open_reuse until ShareAlike product implications are accepted.",
    },
    {
      id: "source-wikimedia-bodyparts3d-stl-category",
      slug: "wikimedia-bodyparts3d-stl-category",
      name: "Wikimedia Commons STL files from BodyParts3D Category",
      url: "https://commons.wikimedia.org/wiki/Category:STL_files_from_BodyParts3D",
      license: "Per-file Wikimedia Commons license review required",
      licenseUrl: "https://commons.wikimedia.org/wiki/Commons:Licensing",
      usageScope: "review_only",
      accessedAt: "2026-05-26T00:00:00.000Z",
      notes: "Review-only 3D candidate. Per-file Wikimedia STL pages must be checked for source, author, exact license, attribution, and ShareAlike requirements before ingestion.",
      attribution: "Wikimedia Commons contributors; per-file attribution required before use.",
      sourceRef: "Candidate source for future STL/3D anatomy media with per-file provenance review.",
    },
    {
      id: "source-massagelab-authored-client-language",
      slug: "massagelab-authored-client-language",
      name: "MassageLab Authored Client Language, Body Map, and Search Terminology Metadata",
      license: "MassageLab-authored proprietary data",
      usageScope: "commercial_licensed",
      accessedAt: "2026-05-23T00:00:00.000Z",
      notes: "Use for MassageLab-authored client-friendly body-map labels, non-diagnostic phrase mappings, common search terminology, abbreviations, and internally reviewed body-map overlap metadata.",
      attribution: "MassageLab authored client-language, search terminology, and body-map taxonomy.",
      sourceRef: "MassageLab-owned client-language, search terminology, and body-map mapping source for commercial product use.",
    },
    {
      id: "source-massagelab-authored-rom-tracking",
      slug: "massagelab-authored-rom-tracking",
      name: "MassageLab Authored ROM Tracking Protocol Metadata",
      license: "MassageLab-authored proprietary data",
      usageScope: "commercial_licensed",
      accessedAt: "2026-05-24T00:00:00.000Z",
      notes: "Use for non-diagnostic tracking protocol metadata, ordinal observation scales, and MassageLab-authored measurement-position guidance. Do not use as an external clinical authority.",
      attribution: "MassageLab authored ROM tracking protocol metadata.",
      sourceRef: "MassageLab-owned ROM tracking metadata for commercial product use.",
    },
    {
      id: "source-massagelab-authored-3d-body-map-protocol",
      slug: "massagelab-authored-3d-body-map-protocol",
      name: "MassageLab Authored 3D Body Map Interaction Protocol",
      license: "MassageLab-authored proprietary data",
      usageScope: "commercial_licensed",
      accessedAt: "2026-05-27T00:00:00.000Z",
      notes: "Use for MassageLab-authored 3D interaction metadata, model coordinate conventions, selectable target semantics, palpation target flags, body-map hit-zone mapping, and ROM visualization anchors. This is not an external clinical authority.",
      attribution: "MassageLab authored 3D body-map interaction metadata.",
      sourceRef: "MassageLab-owned 3D body-map and ROM visualization metadata for commercial product use.",
    },
    {
      id: "source-massagelab-authored-energetic-anatomy",
      slug: "massagelab-authored-energetic-anatomy",
      name: "MassageLab Authored Energetic Anatomy Taxonomy",
      license: "MassageLab-authored proprietary data",
      usageScope: "commercial_licensed",
      accessedAt: "2026-05-24T00:00:00.000Z",
      notes: "Use for non-diagnostic exam-alignment labels and education prompts about energetic anatomy traditions. Keep distinct from clinical anatomy facts.",
      attribution: "MassageLab authored energetic-anatomy taxonomy for non-diagnostic education and exam coverage mapping.",
      sourceRef: "MassageLab-owned energetic-anatomy concept taxonomy for commercial product use.",
    },
    {
      id: "source-mblex-content-outline",
      slug: "mblex-content-outline",
      name: "FSMTB MBLEx Content Outline",
      url: "https://fsmtb.org/wp-content/uploads/2025/12/MBLEx-Content-Outline.pdf",
      license: "Copyright FSMTB; reference only",
      usageScope: "internal_reference",
      accessedAt: "2026-05-23T00:00:00.000Z",
      notes: "Use only as an internal curriculum coverage reference. Do not reuse FSMTB outline wording as MassageLab display copy.",
      attribution: "Federation of State Massage Therapy Boards, Massage & Bodywork Licensing Examination Content Outline.",
      sourceRef: "Internal reference for MBLEx coverage alignment, not a reusable anatomy content source.",
    },
  ],
}
