import type {
  AnatomyCitation,
  AnatomyMovementVisualization,
  AnatomySpatialEntityMap,
} from "../anatomy-foundation.ts"
import type { AnatomySeedSection } from "./sections.ts"

const BODY_PARTS_3D_SOURCE = "bodyparts3d"
const BODY_PARTS_3D_LICENSE_URL = "https://dbarchive.biosciencedbc.jp/en/bodyparts3d/lic.html"
const BODY_PARTS_3D_ATTRIBUTION = "BodyParts3D, © The Database Center for Life Science licensed under CC Attribution 4.0 International."
const SPATIAL_PROTOCOL_SOURCE = "massagelab-authored-3d-body-map-protocol"
const BODY_MAP_MODEL_SLUG = "massagelab-human-bodymap-v1"
const BODY_MAP_MODEL_ASSET_SLUG = "bodyparts3d-runtime-human-glb-candidate"

const spatialMaps: AnatomySpatialEntityMap[] = [
  {
    id: "spatial-map-v1-region-body-surface",
    slug: "massagelab-human-bodymap-v1-region-body-surface",
    modelSlug: BODY_MAP_MODEL_SLUG,
    entityType: "region",
    entitySlug: "body-surface",
    label: "Whole body surface",
    mappingPrecision: "region_context",
    laterality: "bilateral",
    surface: "variable",
    selectable: true,
    palpationTarget: false,
    painSelectionTarget: true,
    notes: "Top-level selectable body-map surface for client pain selection before narrowing to a more specific region.",
    metadata: { interactionModes: ["client_pain_selection", "therapist_region_browse"] },
    sourceRef: SPATIAL_PROTOCOL_SOURCE,
    reviewStatus: "needs_review",
  },
  {
    id: "spatial-map-v1-pain-top-of-shoulder",
    slug: "massagelab-human-bodymap-v1-pain-map-region-top-of-shoulder",
    modelSlug: BODY_MAP_MODEL_SLUG,
    entityType: "pain_map_region",
    entitySlug: "top-of-shoulder",
    label: "Top of shoulder",
    mappingPrecision: "region_context",
    bodyparts3dPartIds: ["FMA33642"],
    laterality: "variable",
    surface: "superior",
    selectable: true,
    palpationTarget: true,
    painSelectionTarget: true,
    notes: "Broad shoulder-cap region target; exact muscle selection should click through to upper trapezius, levator scapulae, deltoid, and shoulder-girdle structures.",
    metadata: { clientLanguage: ["top of shoulder", "shoulder cap"], preferredCamera: "upper_oblique" },
    sourceRef: SPATIAL_PROTOCOL_SOURCE,
    reviewStatus: "needs_review",
  },
  {
    id: "spatial-map-v1-pain-base-of-skull",
    slug: "massagelab-human-bodymap-v1-pain-map-region-base-of-skull",
    modelSlug: BODY_MAP_MODEL_SLUG,
    entityType: "pain_map_region",
    entitySlug: "base-of-skull",
    label: "Base of skull",
    mappingPrecision: "region_context",
    bodyparts3dPartIds: ["FMA7154", "FMA7155"],
    laterality: "midline",
    surface: "posterior",
    selectable: true,
    palpationTarget: true,
    painSelectionTarget: true,
    notes: "Posterior head-neck border target for client language; exact therapist selection should resolve to suboccipital, occipital, upper cervical, and posterior neck structures.",
    metadata: { clientLanguage: ["base of skull", "under skull"], preferredCamera: "posterior_upper" },
    sourceRef: SPATIAL_PROTOCOL_SOURCE,
    reviewStatus: "needs_review",
  },
  {
    id: "spatial-map-v1-pain-low-back",
    slug: "massagelab-human-bodymap-v1-pain-map-region-low-back",
    modelSlug: BODY_MAP_MODEL_SLUG,
    entityType: "pain_map_region",
    entitySlug: "low-back",
    label: "Low back",
    mappingPrecision: "region_context",
    laterality: "midline",
    surface: "posterior",
    selectable: true,
    palpationTarget: true,
    painSelectionTarget: true,
    notes: "Broad lumbar-region body-map target for low-back client language and SOAP tagging.",
    metadata: { clientLanguage: ["low back", "lower back"], preferredCamera: "posterior" },
    sourceRef: SPATIAL_PROTOCOL_SOURCE,
    reviewStatus: "needs_review",
  },
  {
    id: "spatial-map-v1-muscle-biceps-brachii",
    slug: "massagelab-human-bodymap-v1-muscle-biceps-brachii",
    modelSlug: BODY_MAP_MODEL_SLUG,
    entityType: "muscle",
    entitySlug: "biceps-brachii",
    label: "Biceps brachii",
    mappingPrecision: "exact",
    bodyparts3dPartIds: ["FMA37682", "FMA37683"],
    laterality: "bilateral",
    surface: "anterior",
    selectable: true,
    palpationTarget: true,
    painSelectionTarget: false,
    notes: "Exact BodyParts3D head-level mapping used for therapist structure selection and flashcard/game highlighting.",
    metadata: { visibleFrom: ["anterior", "lateral"], targetUse: ["palpation_selection", "education_highlight", "game_prompt"] },
    sourceRef: BODY_PARTS_3D_SOURCE,
    reviewStatus: "needs_review",
  },
  {
    id: "spatial-map-v1-muscle-deltoid",
    slug: "massagelab-human-bodymap-v1-muscle-deltoid",
    modelSlug: BODY_MAP_MODEL_SLUG,
    entityType: "muscle",
    entitySlug: "deltoid",
    label: "Deltoid",
    mappingPrecision: "exact",
    bodyparts3dPartIds: ["FMA34677", "FMA34678", "FMA34679"],
    laterality: "bilateral",
    surface: "lateral",
    selectable: true,
    palpationTarget: true,
    painSelectionTarget: false,
    notes: "Composite exact mapping to clavicular, acromial, and spinal parts of deltoid.",
    metadata: { visibleFrom: ["anterior", "lateral", "posterior"], targetUse: ["palpation_selection", "rom_context", "education_highlight"] },
    sourceRef: BODY_PARTS_3D_SOURCE,
    reviewStatus: "needs_review",
  },
  {
    id: "spatial-map-v1-bone-scapula",
    slug: "massagelab-human-bodymap-v1-bone-scapula",
    modelSlug: BODY_MAP_MODEL_SLUG,
    entityType: "bone",
    entitySlug: "scapula",
    label: "Scapula",
    mappingPrecision: "exact",
    bodyparts3dPartIds: ["FMA13394"],
    laterality: "bilateral",
    surface: "posterior",
    selectable: true,
    palpationTarget: true,
    painSelectionTarget: false,
    notes: "Scapula 3D target for muscle attachment browsing, body-map orientation, and shoulder education.",
    metadata: { visibleFrom: ["posterior", "lateral"], targetUse: ["attachment_browse", "palpation_landmarking"] },
    sourceRef: BODY_PARTS_3D_SOURCE,
    reviewStatus: "needs_review",
  },
  {
    id: "spatial-map-v1-joint-glenohumeral",
    slug: "massagelab-human-bodymap-v1-joint-glenohumeral",
    modelSlug: BODY_MAP_MODEL_SLUG,
    entityType: "joint",
    entitySlug: "glenohumeral",
    label: "Glenohumeral joint",
    mappingPrecision: "landmark",
    laterality: "bilateral",
    surface: "deep",
    selectable: true,
    palpationTarget: false,
    painSelectionTarget: false,
    notes: "Deep joint target represented by shoulder center landmarking; future model should bind this to humeral head and glenoid nodes.",
    metadata: { runtimeAnchor: "shoulder_joint_center", visibleFrom: ["anterior", "lateral", "posterior"], targetUse: ["rom_visualization", "joint_detail"] },
    sourceRef: SPATIAL_PROTOCOL_SOURCE,
    reviewStatus: "needs_review",
  },
  {
    id: "spatial-map-v1-structure-thoracolumbar-fascia",
    slug: "massagelab-human-bodymap-v1-anatomy-structure-thoracolumbar-fascia",
    modelSlug: BODY_MAP_MODEL_SLUG,
    entityType: "anatomy_structure",
    entitySlug: "thoracolumbar-fascia",
    label: "Thoracolumbar fascia",
    mappingPrecision: "broad_context",
    laterality: "midline",
    surface: "posterior",
    selectable: true,
    palpationTarget: true,
    painSelectionTarget: false,
    notes: "Broad posterior fascial target until a reviewed fascia-specific mesh or overlay is available.",
    metadata: { overlayType: "semi_transparent_surface", targetUse: ["palpation_selection", "education_highlight"] },
    sourceRef: SPATIAL_PROTOCOL_SOURCE,
    reviewStatus: "needs_review",
  },
]

const movementVisualizations: AnatomyMovementVisualization[] = [
  {
    id: "movement-viz-human-bodymap-v1-shoulder-abduction",
    slug: "massagelab-human-bodymap-v1-shoulder-abduction",
    modelSlug: BODY_MAP_MODEL_SLUG,
    joint: "glenohumeral",
    movement: "shoulder-abduction",
    rangeOfMotion: "shoulder-abduction",
    primaryEntityType: "joint",
    primaryEntitySlug: "glenohumeral",
    motionAxis: { coordinateSpace: "local", axis: [0, 0, 1], positiveDirection: "humerus abducts away from trunk in the frontal plane" },
    plane: "frontal",
    neutralPose: { shoulderAbductionDegrees: 0, elbowFlexionDegrees: 0, forearmRotation: "neutral" },
    startDegrees: 0,
    endDegrees: 180,
    notes: "ROM visualization anchor for showing measured shoulder abduction against typical values; not diagnostic.",
    metadata: { displayUse: ["rom_tracking", "client_education"], requiresRuntimeRig: true },
    sourceRef: SPATIAL_PROTOCOL_SOURCE,
    reviewStatus: "needs_review",
  },
  {
    id: "movement-viz-human-bodymap-v1-cervical-rotation",
    slug: "massagelab-human-bodymap-v1-cervical-rotation",
    modelSlug: BODY_MAP_MODEL_SLUG,
    joint: "cervical-spine",
    movement: "cervical-rotation",
    rangeOfMotion: "cervical-rotation",
    primaryEntityType: "joint",
    primaryEntitySlug: "cervical-spine",
    motionAxis: { coordinateSpace: "local", axis: [0, 1, 0], positiveDirection: "head rotates left or right around a vertical cervical axis" },
    plane: "transverse",
    neutralPose: { cervicalRotationDegrees: 0, cervicalFlexionDegrees: 0 },
    startDegrees: 0,
    endDegrees: 90,
    notes: "ROM visualization anchor for per-side cervical rotation comparisons against typical values; not diagnostic.",
    metadata: { displayUse: ["rom_tracking", "client_education"], requiresRuntimeRig: true },
    sourceRef: SPATIAL_PROTOCOL_SOURCE,
    reviewStatus: "needs_review",
  },
]

function spatialMapCitation(map: AnatomySpatialEntityMap): AnatomyCitation {
  return {
    id: `citation-${map.slug}-spatial-entity-mapping`,
    slug: `citation-${map.slug}-spatial-entity-mapping`,
    entityType: map.entityType,
    entitySlug: map.entitySlug,
    factType: "spatial_entity_mapping",
    factSlug: map.slug,
    sourceRef: map.sourceRef,
    sourceLocator: map.sourceRef === BODY_PARTS_3D_SOURCE ? BODY_PARTS_3D_LICENSE_URL : "MassageLab authored 3D body-map interaction protocol.",
    citationNote: "3D body-map spatial mapping candidate. Keep as needs_review until runtime mesh/node names are confirmed against the final GLB.",
    reviewStatus: map.reviewStatus,
  }
}

function movementVisualizationCitation(visualization: AnatomyMovementVisualization): AnatomyCitation {
  return {
    id: `citation-${visualization.slug}-movement-visualization`,
    slug: `citation-${visualization.slug}-movement-visualization`,
    entityType: "joint_movement",
    entitySlug: visualization.movement,
    factType: "movement_visualization_protocol",
    factSlug: visualization.slug,
    sourceRef: visualization.sourceRef,
    sourceLocator: "MassageLab authored 3D ROM visualization protocol.",
    citationNote: "3D ROM visualization metadata candidate for future rigging. It describes display semantics, not a diagnostic protocol.",
    reviewStatus: visualization.reviewStatus,
  }
}

export const SPATIAL_BODY_MAP_FOUNDATION_SECTION: AnatomySeedSection = {
  mediaAssets: [
    {
      id: `media-${BODY_MAP_MODEL_ASSET_SLUG}`,
      slug: BODY_MAP_MODEL_ASSET_SLUG,
      title: "BodyParts3D Runtime Human GLB Candidate",
      mediaType: "model_3d",
      description: "Review-only future runtime model candidate for a MassageLab 3D body-map engine. Store as a model candidate until BodyParts3D geometry is converted, optimized, and node names are verified.",
      sourceRef: BODY_PARTS_3D_SOURCE,
      sourceUrl: "https://dbarchive.biosciencedbc.jp/en/bodyparts3d/",
      remoteUrl: "https://dbarchive.biosciencedbc.jp/en/bodyparts3d/",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      attribution: BODY_PARTS_3D_ATTRIBUTION,
      author: "Database Center for Life Science",
      usageScope: "review_only",
      reviewStatus: "needs_review",
      format: "glb",
      metadata: {
        candidateFor: "future_3d_body_map_engine",
        sourceKind: "bodyparts3d-geometry-candidate",
        targetRuntimeFormat: "glb",
        pipelineStatus: "conversion_and_optimization_pending",
        preferredOptimization: ["gltf-transform", "meshopt"],
        r2Upload: false,
      },
    },
  ],
  mediaEntityLinks: [
    {
      id: `media-link-${BODY_MAP_MODEL_ASSET_SLUG}-region-body-surface-reference`,
      assetSlug: BODY_MAP_MODEL_ASSET_SLUG,
      entityType: "region",
      entitySlug: "body-surface",
      role: "reference",
      notes: "Future 3D model candidate linked to the whole body surface until runtime GLB files and exact mesh/node mappings are reviewed.",
    },
  ],
  spatialModels: [
    {
      id: `spatial-model-${BODY_MAP_MODEL_SLUG}`,
      slug: BODY_MAP_MODEL_SLUG,
      name: "MassageLab Human Body Map V1",
      description: "Future 3D body-map model contract for therapist palpation selection, client pain selection, anatomy education, games, and ROM visualization.",
      mediaAssetSlug: BODY_MAP_MODEL_ASSET_SLUG,
      sourceRef: SPATIAL_PROTOCOL_SOURCE,
      coordinateSystem: "right-handed-y-up",
      unit: "meter",
      forwardAxis: "-Z",
      upAxis: "Y",
      scaleToMeters: 1,
      defaultCamera: {
        position: [0, 1.45, 3.2],
        target: [0, 1.25, 0],
        fieldOfViewDegrees: 35,
      },
      interactionNotes: "Selectable entities should resolve by stable MassageLab entity slugs first, then runtime mesh/node names once a GLB is finalized.",
      usageScope: "commercial_licensed",
      reviewStatus: "needs_review",
      metadata: {
        runtimeCandidates: ["threejs", "react-three-fiber"],
        interactionModes: ["therapist_structure_selection", "client_pain_selection", "rom_visualization", "anatomy_game_prompting"],
        modelAssetStatus: "candidate_not_imported",
        stableContract: ["entityType", "entitySlug", "mappingPrecision", "bodyparts3dPartIds"],
      },
    },
  ],
  spatialEntityMaps: spatialMaps,
  movementVisualizations,
  citations: [
    {
      id: `citation-${BODY_MAP_MODEL_ASSET_SLUG}-media-source`,
      slug: `citation-${BODY_MAP_MODEL_ASSET_SLUG}-media-source`,
      entityType: "region",
      entitySlug: "body-surface",
      factType: "media_source",
      factSlug: BODY_MAP_MODEL_ASSET_SLUG,
      sourceRef: BODY_PARTS_3D_SOURCE,
      sourceLocator: "https://dbarchive.biosciencedbc.jp/en/bodyparts3d/",
      citationNote: "BodyParts3D source candidate for future runtime 3D model import. Runtime conversion and mesh review remain pending.",
      reviewStatus: "needs_review",
    },
    {
      id: `citation-${BODY_MAP_MODEL_ASSET_SLUG}-media-license`,
      slug: `citation-${BODY_MAP_MODEL_ASSET_SLUG}-media-license`,
      entityType: "region",
      entitySlug: "body-surface",
      factType: "media_license",
      factSlug: BODY_MAP_MODEL_ASSET_SLUG,
      sourceRef: BODY_PARTS_3D_SOURCE,
      sourceLocator: BODY_PARTS_3D_LICENSE_URL,
      citationNote: "Official BodyParts3D archive license page lists Creative Commons Attribution 4.0 International and attribution requirements.",
      reviewStatus: "reviewed",
    },
    {
      id: `citation-${BODY_MAP_MODEL_SLUG}-spatial-model-protocol`,
      slug: `citation-${BODY_MAP_MODEL_SLUG}-spatial-model-protocol`,
      entityType: "region",
      entitySlug: "body-surface",
      factType: "spatial_model_protocol",
      factSlug: BODY_MAP_MODEL_SLUG,
      sourceRef: SPATIAL_PROTOCOL_SOURCE,
      sourceLocator: "MassageLab authored 3D body-map interaction protocol.",
      citationNote: "Internal product metadata defining coordinate, selection, and ROM visualization conventions for future runtime 3D body-map work.",
      reviewStatus: "needs_review",
    },
    ...spatialMaps.map(spatialMapCitation),
    ...movementVisualizations.map(movementVisualizationCitation),
  ],
}
