import type { AnatomySeedSection } from "./sections.ts"

const STARTER_SOURCE = "massagelab-initial-anatomy-foundation"
const REVIEW_SOURCE = "future-clinical-citation-needed"

export const WHOLE_BODY_SCAFFOLD_SECTION: AnatomySeedSection = {
  bodyRegions: [
    { id: "region-trunk-spine-pelvis", slug: "trunk-spine-pelvis", name: "Trunk, Spine, and Pelvis", description: "Whole-body scaffold region for axial trunk, spine, abdomen, and pelvis anatomy.", sourceRefs: [STARTER_SOURCE] },
    { id: "region-upper-limb", slug: "upper-limb", name: "Upper Limb", description: "Whole-body scaffold region for arm, forearm, wrist, and hand anatomy.", sourceRefs: [STARTER_SOURCE] },
    { id: "region-lower-limb", slug: "lower-limb", name: "Lower Limb", description: "Whole-body scaffold region for hip, thigh, knee, leg, ankle, and foot anatomy.", sourceRefs: [STARTER_SOURCE] },
    { id: "region-head-face-jaw", slug: "head-face-jaw", name: "Head, Face, and Jaw", description: "Whole-body scaffold region for face, jaw, scalp, and TMJ anatomy.", sourceRefs: [STARTER_SOURCE] },
  ],
  bodySubregions: [
    { id: "subregion-head", slug: "head", name: "Head", region: "head-face-jaw", sourceRefs: [STARTER_SOURCE] },
    { id: "subregion-face", slug: "face", name: "Face", region: "head-face-jaw", sourceRefs: [STARTER_SOURCE] },
    { id: "subregion-jaw", slug: "jaw", name: "Jaw", region: "head-face-jaw", sourceRefs: [STARTER_SOURCE] },
    { id: "subregion-neck", slug: "neck", name: "Neck", region: "head-face-jaw", sourceRefs: [STARTER_SOURCE] },
    { id: "subregion-thorax", slug: "thorax", name: "Thorax", region: "trunk-spine-pelvis", sourceRefs: [STARTER_SOURCE] },
    { id: "subregion-abdomen", slug: "abdomen", name: "Abdomen", region: "trunk-spine-pelvis", sourceRefs: [STARTER_SOURCE] },
    { id: "subregion-pelvis", slug: "pelvis", name: "Pelvis", region: "trunk-spine-pelvis", sourceRefs: [STARTER_SOURCE] },
    { id: "subregion-back", slug: "back", name: "Back", region: "trunk-spine-pelvis", sourceRefs: [STARTER_SOURCE] },
    { id: "subregion-lumbar-region", slug: "lumbar-region", name: "Lumbar Region", region: "trunk-spine-pelvis", sourceRefs: [STARTER_SOURCE] },
    { id: "subregion-arm", slug: "arm", name: "Arm", region: "upper-limb", sourceRefs: [STARTER_SOURCE] },
    { id: "subregion-elbow", slug: "elbow", name: "Elbow", region: "upper-limb", sourceRefs: [STARTER_SOURCE] },
    { id: "subregion-forearm", slug: "forearm", name: "Forearm", region: "upper-limb", sourceRefs: [STARTER_SOURCE] },
    { id: "subregion-wrist", slug: "wrist", name: "Wrist", region: "upper-limb", sourceRefs: [STARTER_SOURCE] },
    { id: "subregion-hand", slug: "hand", name: "Hand", region: "upper-limb", sourceRefs: [STARTER_SOURCE] },
    { id: "subregion-hip", slug: "hip", name: "Hip", region: "lower-limb", sourceRefs: [STARTER_SOURCE] },
    { id: "subregion-thigh", slug: "thigh", name: "Thigh", region: "lower-limb", sourceRefs: [STARTER_SOURCE] },
    { id: "subregion-knee", slug: "knee", name: "Knee", region: "lower-limb", sourceRefs: [STARTER_SOURCE] },
    { id: "subregion-leg", slug: "leg", name: "Leg", region: "lower-limb", sourceRefs: [STARTER_SOURCE] },
    { id: "subregion-ankle", slug: "ankle", name: "Ankle", region: "lower-limb", sourceRefs: [STARTER_SOURCE] },
    { id: "subregion-foot", slug: "foot", name: "Foot", region: "lower-limb", sourceRefs: [STARTER_SOURCE] },
  ],
  structures: [
    { id: "structure-intervertebral-disc", slug: "intervertebral-disc", name: "Intervertebral Disc", structureType: "cartilage_disc", region: "trunk-spine-pelvis", description: "Fibrocartilaginous structure between adjacent vertebral bodies.", sourceRef: REVIEW_SOURCE },
    { id: "structure-thoracolumbar-fascia", slug: "thoracolumbar-fascia", name: "Thoracolumbar Fascia", structureType: "fascia", region: "trunk-spine-pelvis", description: "Dense fascial layer of the posterior trunk and lumbar region.", sourceRef: REVIEW_SOURCE },
    { id: "structure-abdominal-aponeurosis", slug: "abdominal-aponeurosis", name: "Abdominal Aponeurosis", structureType: "aponeurosis", region: "trunk-spine-pelvis", sourceRef: REVIEW_SOURCE },
    { id: "structure-temporomandibular-articular-disc", slug: "temporomandibular-articular-disc", name: "Temporomandibular Articular Disc", structureType: "articular_disc", region: "head-face-jaw", sourceRef: REVIEW_SOURCE },
    { id: "structure-biceps-tendon", slug: "biceps-tendon", name: "Biceps Tendon", structureType: "tendon", region: "upper-limb", sourceRef: REVIEW_SOURCE },
    { id: "structure-triceps-tendon", slug: "triceps-tendon", name: "Triceps Tendon", structureType: "tendon", region: "upper-limb", sourceRef: REVIEW_SOURCE },
    { id: "structure-flexor-retinaculum", slug: "flexor-retinaculum", name: "Flexor Retinaculum", structureType: "retinaculum", region: "upper-limb", sourceRef: REVIEW_SOURCE },
    { id: "structure-iliotibial-band", slug: "iliotibial-band", name: "Iliotibial Band", structureType: "fascia", region: "lower-limb", sourceRef: REVIEW_SOURCE },
    { id: "structure-knee-meniscus", slug: "knee-meniscus", name: "Knee Meniscus", structureType: "fibrocartilage", region: "lower-limb", sourceRef: REVIEW_SOURCE },
    { id: "structure-patellar-tendon", slug: "patellar-tendon", name: "Patellar Tendon", structureType: "tendon", region: "knee", description: "Patellar ligament or tendon region connecting the patella to the tibial tuberosity as part of the knee extensor apparatus.", sourceRef: "applied-human-anatomy" },
    { id: "structure-achilles-tendon", slug: "achilles-tendon", name: "Achilles Tendon", structureType: "tendon", region: "lower-limb", sourceRef: REVIEW_SOURCE },
    { id: "structure-plantar-fascia", slug: "plantar-fascia", name: "Plantar Fascia", structureType: "fascia", region: "lower-limb", sourceRef: REVIEW_SOURCE },
  ],
  painMapRegions: [
    { id: "painmap-low-back", slug: "low-back", name: "Low Back", region: "lumbar-region", laterality: "midline", surface: "posterior", plainLanguageDescription: "Client-friendly low back region.", sourceRef: STARTER_SOURCE },
    { id: "painmap-abdomen", slug: "abdomen", name: "Abdomen", region: "abdomen", laterality: "midline", surface: "anterior", plainLanguageDescription: "Client-friendly front abdominal region.", sourceRef: STARTER_SOURCE },
    { id: "painmap-hip", slug: "hip-area", name: "Hip Area", region: "hip", laterality: "variable", surface: "lateral", plainLanguageDescription: "Client-friendly hip region.", sourceRef: STARTER_SOURCE },
    { id: "painmap-front-thigh", slug: "front-thigh", name: "Front Thigh", region: "thigh", laterality: "variable", surface: "anterior", sourceRef: STARTER_SOURCE },
    { id: "painmap-knee-front", slug: "front-of-knee", name: "Front of Knee", region: "knee", laterality: "variable", surface: "anterior", sourceRef: STARTER_SOURCE },
    { id: "painmap-calf", slug: "calf", name: "Calf", region: "leg", laterality: "variable", surface: "posterior", sourceRef: STARTER_SOURCE },
    { id: "painmap-foot-arch", slug: "foot-arch", name: "Foot Arch", region: "foot", laterality: "variable", surface: "inferior", sourceRef: STARTER_SOURCE },
    { id: "painmap-elbow-area", slug: "elbow-area", name: "Elbow Area", region: "elbow", laterality: "variable", surface: "variable", sourceRef: STARTER_SOURCE },
    { id: "painmap-forearm-area", slug: "forearm-area", name: "Forearm Area", region: "forearm", laterality: "variable", surface: "variable", sourceRef: STARTER_SOURCE },
    { id: "painmap-wrist-hand", slug: "wrist-hand", name: "Wrist and Hand", region: "hand", laterality: "variable", surface: "variable", sourceRef: STARTER_SOURCE },
    { id: "painmap-jaw-area", slug: "jaw-area", name: "Jaw Area", region: "jaw", laterality: "variable", surface: "lateral", sourceRef: STARTER_SOURCE },
  ],
  clientTerms: [
    { id: "client-term-low-back-tightness", slug: "low-back-tightness", term: "low back tightness", plainLanguageDescription: "Client language for the lumbar or low-back region.", mappedRegionSlug: "lumbar-region", confidence: "broad", clinicalUse: "non-diagnostic", likelyRegions: ["lumbar-region", "back"], likelyStructures: ["lumbar-spine", "quadratus-lumborum", "thoracolumbar-fascia"], therapistPrompt: "Use as a conversation starter, then choose clinically relevant structures from assessment findings.", sourceRef: STARTER_SOURCE },
    { id: "client-term-hip-tightness", slug: "hip-tightness", term: "hip tightness", plainLanguageDescription: "Client language for the hip or lateral pelvis region.", mappedRegionSlug: "hip", confidence: "broad", clinicalUse: "non-diagnostic", likelyRegions: ["hip", "pelvis"], likelyStructures: ["hip-joint", "gluteus-medius", "iliotibial-band"], therapistPrompt: "Use as a conversation starter, then choose clinically relevant structures from assessment findings.", sourceRef: STARTER_SOURCE },
    { id: "client-term-knee-pain", slug: "knee-pain", term: "knee pain", plainLanguageDescription: "Client language for the knee region.", mappedRegionSlug: "knee", confidence: "broad", clinicalUse: "non-diagnostic", likelyRegions: ["knee"], likelyStructures: ["knee-joint", "patellar-tendon", "knee-meniscus"], therapistPrompt: "Use as a conversation starter, then choose clinically relevant structures from assessment findings.", sourceRef: STARTER_SOURCE },
    { id: "client-term-calf-tightness", slug: "calf-tightness", term: "calf tightness", plainLanguageDescription: "Client language for the posterior lower leg.", mappedRegionSlug: "leg", confidence: "broad", clinicalUse: "non-diagnostic", likelyRegions: ["leg"], likelyStructures: ["gastrocnemius", "soleus", "achilles-tendon"], therapistPrompt: "Use as a conversation starter, then choose clinically relevant structures from assessment findings.", sourceRef: STARTER_SOURCE },
    { id: "client-term-foot-arch-pain", slug: "foot-arch-pain", term: "foot arch pain", plainLanguageDescription: "Client language for the plantar foot or arch area.", mappedRegionSlug: "foot", confidence: "broad", clinicalUse: "non-diagnostic", likelyRegions: ["foot"], likelyStructures: ["plantar-fascia"], therapistPrompt: "Use as a conversation starter, then choose clinically relevant structures from assessment findings.", sourceRef: STARTER_SOURCE },
    { id: "client-term-forearm-tightness", slug: "forearm-tightness", term: "forearm tightness", plainLanguageDescription: "Client language for the forearm region.", mappedRegionSlug: "forearm", confidence: "broad", clinicalUse: "non-diagnostic", likelyRegions: ["forearm"], likelyStructures: ["wrist-flexor-group", "wrist-extensor-group"], therapistPrompt: "Use as a conversation starter, then choose clinically relevant structures from assessment findings.", sourceRef: STARTER_SOURCE },
    { id: "client-term-wrist-tightness", slug: "wrist-tightness", term: "wrist tightness", plainLanguageDescription: "Client language for wrist or hand tension.", mappedRegionSlug: "wrist", confidence: "broad", clinicalUse: "non-diagnostic", likelyRegions: ["wrist", "hand"], likelyStructures: ["flexor-retinaculum", "wrist-flexor-group"], therapistPrompt: "Use as a conversation starter, then choose clinically relevant structures from assessment findings.", sourceRef: STARTER_SOURCE },
    { id: "client-term-jaw-tension", slug: "jaw-tension", term: "jaw tension", plainLanguageDescription: "Client language for jaw or TMJ-area tension.", mappedRegionSlug: "jaw", confidence: "broad", clinicalUse: "non-diagnostic", likelyRegions: ["jaw", "face"], likelyStructures: ["temporomandibular-joint", "masseter", "temporomandibular-articular-disc"], therapistPrompt: "Use as a conversation starter, then choose clinically relevant structures from assessment findings.", sourceRef: STARTER_SOURCE },
  ],
  entityTerms: [
    { id: "term-plantar-fascia-formal", anatomyEntityType: "anatomy_structure", anatomyEntitySlug: "plantar-fascia", term: "Plantar fascia", termType: "formal", sourceRef: REVIEW_SOURCE },
    { id: "term-achilles-tendon-common", anatomyEntityType: "anatomy_structure", anatomyEntitySlug: "achilles-tendon", term: "Achilles tendon", termType: "common", sourceRef: REVIEW_SOURCE },
    { id: "term-tmj-disc-formal", anatomyEntityType: "anatomy_structure", anatomyEntitySlug: "temporomandibular-articular-disc", term: "Temporomandibular articular disc", termType: "formal", sourceRef: REVIEW_SOURCE },
    { id: "term-it-band-common", anatomyEntityType: "anatomy_structure", anatomyEntitySlug: "iliotibial-band", term: "IT band", termType: "common", sourceRef: STARTER_SOURCE },
  ],
  citations: [
    { id: "citation-whole-body-scaffold-review-needed", slug: "citation-whole-body-scaffold-review-needed", entityType: "region", entitySlug: "trunk-spine-pelvis", factType: "section_scaffold", sourceRef: REVIEW_SOURCE, citationNote: "Whole-body scaffold placeholder pending section-level citation review.", reviewStatus: "needs_review" },
  ],
}
